// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type AssignServerVirtualNetworkPrivateNetworksType string

const (
	AssignServerVirtualNetworkPrivateNetworksTypeVirtualNetworkAssignment AssignServerVirtualNetworkPrivateNetworksType = "virtual_network_assignment"
)

func (e AssignServerVirtualNetworkPrivateNetworksType) ToPointer() *AssignServerVirtualNetworkPrivateNetworksType {
	return &e
}
func (e *AssignServerVirtualNetworkPrivateNetworksType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "virtual_network_assignment":
		*e = AssignServerVirtualNetworkPrivateNetworksType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AssignServerVirtualNetworkPrivateNetworksType: %v", v)
	}
}

type AssignServerVirtualNetworkPrivateNetworksAttributes struct {
	ServerID         string `json:"server_id"`
	VirtualNetworkID string `json:"virtual_network_id"`
}

func (a *AssignServerVirtualNetworkPrivateNetworksAttributes) GetServerID() string {
	if a == nil {
		return ""
	}
	return a.ServerID
}

func (a *AssignServerVirtualNetworkPrivateNetworksAttributes) GetVirtualNetworkID() string {
	if a == nil {
		return ""
	}
	return a.VirtualNetworkID
}

type AssignServerVirtualNetworkPrivateNetworksData struct {
	Type       AssignServerVirtualNetworkPrivateNetworksType        `json:"type"`
	Attributes *AssignServerVirtualNetworkPrivateNetworksAttributes `json:"attributes,omitempty"`
}

func (a *AssignServerVirtualNetworkPrivateNetworksData) GetType() AssignServerVirtualNetworkPrivateNetworksType {
	if a == nil {
		return AssignServerVirtualNetworkPrivateNetworksType("")
	}
	return a.Type
}

func (a *AssignServerVirtualNetworkPrivateNetworksData) GetAttributes() *AssignServerVirtualNetworkPrivateNetworksAttributes {
	if a == nil {
		return nil
	}
	return a.Attributes
}

type AssignServerVirtualNetworkPrivateNetworksRequestBody struct {
	Data *AssignServerVirtualNetworkPrivateNetworksData `json:"data,omitempty"`
}

func (a *AssignServerVirtualNetworkPrivateNetworksRequestBody) GetData() *AssignServerVirtualNetworkPrivateNetworksData {
	if a == nil {
		return nil
	}
	return a.Data
}

type AssignServerVirtualNetworkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	VirtualNetworkAssignment *components.VirtualNetworkAssignment
}

func (a *AssignServerVirtualNetworkResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AssignServerVirtualNetworkResponse) GetVirtualNetworkAssignment() *components.VirtualNetworkAssignment {
	if a == nil {
		return nil
	}
	return a.VirtualNetworkAssignment
}
