// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type CreateTagTagsType string

const (
	CreateTagTagsTypeTags CreateTagTagsType = "tags"
)

func (e CreateTagTagsType) ToPointer() *CreateTagTagsType {
	return &e
}
func (e *CreateTagTagsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tags":
		*e = CreateTagTagsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateTagTagsType: %v", v)
	}
}

type CreateTagTagsAttributes struct {
	// Name of the Tag
	Name *string `json:"name,omitempty"`
	// Description of the Tag
	Description *string `json:"description,omitempty"`
	// Color of the Tag
	Color *string `default:"#ffffff" json:"color"`
}

func (c CreateTagTagsAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTagTagsAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateTagTagsAttributes) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateTagTagsAttributes) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateTagTagsAttributes) GetColor() *string {
	if c == nil {
		return nil
	}
	return c.Color
}

type CreateTagTagsData struct {
	Type       *CreateTagTagsType       `json:"type,omitempty"`
	Attributes *CreateTagTagsAttributes `json:"attributes,omitempty"`
}

func (c *CreateTagTagsData) GetType() *CreateTagTagsType {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *CreateTagTagsData) GetAttributes() *CreateTagTagsAttributes {
	if c == nil {
		return nil
	}
	return c.Attributes
}

type CreateTagTagsRequestBody struct {
	Data *CreateTagTagsData `json:"data,omitempty"`
}

func (c *CreateTagTagsRequestBody) GetData() *CreateTagTagsData {
	if c == nil {
		return nil
	}
	return c.Data
}

type CreateTagResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	CustomTag *components.CustomTag
}

func (c *CreateTagResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateTagResponse) GetCustomTag() *components.CustomTag {
	if c == nil {
		return nil
	}
	return c.CustomTag
}
