// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type CreateVirtualNetworkPrivateNetworksType string

const (
	CreateVirtualNetworkPrivateNetworksTypeVirtualNetwork CreateVirtualNetworkPrivateNetworksType = "virtual_network"
)

func (e CreateVirtualNetworkPrivateNetworksType) ToPointer() *CreateVirtualNetworkPrivateNetworksType {
	return &e
}
func (e *CreateVirtualNetworkPrivateNetworksType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "virtual_network":
		*e = CreateVirtualNetworkPrivateNetworksType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateVirtualNetworkPrivateNetworksType: %v", v)
	}
}

// CreateVirtualNetworkPrivateNetworksSite - Site ID or slug (case-insensitive)
type CreateVirtualNetworkPrivateNetworksSite string

const (
	CreateVirtualNetworkPrivateNetworksSiteAsh  CreateVirtualNetworkPrivateNetworksSite = "ASH"
	CreateVirtualNetworkPrivateNetworksSiteBgt  CreateVirtualNetworkPrivateNetworksSite = "BGT"
	CreateVirtualNetworkPrivateNetworksSiteBue  CreateVirtualNetworkPrivateNetworksSite = "BUE"
	CreateVirtualNetworkPrivateNetworksSiteChi  CreateVirtualNetworkPrivateNetworksSite = "CHI"
	CreateVirtualNetworkPrivateNetworksSiteDal  CreateVirtualNetworkPrivateNetworksSite = "DAL"
	CreateVirtualNetworkPrivateNetworksSiteFra  CreateVirtualNetworkPrivateNetworksSite = "FRA"
	CreateVirtualNetworkPrivateNetworksSiteLax  CreateVirtualNetworkPrivateNetworksSite = "LAX"
	CreateVirtualNetworkPrivateNetworksSiteLon  CreateVirtualNetworkPrivateNetworksSite = "LON"
	CreateVirtualNetworkPrivateNetworksSiteMex  CreateVirtualNetworkPrivateNetworksSite = "MEX"
	CreateVirtualNetworkPrivateNetworksSiteMex2 CreateVirtualNetworkPrivateNetworksSite = "MEX2"
	CreateVirtualNetworkPrivateNetworksSiteMia  CreateVirtualNetworkPrivateNetworksSite = "MIA"
	CreateVirtualNetworkPrivateNetworksSiteMia2 CreateVirtualNetworkPrivateNetworksSite = "MIA2"
	CreateVirtualNetworkPrivateNetworksSiteNyc  CreateVirtualNetworkPrivateNetworksSite = "NYC"
	CreateVirtualNetworkPrivateNetworksSiteSan  CreateVirtualNetworkPrivateNetworksSite = "SAN"
	CreateVirtualNetworkPrivateNetworksSiteSao  CreateVirtualNetworkPrivateNetworksSite = "SAO"
	CreateVirtualNetworkPrivateNetworksSiteSao2 CreateVirtualNetworkPrivateNetworksSite = "SAO2"
	CreateVirtualNetworkPrivateNetworksSiteSyd  CreateVirtualNetworkPrivateNetworksSite = "SYD"
	CreateVirtualNetworkPrivateNetworksSiteTyo  CreateVirtualNetworkPrivateNetworksSite = "TYO"
	CreateVirtualNetworkPrivateNetworksSiteTyo2 CreateVirtualNetworkPrivateNetworksSite = "TYO2"
)

func (e CreateVirtualNetworkPrivateNetworksSite) ToPointer() *CreateVirtualNetworkPrivateNetworksSite {
	return &e
}
func (e *CreateVirtualNetworkPrivateNetworksSite) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ASH":
		fallthrough
	case "BGT":
		fallthrough
	case "BUE":
		fallthrough
	case "CHI":
		fallthrough
	case "DAL":
		fallthrough
	case "FRA":
		fallthrough
	case "LAX":
		fallthrough
	case "LON":
		fallthrough
	case "MEX":
		fallthrough
	case "MEX2":
		fallthrough
	case "MIA":
		fallthrough
	case "MIA2":
		fallthrough
	case "NYC":
		fallthrough
	case "SAN":
		fallthrough
	case "SAO":
		fallthrough
	case "SAO2":
		fallthrough
	case "SYD":
		fallthrough
	case "TYO":
		fallthrough
	case "TYO2":
		*e = CreateVirtualNetworkPrivateNetworksSite(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateVirtualNetworkPrivateNetworksSite: %v", v)
	}
}

type CreateVirtualNetworkPrivateNetworksAttributes struct {
	Description string `json:"description"`
	// Site ID or slug (case-insensitive)
	Site *CreateVirtualNetworkPrivateNetworksSite `json:"site,omitempty"`
	// Project ID or slug
	Project string `json:"project"`
}

func (c *CreateVirtualNetworkPrivateNetworksAttributes) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *CreateVirtualNetworkPrivateNetworksAttributes) GetSite() *CreateVirtualNetworkPrivateNetworksSite {
	if c == nil {
		return nil
	}
	return c.Site
}

func (c *CreateVirtualNetworkPrivateNetworksAttributes) GetProject() string {
	if c == nil {
		return ""
	}
	return c.Project
}

type CreateVirtualNetworkPrivateNetworksData struct {
	Type       CreateVirtualNetworkPrivateNetworksType       `json:"type"`
	Attributes CreateVirtualNetworkPrivateNetworksAttributes `json:"attributes"`
}

func (c *CreateVirtualNetworkPrivateNetworksData) GetType() CreateVirtualNetworkPrivateNetworksType {
	if c == nil {
		return CreateVirtualNetworkPrivateNetworksType("")
	}
	return c.Type
}

func (c *CreateVirtualNetworkPrivateNetworksData) GetAttributes() CreateVirtualNetworkPrivateNetworksAttributes {
	if c == nil {
		return CreateVirtualNetworkPrivateNetworksAttributes{}
	}
	return c.Attributes
}

type CreateVirtualNetworkPrivateNetworksRequestBody struct {
	Data CreateVirtualNetworkPrivateNetworksData `json:"data"`
}

func (c *CreateVirtualNetworkPrivateNetworksRequestBody) GetData() CreateVirtualNetworkPrivateNetworksData {
	if c == nil {
		return CreateVirtualNetworkPrivateNetworksData{}
	}
	return c.Data
}

type CreateVirtualNetworkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	VirtualNetwork *components.VirtualNetwork
}

func (c *CreateVirtualNetworkResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateVirtualNetworkResponse) GetVirtualNetwork() *components.VirtualNetwork {
	if c == nil {
		return nil
	}
	return c.VirtualNetwork
}
