// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type CreateLksClusterResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	LksCluster *components.LksCluster
}

func (c *CreateLksClusterResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateLksClusterResponse) GetLksCluster() *components.LksCluster {
	if c == nil {
		return nil
	}
	return c.LksCluster
}
