// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type CreateElasticIPResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Accepted
	ElasticIP *components.ElasticIP
}

func (c *CreateElasticIPResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateElasticIPResponse) GetElasticIP() *components.ElasticIP {
	if c == nil {
		return nil
	}
	return c.ElasticIP
}
