// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type CreateServerActionServersType string

const (
	CreateServerActionServersTypeActions CreateServerActionServersType = "actions"
)

func (e CreateServerActionServersType) ToPointer() *CreateServerActionServersType {
	return &e
}
func (e *CreateServerActionServersType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "actions":
		*e = CreateServerActionServersType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateServerActionServersType: %v", v)
	}
}

// CreateServerActionAction - The action to perform on the server
type CreateServerActionAction string

const (
	CreateServerActionActionPowerOn  CreateServerActionAction = "power_on"
	CreateServerActionActionPowerOff CreateServerActionAction = "power_off"
	CreateServerActionActionReboot   CreateServerActionAction = "reboot"
)

func (e CreateServerActionAction) ToPointer() *CreateServerActionAction {
	return &e
}
func (e *CreateServerActionAction) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "power_on":
		fallthrough
	case "power_off":
		fallthrough
	case "reboot":
		*e = CreateServerActionAction(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateServerActionAction: %v", v)
	}
}

type CreateServerActionServersAttributes struct {
	// The action to perform on the server
	Action CreateServerActionAction `json:"action"`
}

func (c *CreateServerActionServersAttributes) GetAction() CreateServerActionAction {
	if c == nil {
		return CreateServerActionAction("")
	}
	return c.Action
}

type CreateServerActionServersData struct {
	Type       CreateServerActionServersType        `json:"type"`
	Attributes *CreateServerActionServersAttributes `json:"attributes,omitempty"`
}

func (c *CreateServerActionServersData) GetType() CreateServerActionServersType {
	if c == nil {
		return CreateServerActionServersType("")
	}
	return c.Type
}

func (c *CreateServerActionServersData) GetAttributes() *CreateServerActionServersAttributes {
	if c == nil {
		return nil
	}
	return c.Attributes
}

type CreateServerActionServersRequestBody struct {
	Data CreateServerActionServersData `json:"data"`
}

func (c *CreateServerActionServersRequestBody) GetData() CreateServerActionServersData {
	if c == nil {
		return CreateServerActionServersData{}
	}
	return c.Data
}

type CreateServerActionRequest struct {
	ServerID    string                               `pathParam:"style=simple,explode=false,name=server_id"`
	RequestBody CreateServerActionServersRequestBody `request:"mediaType=application/json"`
}

func (c *CreateServerActionRequest) GetServerID() string {
	if c == nil {
		return ""
	}
	return c.ServerID
}

func (c *CreateServerActionRequest) GetRequestBody() CreateServerActionServersRequestBody {
	if c == nil {
		return CreateServerActionServersRequestBody{}
	}
	return c.RequestBody
}

type CreateServerActionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	ServerAction *components.ServerAction
}

func (c *CreateServerActionResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateServerActionResponse) GetServerAction() *components.ServerAction {
	if c == nil {
		return nil
	}
	return c.ServerAction
}
