// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type CreateVirtualMachineBackupTopLevelResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	VirtualMachineBackup *components.VirtualMachineBackup
}

func (c *CreateVirtualMachineBackupTopLevelResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateVirtualMachineBackupTopLevelResponse) GetVirtualMachineBackup() *components.VirtualMachineBackup {
	if c == nil {
		return nil
	}
	return c.VirtualMachineBackup
}
