// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type CreateVirtualNetworkPrivateNetworksType string

const (
	CreateVirtualNetworkPrivateNetworksTypeVirtualNetwork CreateVirtualNetworkPrivateNetworksType = "virtual_network"
)

func (e CreateVirtualNetworkPrivateNetworksType) ToPointer() *CreateVirtualNetworkPrivateNetworksType {
	return &e
}
func (e *CreateVirtualNetworkPrivateNetworksType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "virtual_network":
		*e = CreateVirtualNetworkPrivateNetworksType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateVirtualNetworkPrivateNetworksType: %v", v)
	}
}

// CreateVirtualNetworkPrivateNetworksSite - Site slug
type CreateVirtualNetworkPrivateNetworksSite string

const (
	CreateVirtualNetworkPrivateNetworksSiteAms  CreateVirtualNetworkPrivateNetworksSite = "AMS"
	CreateVirtualNetworkPrivateNetworksSiteAsh  CreateVirtualNetworkPrivateNetworksSite = "ASH"
	CreateVirtualNetworkPrivateNetworksSiteAsh2 CreateVirtualNetworkPrivateNetworksSite = "ASH2"
	CreateVirtualNetworkPrivateNetworksSiteBgt  CreateVirtualNetworkPrivateNetworksSite = "BGT"
	CreateVirtualNetworkPrivateNetworksSiteBue  CreateVirtualNetworkPrivateNetworksSite = "BUE"
	CreateVirtualNetworkPrivateNetworksSiteChi  CreateVirtualNetworkPrivateNetworksSite = "CHI"
	CreateVirtualNetworkPrivateNetworksSiteDal  CreateVirtualNetworkPrivateNetworksSite = "DAL"
	CreateVirtualNetworkPrivateNetworksSiteFra  CreateVirtualNetworkPrivateNetworksSite = "FRA"
	CreateVirtualNetworkPrivateNetworksSiteFra2 CreateVirtualNetworkPrivateNetworksSite = "FRA2"
	CreateVirtualNetworkPrivateNetworksSiteLax  CreateVirtualNetworkPrivateNetworksSite = "LAX"
	CreateVirtualNetworkPrivateNetworksSiteLax2 CreateVirtualNetworkPrivateNetworksSite = "LAX2"
	CreateVirtualNetworkPrivateNetworksSiteLon  CreateVirtualNetworkPrivateNetworksSite = "LON"
	CreateVirtualNetworkPrivateNetworksSiteLon2 CreateVirtualNetworkPrivateNetworksSite = "LON2"
	CreateVirtualNetworkPrivateNetworksSiteMex2 CreateVirtualNetworkPrivateNetworksSite = "MEX2"
	CreateVirtualNetworkPrivateNetworksSiteMia2 CreateVirtualNetworkPrivateNetworksSite = "MIA2"
	CreateVirtualNetworkPrivateNetworksSiteNyc  CreateVirtualNetworkPrivateNetworksSite = "NYC"
	CreateVirtualNetworkPrivateNetworksSiteSan3 CreateVirtualNetworkPrivateNetworksSite = "SAN3"
	CreateVirtualNetworkPrivateNetworksSiteSao  CreateVirtualNetworkPrivateNetworksSite = "SAO"
	CreateVirtualNetworkPrivateNetworksSiteSao2 CreateVirtualNetworkPrivateNetworksSite = "SAO2"
	CreateVirtualNetworkPrivateNetworksSiteSgp  CreateVirtualNetworkPrivateNetworksSite = "SGP"
	CreateVirtualNetworkPrivateNetworksSiteSjc2 CreateVirtualNetworkPrivateNetworksSite = "SJC2"
	CreateVirtualNetworkPrivateNetworksSiteSyd  CreateVirtualNetworkPrivateNetworksSite = "SYD"
	CreateVirtualNetworkPrivateNetworksSiteSyd2 CreateVirtualNetworkPrivateNetworksSite = "SYD2"
	CreateVirtualNetworkPrivateNetworksSiteTor  CreateVirtualNetworkPrivateNetworksSite = "TOR"
	CreateVirtualNetworkPrivateNetworksSiteTyo3 CreateVirtualNetworkPrivateNetworksSite = "TYO3"
	CreateVirtualNetworkPrivateNetworksSiteTyo4 CreateVirtualNetworkPrivateNetworksSite = "TYO4"
)

func (e CreateVirtualNetworkPrivateNetworksSite) ToPointer() *CreateVirtualNetworkPrivateNetworksSite {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CreateVirtualNetworkPrivateNetworksSite) IsExact() bool {
	if e != nil {
		switch *e {
		case "AMS", "ASH", "ASH2", "BGT", "BUE", "CHI", "DAL", "FRA", "FRA2", "LAX", "LAX2", "LON", "LON2", "MEX2", "MIA2", "NYC", "SAN3", "SAO", "SAO2", "SGP", "SJC2", "SYD", "SYD2", "TOR", "TYO3", "TYO4":
			return true
		}
	}
	return false
}

type CreateVirtualNetworkPrivateNetworksAttributes struct {
	Description string `json:"description"`
	// Site slug
	Site *CreateVirtualNetworkPrivateNetworksSite `json:"site,omitempty"`
	// Project ID or slug
	Project string `json:"project"`
}

func (c *CreateVirtualNetworkPrivateNetworksAttributes) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *CreateVirtualNetworkPrivateNetworksAttributes) GetSite() *CreateVirtualNetworkPrivateNetworksSite {
	if c == nil {
		return nil
	}
	return c.Site
}

func (c *CreateVirtualNetworkPrivateNetworksAttributes) GetProject() string {
	if c == nil {
		return ""
	}
	return c.Project
}

type CreateVirtualNetworkPrivateNetworksData struct {
	Type       CreateVirtualNetworkPrivateNetworksType       `json:"type"`
	Attributes CreateVirtualNetworkPrivateNetworksAttributes `json:"attributes"`
}

func (c *CreateVirtualNetworkPrivateNetworksData) GetType() CreateVirtualNetworkPrivateNetworksType {
	if c == nil {
		return CreateVirtualNetworkPrivateNetworksType("")
	}
	return c.Type
}

func (c *CreateVirtualNetworkPrivateNetworksData) GetAttributes() CreateVirtualNetworkPrivateNetworksAttributes {
	if c == nil {
		return CreateVirtualNetworkPrivateNetworksAttributes{}
	}
	return c.Attributes
}

type CreateVirtualNetworkPrivateNetworksRequestBody struct {
	Data CreateVirtualNetworkPrivateNetworksData `json:"data"`
}

func (c *CreateVirtualNetworkPrivateNetworksRequestBody) GetData() CreateVirtualNetworkPrivateNetworksData {
	if c == nil {
		return CreateVirtualNetworkPrivateNetworksData{}
	}
	return c.Data
}

type CreateVirtualNetworkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	VirtualNetwork *components.VirtualNetwork
}

func (c *CreateVirtualNetworkResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateVirtualNetworkResponse) GetVirtualNetwork() *components.VirtualNetwork {
	if c == nil {
		return nil
	}
	return c.VirtualNetwork
}
