// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type DeleteVpnSessionRequest struct {
	VpnSessionID string `pathParam:"style=simple,explode=false,name=vpn_session_id"`
}

func (d *DeleteVpnSessionRequest) GetVpnSessionID() string {
	if d == nil {
		return ""
	}
	return d.VpnSessionID
}

type DeleteVpnSessionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteVpnSessionResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
