// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type DeleteVirtualNetworksAssignmentsRequest struct {
	AssignmentID string `pathParam:"style=simple,explode=false,name=assignment_id"`
}

func (d *DeleteVirtualNetworksAssignmentsRequest) GetAssignmentID() string {
	if d == nil {
		return ""
	}
	return d.AssignmentID
}

type DeleteVirtualNetworksAssignmentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteVirtualNetworksAssignmentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
