// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

// PathParamStorageClass - Backend storage tier of the access key. `standard` targets Wasabi; `high_performance` targets VAST.
type PathParamStorageClass string

const (
	PathParamStorageClassStandard        PathParamStorageClass = "standard"
	PathParamStorageClassHighPerformance PathParamStorageClass = "high_performance"
)

func (e PathParamStorageClass) ToPointer() *PathParamStorageClass {
	return &e
}
func (e *PathParamStorageClass) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "standard":
		fallthrough
	case "high_performance":
		*e = PathParamStorageClass(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PathParamStorageClass: %v", v)
	}
}

type DeleteStorageAccessKeysUsernameRequest struct {
	// Name of the access key to delete.
	Username string `pathParam:"style=simple,explode=false,name=username"`
	// Backend storage tier of the access key. `standard` targets Wasabi; `high_performance` targets VAST.
	StorageClass PathParamStorageClass `pathParam:"style=simple,explode=false,name=storage_class"`
	// Project ID or slug the access key belongs to.
	Project string `queryParam:"style=form,explode=true,name=project"`
	// Region slug (e.g., `DAL`, `SAO2`). Required for `high_performance` (VAST) keys to select the VAST cluster; ignored for `standard` (Wasabi) keys.
	Region *string `queryParam:"style=form,explode=true,name=region"`
}

func (d *DeleteStorageAccessKeysUsernameRequest) GetUsername() string {
	if d == nil {
		return ""
	}
	return d.Username
}

func (d *DeleteStorageAccessKeysUsernameRequest) GetStorageClass() PathParamStorageClass {
	if d == nil {
		return PathParamStorageClass("")
	}
	return d.StorageClass
}

func (d *DeleteStorageAccessKeysUsernameRequest) GetProject() string {
	if d == nil {
		return ""
	}
	return d.Project
}

func (d *DeleteStorageAccessKeysUsernameRequest) GetRegion() *string {
	if d == nil {
		return nil
	}
	return d.Region
}

type DeleteStorageAccessKeysUsernameResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteStorageAccessKeysUsernameResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
