// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type DeleteLksNodePoolRequest struct {
	// The cluster ID (format: `lksc_<hash>`).
	ClusterID string `pathParam:"style=simple,explode=false,name=cluster_id"`
	// The node pool ID (format: `lksnp_<hash>`).
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteLksNodePoolRequest) GetClusterID() string {
	if d == nil {
		return ""
	}
	return d.ClusterID
}

func (d *DeleteLksNodePoolRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteLksNodePoolResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteLksNodePoolResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
