// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type DeleteKubernetesClusterRequest struct {
	// The cluster name
	KubernetesClusterID string `pathParam:"style=simple,explode=false,name=kubernetes_cluster_id"`
}

func (d *DeleteKubernetesClusterRequest) GetKubernetesClusterID() string {
	if d == nil {
		return ""
	}
	return d.KubernetesClusterID
}

type DeleteKubernetesClusterResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteKubernetesClusterResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
