// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type DeleteProjectSSHKeyRequest struct {
	// Project ID or Slug
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	SSHKeyID  string `pathParam:"style=simple,explode=false,name=ssh_key_id"`
}

func (d *DeleteProjectSSHKeyRequest) GetProjectID() string {
	if d == nil {
		return ""
	}
	return d.ProjectID
}

func (d *DeleteProjectSSHKeyRequest) GetSSHKeyID() string {
	if d == nil {
		return ""
	}
	return d.SSHKeyID
}

type DeleteProjectSSHKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteProjectSSHKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
