// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type DestroyVirtualMachineRequest struct {
	VirtualMachineID string `pathParam:"style=simple,explode=false,name=virtual_machine_id"`
}

func (d *DestroyVirtualMachineRequest) GetVirtualMachineID() string {
	if d == nil {
		return ""
	}
	return d.VirtualMachineID
}

type DestroyVirtualMachineResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DestroyVirtualMachineResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
