// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type DestroyPrefixRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DestroyPrefixRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DestroyPrefixResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DestroyPrefixResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
