// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetAllFirewallAssignmentsRequest struct {
	// The server ID to filter by
	FilterServer *string `queryParam:"style=form,explode=true,name=filter[server]"`
	// Number of items to return per page
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=page[size]"`
	// Page number to return (starts at 1)
	PageNumber *int64 `default:"1" queryParam:"style=form,explode=true,name=page[number]"`
}

func (g GetAllFirewallAssignmentsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAllFirewallAssignmentsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAllFirewallAssignmentsRequest) GetFilterServer() *string {
	if g == nil {
		return nil
	}
	return g.FilterServer
}

func (g *GetAllFirewallAssignmentsRequest) GetPageSize() *int64 {
	if g == nil {
		return nil
	}
	return g.PageSize
}

func (g *GetAllFirewallAssignmentsRequest) GetPageNumber() *int64 {
	if g == nil {
		return nil
	}
	return g.PageNumber
}

type GetAllFirewallAssignmentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	FirewallAssignments *components.FirewallAssignments

	Next func() (*GetAllFirewallAssignmentsResponse, error)
}

func (g *GetAllFirewallAssignmentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAllFirewallAssignmentsResponse) GetFirewallAssignments() *components.FirewallAssignments {
	if g == nil {
		return nil
	}
	return g.FirewallAssignments
}
