// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetBaselineRequest struct {
	// Baseline ID
	BaselineID string `pathParam:"style=simple,explode=false,name=baseline_id"`
}

func (g *GetBaselineRequest) GetBaselineID() string {
	if g == nil {
		return ""
	}
	return g.BaselineID
}

type GetBaselineResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Baseline *components.Baseline
}

func (g *GetBaselineResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetBaselineResponse) GetBaseline() *components.Baseline {
	if g == nil {
		return nil
	}
	return g.Baseline
}
