// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetBaselinesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Baselines *components.Baselines
}

func (g *GetBaselinesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetBaselinesResponse) GetBaselines() *components.Baselines {
	if g == nil {
		return nil
	}
	return g.Baselines
}
