// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetBandwidthPlansRequest struct {
	APIVersion *string `default:"2023-06-01" header:"style=simple,explode=false,name=API-Version"`
	// The plan ID to filter by
	FilterID *string `queryParam:"style=form,explode=true,name=filter[id]"`
}

func (g GetBandwidthPlansRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetBandwidthPlansRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetBandwidthPlansRequest) GetAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.APIVersion
}

func (o *GetBandwidthPlansRequest) GetFilterID() *string {
	if o == nil {
		return nil
	}
	return o.FilterID
}

type GetBandwidthPlansResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	BandwidthPlans *components.BandwidthPlans
}

func (o *GetBandwidthPlansResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetBandwidthPlansResponse) GetBandwidthPlans() *components.BandwidthPlans {
	if o == nil {
		return nil
	}
	return o.BandwidthPlans
}
