// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

// QueryParamFilterStockLevel - Filter by the level of containers availability
type QueryParamFilterStockLevel string

const (
	QueryParamFilterStockLevelUnavailable QueryParamFilterStockLevel = "unavailable"
	QueryParamFilterStockLevelLow         QueryParamFilterStockLevel = "low"
	QueryParamFilterStockLevelMedium      QueryParamFilterStockLevel = "medium"
	QueryParamFilterStockLevelHigh        QueryParamFilterStockLevel = "high"
)

func (e QueryParamFilterStockLevel) ToPointer() *QueryParamFilterStockLevel {
	return &e
}
func (e *QueryParamFilterStockLevel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "unavailable":
		fallthrough
	case "low":
		fallthrough
	case "medium":
		fallthrough
	case "high":
		*e = QueryParamFilterStockLevel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamFilterStockLevel: %v", v)
	}
}

type GetContainersPlansRequest struct {
	// The plan name to filter by
	FilterName *string `queryParam:"style=form,explode=true,name=filter[name]"`
	// The plan slug to filter by
	FilterSlug *string `queryParam:"style=form,explode=true,name=filter[slug]"`
	// The location of the site to filter by
	FilterLocation *string `queryParam:"style=form,explode=true,name=filter[location]"`
	// Filter by the level of containers availability
	FilterStockLevel *QueryParamFilterStockLevel `queryParam:"style=form,explode=true,name=filter[stock_level]"`
	// The stock available at the site to filter by
	FilterInStock *bool `queryParam:"style=form,explode=true,name=filter[in_stock]"`
	// Filter by the existence of an associated GPU
	FilterGpu *bool `queryParam:"style=form,explode=true,name=filter[gpu]"`
	// The ram size in Gigabytes to filter by, should be used with the following options:
	//                               [eql] to filter for values equal to the provided value.
	//                               [gte] to filter for values greater or equal to the provided value.
	//                               [lte] to filter by values lower or equal to the provided value.
	FilterRAM *int64 `queryParam:"style=form,explode=true,name=filter[ram]"`
	// The ephemeral_storage size in Gigabytes to filter by, should be used with the following options:
	//                               [eql] to filter for values equal to the provided value.
	//                               [gte] to filter for values greater or equal to the provided value.
	//                               [lte] to filter by values lower or equal to the provided value.
	FilterEphemeralStorage *int64 `queryParam:"style=form,explode=true,name=filter[ephemeral_storage]"`
}

func (o *GetContainersPlansRequest) GetFilterName() *string {
	if o == nil {
		return nil
	}
	return o.FilterName
}

func (o *GetContainersPlansRequest) GetFilterSlug() *string {
	if o == nil {
		return nil
	}
	return o.FilterSlug
}

func (o *GetContainersPlansRequest) GetFilterLocation() *string {
	if o == nil {
		return nil
	}
	return o.FilterLocation
}

func (o *GetContainersPlansRequest) GetFilterStockLevel() *QueryParamFilterStockLevel {
	if o == nil {
		return nil
	}
	return o.FilterStockLevel
}

func (o *GetContainersPlansRequest) GetFilterInStock() *bool {
	if o == nil {
		return nil
	}
	return o.FilterInStock
}

func (o *GetContainersPlansRequest) GetFilterGpu() *bool {
	if o == nil {
		return nil
	}
	return o.FilterGpu
}

func (o *GetContainersPlansRequest) GetFilterRAM() *int64 {
	if o == nil {
		return nil
	}
	return o.FilterRAM
}

func (o *GetContainersPlansRequest) GetFilterEphemeralStorage() *int64 {
	if o == nil {
		return nil
	}
	return o.FilterEphemeralStorage
}

// GetContainersPlansResponseBody - Success
type GetContainersPlansResponseBody struct {
	Data []components.ContainerPlanData `json:"data,omitempty"`
}

func (o *GetContainersPlansResponseBody) GetData() []components.ContainerPlanData {
	if o == nil {
		return nil
	}
	return o.Data
}

type GetContainersPlansResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetContainersPlansResponseBody
}

func (o *GetContainersPlansResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetContainersPlansResponse) GetObject() *GetContainersPlansResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
