// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetElasticIPRequest struct {
	// The Elastic IP ID
	ElasticIPID string `pathParam:"style=simple,explode=false,name=elastic_ip_id"`
}

func (g *GetElasticIPRequest) GetElasticIPID() string {
	if g == nil {
		return ""
	}
	return g.ElasticIPID
}

type GetElasticIPResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	ElasticIP *components.ElasticIP
}

func (g *GetElasticIPResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetElasticIPResponse) GetElasticIP() *components.ElasticIP {
	if g == nil {
		return nil
	}
	return g.ElasticIP
}
