// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetProjectSSHKeyRequest struct {
	// Project ID or Slug
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	SSHKeyID  string `pathParam:"style=simple,explode=false,name=ssh_key_id"`
}

func (g *GetProjectSSHKeyRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetProjectSSHKeyRequest) GetSSHKeyID() string {
	if g == nil {
		return ""
	}
	return g.SSHKeyID
}

// GetProjectSSHKeyResponseBody - Success
type GetProjectSSHKeyResponseBody struct {
	Data *components.SSHKeyData `json:"data,omitempty"`
}

func (g *GetProjectSSHKeyResponseBody) GetData() *components.SSHKeyData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetProjectSSHKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetProjectSSHKeyResponseBody
}

func (g *GetProjectSSHKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetProjectSSHKeyResponse) GetObject() *GetProjectSSHKeyResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
