// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetPrefixRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetPrefixRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetPrefixResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Prefix *components.Prefix
}

func (g *GetPrefixResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPrefixResponse) GetPrefix() *components.Prefix {
	if g == nil {
		return nil
	}
	return g.Prefix
}
