// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetProjectSSHKeysRequest struct {
	// Project ID or Slug
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	// The tags ids to filter by, separated by comma, e.g. `filter[tags]=tag_1,tag_2`will return ssh keys with `tag_1` AND `tag_2`
	FilterTags *string `queryParam:"style=form,explode=true,name=filter[tags]"`
	// Request aggregate stats in the response `meta`. Use `count` to get the total number of records, returned as `meta.stats.total.count`.
	StatsTotal *string `queryParam:"style=form,explode=true,name=stats[total]"`
	// Page number for pagination
	PageNumber *int64 `queryParam:"style=form,explode=true,name=page[number]"`
	// Number of items per page
	PageSize *int64 `queryParam:"style=form,explode=true,name=page[size]"`
}

func (g *GetProjectSSHKeysRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetProjectSSHKeysRequest) GetFilterTags() *string {
	if g == nil {
		return nil
	}
	return g.FilterTags
}

func (g *GetProjectSSHKeysRequest) GetStatsTotal() *string {
	if g == nil {
		return nil
	}
	return g.StatsTotal
}

func (g *GetProjectSSHKeysRequest) GetPageNumber() *int64 {
	if g == nil {
		return nil
	}
	return g.PageNumber
}

func (g *GetProjectSSHKeysRequest) GetPageSize() *int64 {
	if g == nil {
		return nil
	}
	return g.PageSize
}

type GetProjectSSHKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	SSHKeys *components.SSHKeys
}

func (g *GetProjectSSHKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetProjectSSHKeysResponse) GetSSHKeys() *components.SSHKeys {
	if g == nil {
		return nil
	}
	return g.SSHKeys
}
