// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetPlanRequest struct {
	PlanID string `pathParam:"style=simple,explode=false,name=plan_id"`
}

func (g *GetPlanRequest) GetPlanID() string {
	if g == nil {
		return ""
	}
	return g.PlanID
}

type GetPlanResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Plan *components.Plan
}

func (g *GetPlanResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPlanResponse) GetPlan() *components.Plan {
	if g == nil {
		return nil
	}
	return g.Plan
}
