// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetRegionsRequest struct {
	// Number of items to return per page
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=page[size]"`
	// Page number to return (starts at 1)
	PageNumber *int64 `default:"1" queryParam:"style=form,explode=true,name=page[number]"`
	// Request aggregate stats in the response `meta`. Use `count` to get the total number of records, returned as `meta.stats.total.count`.
	StatsTotal *string `queryParam:"style=form,explode=true,name=stats[total]"`
}

func (g GetRegionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRegionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetRegionsRequest) GetPageSize() *int64 {
	if g == nil {
		return nil
	}
	return g.PageSize
}

func (g *GetRegionsRequest) GetPageNumber() *int64 {
	if g == nil {
		return nil
	}
	return g.PageNumber
}

func (g *GetRegionsRequest) GetStatsTotal() *string {
	if g == nil {
		return nil
	}
	return g.StatsTotal
}

type GetRegionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Regions *components.Regions

	Next func() (*GetRegionsResponse, error)
}

func (g *GetRegionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetRegionsResponse) GetRegions() *components.Regions {
	if g == nil {
		return nil
	}
	return g.Regions
}
