// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetRegionRequest struct {
	// The region region_ID
	RegionID string `pathParam:"style=simple,explode=false,name=region_id"`
}

func (g *GetRegionRequest) GetRegionID() string {
	if g == nil {
		return ""
	}
	return g.RegionID
}

type GetRegionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Region *components.Region
}

func (g *GetRegionResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetRegionResponse) GetRegion() *components.Region {
	if g == nil {
		return nil
	}
	return g.Region
}
