// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetStorageVolumeRequest struct {
	// The volume storage ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetStorageVolumeRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetStorageVolumeResponseBody - Success
type GetStorageVolumeResponseBody struct {
	Data *components.VolumeData `json:"data,omitempty"`
}

func (g *GetStorageVolumeResponseBody) GetData() *components.VolumeData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetStorageVolumeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetStorageVolumeResponseBody
}

func (g *GetStorageVolumeResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStorageVolumeResponse) GetObject() *GetStorageVolumeResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
