// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
	"time"
)

type GetStorageBucketMetricsRequest struct {
	// The object storage bucket ID
	BucketID string `pathParam:"style=simple,explode=false,name=bucket_id"`
}

func (g *GetStorageBucketMetricsRequest) GetBucketID() string {
	if g == nil {
		return ""
	}
	return g.BucketID
}

type GetStorageBucketMetricsType string

const (
	GetStorageBucketMetricsTypeObjectStorageMetrics GetStorageBucketMetricsType = "object_storage_metrics"
)

func (e GetStorageBucketMetricsType) ToPointer() *GetStorageBucketMetricsType {
	return &e
}
func (e *GetStorageBucketMetricsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "object_storage_metrics":
		*e = GetStorageBucketMetricsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetStorageBucketMetricsType: %v", v)
	}
}

// Period - The current billing period
type Period struct {
	// Start of the billing period in ISO 8601 format
	Start *time.Time `json:"start,omitempty"`
	// End of the billing period in ISO 8601 format
	End *time.Time `json:"end,omitempty"`
}

func (p Period) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Period) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Period) GetStart() *time.Time {
	if p == nil {
		return nil
	}
	return p.Start
}

func (p *Period) GetEnd() *time.Time {
	if p == nil {
		return nil
	}
	return p.End
}

// Unit of measurement for storage
type Unit string

const (
	UnitGb Unit = "GB"
)

func (e Unit) ToPointer() *Unit {
	return &e
}
func (e *Unit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "GB":
		*e = Unit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Unit: %v", v)
	}
}

// Storage consumption metrics
type Storage struct {
	// Billed storage usage for the current period
	Consumed *int64 `json:"consumed,omitempty"`
	// Latest recorded storage usage (last datapoint)
	Current *int64 `json:"current,omitempty"`
	// Unit of measurement for storage
	Unit *Unit `json:"unit,omitempty"`
}

func (s *Storage) GetConsumed() *int64 {
	if s == nil {
		return nil
	}
	return s.Consumed
}

func (s *Storage) GetCurrent() *int64 {
	if s == nil {
		return nil
	}
	return s.Current
}

func (s *Storage) GetUnit() *Unit {
	if s == nil {
		return nil
	}
	return s.Unit
}

// EstimatedCost - Estimated cost for the current billing period
type EstimatedCost struct {
	// Estimated cost amount
	Amount *float64 `json:"amount,omitempty"`
	// Currency code (e.g., USD, BRL)
	Currency *string `json:"currency,omitempty"`
}

func (e *EstimatedCost) GetAmount() *float64 {
	if e == nil {
		return nil
	}
	return e.Amount
}

func (e *EstimatedCost) GetCurrency() *string {
	if e == nil {
		return nil
	}
	return e.Currency
}

type GetStorageBucketMetricsAttributes struct {
	// The current billing period
	Period *Period `json:"period,omitempty"`
	// Storage consumption metrics
	Storage *Storage `json:"storage,omitempty"`
	// Estimated cost for the current billing period
	EstimatedCost *EstimatedCost `json:"estimated_cost,omitempty"`
}

func (g *GetStorageBucketMetricsAttributes) GetPeriod() *Period {
	if g == nil {
		return nil
	}
	return g.Period
}

func (g *GetStorageBucketMetricsAttributes) GetStorage() *Storage {
	if g == nil {
		return nil
	}
	return g.Storage
}

func (g *GetStorageBucketMetricsAttributes) GetEstimatedCost() *EstimatedCost {
	if g == nil {
		return nil
	}
	return g.EstimatedCost
}

type GetStorageBucketMetricsData struct {
	// The bucket ID
	ID         *string                            `json:"id,omitempty"`
	Type       *GetStorageBucketMetricsType       `json:"type,omitempty"`
	Attributes *GetStorageBucketMetricsAttributes `json:"attributes,omitempty"`
}

func (g *GetStorageBucketMetricsData) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GetStorageBucketMetricsData) GetType() *GetStorageBucketMetricsType {
	if g == nil {
		return nil
	}
	return g.Type
}

func (g *GetStorageBucketMetricsData) GetAttributes() *GetStorageBucketMetricsAttributes {
	if g == nil {
		return nil
	}
	return g.Attributes
}

// GetStorageBucketMetricsResponseBody - Success
type GetStorageBucketMetricsResponseBody struct {
	Data *GetStorageBucketMetricsData `json:"data,omitempty"`
}

func (g *GetStorageBucketMetricsResponseBody) GetData() *GetStorageBucketMetricsData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetStorageBucketMetricsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetStorageBucketMetricsResponseBody
}

func (g *GetStorageBucketMetricsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStorageBucketMetricsResponse) GetObject() *GetStorageBucketMetricsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
