// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetStorageAccessKeysRequest struct {
	// Project ID or slug to list access keys for.
	Project string `queryParam:"style=form,explode=true,name=project"`
}

func (g *GetStorageAccessKeysRequest) GetProject() string {
	if g == nil {
		return ""
	}
	return g.Project
}

// Standard - Access key metadata. Exact fields depend on the storage provider.
type Standard struct {
	Name        *string `json:"name,omitempty"`
	Username    *string `json:"username,omitempty"`
	AccessKeyID *string `json:"access_key_id,omitempty"`
	Status      *string `json:"status,omitempty"`
	CreatedAt   *string `json:"created_at,omitempty"`
	Region      *string `json:"region,omitempty"`
}

func (s *Standard) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *Standard) GetUsername() *string {
	if s == nil {
		return nil
	}
	return s.Username
}

func (s *Standard) GetAccessKeyID() *string {
	if s == nil {
		return nil
	}
	return s.AccessKeyID
}

func (s *Standard) GetStatus() *string {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *Standard) GetCreatedAt() *string {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *Standard) GetRegion() *string {
	if s == nil {
		return nil
	}
	return s.Region
}

// HighPerformance - Access key metadata. Exact fields depend on the storage provider.
type HighPerformance struct {
	Name        *string `json:"name,omitempty"`
	Username    *string `json:"username,omitempty"`
	AccessKeyID *string `json:"access_key_id,omitempty"`
	Status      *string `json:"status,omitempty"`
	CreatedAt   *string `json:"created_at,omitempty"`
	Region      *string `json:"region,omitempty"`
}

func (h *HighPerformance) GetName() *string {
	if h == nil {
		return nil
	}
	return h.Name
}

func (h *HighPerformance) GetUsername() *string {
	if h == nil {
		return nil
	}
	return h.Username
}

func (h *HighPerformance) GetAccessKeyID() *string {
	if h == nil {
		return nil
	}
	return h.AccessKeyID
}

func (h *HighPerformance) GetStatus() *string {
	if h == nil {
		return nil
	}
	return h.Status
}

func (h *HighPerformance) GetCreatedAt() *string {
	if h == nil {
		return nil
	}
	return h.CreatedAt
}

func (h *HighPerformance) GetRegion() *string {
	if h == nil {
		return nil
	}
	return h.Region
}

// GetStorageAccessKeysData - Access keys grouped by storage class.
type GetStorageAccessKeysData struct {
	// Wasabi (standard) access keys.
	Standard []Standard `json:"standard,omitempty"`
	// VAST (high_performance) access keys, across all regions.
	HighPerformance []HighPerformance `json:"high_performance,omitempty"`
}

func (g *GetStorageAccessKeysData) GetStandard() []Standard {
	if g == nil {
		return nil
	}
	return g.Standard
}

func (g *GetStorageAccessKeysData) GetHighPerformance() []HighPerformance {
	if g == nil {
		return nil
	}
	return g.HighPerformance
}

// GetStorageAccessKeysResponseBody - Success
type GetStorageAccessKeysResponseBody struct {
	// Access keys grouped by storage class.
	Data *GetStorageAccessKeysData `json:"data,omitempty"`
}

func (g *GetStorageAccessKeysResponseBody) GetData() *GetStorageAccessKeysData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetStorageAccessKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetStorageAccessKeysResponseBody
}

func (g *GetStorageAccessKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStorageAccessKeysResponse) GetObject() *GetStorageAccessKeysResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
