// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetStoragePlansResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	StoragePlans *components.StoragePlans
}

func (g *GetStoragePlansResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStoragePlansResponse) GetStoragePlans() *components.StoragePlans {
	if g == nil {
		return nil
	}
	return g.StoragePlans
}
