// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetServersRequest struct {
	// The project ID or Slug to filter by
	FilterProject *string `queryParam:"style=form,explode=true,name=filter[project]"`
	// The region Slug to filter by
	FilterRegion *string `queryParam:"style=form,explode=true,name=filter[region]"`
	// The hostname of server to filter by
	FilterHostname *string `queryParam:"style=form,explode=true,name=filter[hostname]"`
	// The created at greater than equal date to filter by
	FilterCreatedAtGte *string `queryParam:"style=form,explode=true,name=filter[created_at_gte]"`
	// The created at less than equal date to filter by
	FilterCreatedAtLte *string `queryParam:"style=form,explode=true,name=filter[created_at_lte]"`
	// The label of server to filter by
	FilterLabel *string `queryParam:"style=form,explode=true,name=filter[label]"`
	// The status of server to filter by
	FilterStatus *string `queryParam:"style=form,explode=true,name=filter[status]"`
	// The platform/plan name of the server to filter by
	FilterPlan *string `queryParam:"style=form,explode=true,name=filter[plan]"`
	// Filter by the existence of an associated GPU
	FilterGpu *bool `queryParam:"style=form,explode=true,name=filter[gpu]"`
	// Filter servers with RAM size (in GB) equals the provided value.
	FilterRAMEql *int64 `queryParam:"style=form,explode=true,name=filter[ram][eql]"`
	// Filter servers with RAM size (in GB) greater than or equal the provided value.
	FilterRAMGte *int64 `queryParam:"style=form,explode=true,name=filter[ram][gte]"`
	// Filter servers with RAM size (in GB) less than or equal the provided value.
	FilterRAMLte *int64 `queryParam:"style=form,explode=true,name=filter[ram][lte]"`
	// The disk size in Gigabytes to filter by, should be used with the following options:
	//                               [eql] to filter for values equal to the provided value.
	//                               [gte] to filter for values greater than or equal to the provided value.
	//                               [lte] to filter by values lower than or equal to the provided value.
	FilterDisk *int64 `queryParam:"style=form,explode=true,name=filter[disk]"`
	// The tags IDs to filter by, separated by comma, e.g. `filter[tags]=tag_1,tag_2`will return servers with `tag_1` AND `tag_2`
	FilterTags *string `queryParam:"style=form,explode=true,name=filter[tags]"`
	// The `credentials` are provided as extra attributes that are lazy loaded. To request it, just set `extra_fields[servers]=credentials` in the query string.
	ExtraFieldsServers *string `queryParam:"style=form,explode=true,name=extra_fields[servers]"`
	// Number of items to return per page
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=page[size]"`
	// Page number to return (starts at 1)
	PageNumber *int64 `default:"1" queryParam:"style=form,explode=true,name=page[number]"`
}

func (g GetServersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetServersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetServersRequest) GetFilterProject() *string {
	if g == nil {
		return nil
	}
	return g.FilterProject
}

func (g *GetServersRequest) GetFilterRegion() *string {
	if g == nil {
		return nil
	}
	return g.FilterRegion
}

func (g *GetServersRequest) GetFilterHostname() *string {
	if g == nil {
		return nil
	}
	return g.FilterHostname
}

func (g *GetServersRequest) GetFilterCreatedAtGte() *string {
	if g == nil {
		return nil
	}
	return g.FilterCreatedAtGte
}

func (g *GetServersRequest) GetFilterCreatedAtLte() *string {
	if g == nil {
		return nil
	}
	return g.FilterCreatedAtLte
}

func (g *GetServersRequest) GetFilterLabel() *string {
	if g == nil {
		return nil
	}
	return g.FilterLabel
}

func (g *GetServersRequest) GetFilterStatus() *string {
	if g == nil {
		return nil
	}
	return g.FilterStatus
}

func (g *GetServersRequest) GetFilterPlan() *string {
	if g == nil {
		return nil
	}
	return g.FilterPlan
}

func (g *GetServersRequest) GetFilterGpu() *bool {
	if g == nil {
		return nil
	}
	return g.FilterGpu
}

func (g *GetServersRequest) GetFilterRAMEql() *int64 {
	if g == nil {
		return nil
	}
	return g.FilterRAMEql
}

func (g *GetServersRequest) GetFilterRAMGte() *int64 {
	if g == nil {
		return nil
	}
	return g.FilterRAMGte
}

func (g *GetServersRequest) GetFilterRAMLte() *int64 {
	if g == nil {
		return nil
	}
	return g.FilterRAMLte
}

func (g *GetServersRequest) GetFilterDisk() *int64 {
	if g == nil {
		return nil
	}
	return g.FilterDisk
}

func (g *GetServersRequest) GetFilterTags() *string {
	if g == nil {
		return nil
	}
	return g.FilterTags
}

func (g *GetServersRequest) GetExtraFieldsServers() *string {
	if g == nil {
		return nil
	}
	return g.ExtraFieldsServers
}

func (g *GetServersRequest) GetPageSize() *int64 {
	if g == nil {
		return nil
	}
	return g.PageSize
}

func (g *GetServersRequest) GetPageNumber() *int64 {
	if g == nil {
		return nil
	}
	return g.PageNumber
}

type GetServersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Servers *components.Servers

	Next func() (*GetServersResponse, error)
}

func (g *GetServersResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetServersResponse) GetServers() *components.Servers {
	if g == nil {
		return nil
	}
	return g.Servers
}
