// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetStorageBucketLifecycleRulesRequest struct {
	// The object storage bucket ID
	BucketID string `pathParam:"style=simple,explode=false,name=bucket_id"`
}

func (g *GetStorageBucketLifecycleRulesRequest) GetBucketID() string {
	if g == nil {
		return ""
	}
	return g.BucketID
}

type GetStorageBucketLifecycleRulesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	LifecycleRules *components.LifecycleRules
}

func (g *GetStorageBucketLifecycleRulesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStorageBucketLifecycleRulesResponse) GetLifecycleRules() *components.LifecycleRules {
	if g == nil {
		return nil
	}
	return g.LifecycleRules
}
