// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetStorageBucketRequest struct {
	// The object storage ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetStorageBucketRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetStorageBucketResponseBody - Success
type GetStorageBucketResponseBody struct {
	Data *components.ObjectStorageData `json:"data,omitempty"`
}

func (g *GetStorageBucketResponseBody) GetData() *components.ObjectStorageData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetStorageBucketResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetStorageBucketResponseBody
}

func (g *GetStorageBucketResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStorageBucketResponse) GetObject() *GetStorageBucketResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
