// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetStoragePlansRequest struct {
	// Filter by storage type (filesystem or object)
	FilterStorageType *string `queryParam:"style=form,explode=true,name=filter[storage_type]"`
	// Filter by storage class (standard or high_performance)
	FilterStorageClass *string `queryParam:"style=form,explode=true,name=filter[storage_class]"`
}

func (g *GetStoragePlansRequest) GetFilterStorageType() *string {
	if g == nil {
		return nil
	}
	return g.FilterStorageType
}

func (g *GetStoragePlansRequest) GetFilterStorageClass() *string {
	if g == nil {
		return nil
	}
	return g.FilterStorageClass
}

type GetStoragePlansResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	StoragePlans *components.StoragePlans
}

func (g *GetStoragePlansResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStoragePlansResponse) GetStoragePlans() *components.StoragePlans {
	if g == nil {
		return nil
	}
	return g.StoragePlans
}
