// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetStorageBucketsRequest struct {
	// The project ID or Slug to filter by
	FilterProject *string `queryParam:"style=form,explode=true,name=filter[project]"`
}

func (g *GetStorageBucketsRequest) GetFilterProject() *string {
	if g == nil {
		return nil
	}
	return g.FilterProject
}

type GetStorageBucketsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	ObjectStorages *components.ObjectStorages
}

func (g *GetStorageBucketsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStorageBucketsResponse) GetObjectStorages() *components.ObjectStorages {
	if g == nil {
		return nil
	}
	return g.ObjectStorages
}
