// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetStorageObjectRequest struct {
	// The object storage ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetStorageObjectRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetStorageObjectResponseBody - Success
type GetStorageObjectResponseBody struct {
	Data *components.ObjectStorageData `json:"data,omitempty"`
}

func (g *GetStorageObjectResponseBody) GetData() *components.ObjectStorageData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetStorageObjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetStorageObjectResponseBody
}

func (g *GetStorageObjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStorageObjectResponse) GetObject() *GetStorageObjectResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
