// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetStorageBucketAccessKeysRequest struct {
	// The object storage (bucket) ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetStorageBucketAccessKeysRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetStorageBucketAccessKeysData - Access key metadata. Exact fields depend on the storage provider.
type GetStorageBucketAccessKeysData struct {
	Name        *string `json:"name,omitempty"`
	Username    *string `json:"username,omitempty"`
	AccessKeyID *string `json:"access_key_id,omitempty"`
	Status      *string `json:"status,omitempty"`
	CreatedAt   *string `json:"created_at,omitempty"`
	Access      *string `json:"access,omitempty"`
}

func (g *GetStorageBucketAccessKeysData) GetName() *string {
	if g == nil {
		return nil
	}
	return g.Name
}

func (g *GetStorageBucketAccessKeysData) GetUsername() *string {
	if g == nil {
		return nil
	}
	return g.Username
}

func (g *GetStorageBucketAccessKeysData) GetAccessKeyID() *string {
	if g == nil {
		return nil
	}
	return g.AccessKeyID
}

func (g *GetStorageBucketAccessKeysData) GetStatus() *string {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetStorageBucketAccessKeysData) GetCreatedAt() *string {
	if g == nil {
		return nil
	}
	return g.CreatedAt
}

func (g *GetStorageBucketAccessKeysData) GetAccess() *string {
	if g == nil {
		return nil
	}
	return g.Access
}

// GetStorageBucketAccessKeysResponseBody - Success
type GetStorageBucketAccessKeysResponseBody struct {
	Data []GetStorageBucketAccessKeysData `json:"data,omitempty"`
}

func (g *GetStorageBucketAccessKeysResponseBody) GetData() []GetStorageBucketAccessKeysData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetStorageBucketAccessKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetStorageBucketAccessKeysResponseBody
}

func (g *GetStorageBucketAccessKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStorageBucketAccessKeysResponse) GetObject() *GetStorageBucketAccessKeysResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
