// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetSSHKeyRequest struct {
	SSHKeyID string `pathParam:"style=simple,explode=false,name=ssh_key_id"`
}

func (g *GetSSHKeyRequest) GetSSHKeyID() string {
	if g == nil {
		return ""
	}
	return g.SSHKeyID
}

// GetSSHKeyResponseBody - Success
type GetSSHKeyResponseBody struct {
	Data *components.SSHKeyData `json:"data,omitempty"`
}

func (g *GetSSHKeyResponseBody) GetData() *components.SSHKeyData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetSSHKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetSSHKeyResponseBody
}

func (g *GetSSHKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSSHKeyResponse) GetObject() *GetSSHKeyResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
