// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetStorageBucketLifecycleRuleRequest struct {
	// The object storage bucket ID
	BucketID string `pathParam:"style=simple,explode=false,name=bucket_id"`
	// The lifecycle rule ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetStorageBucketLifecycleRuleRequest) GetBucketID() string {
	if g == nil {
		return ""
	}
	return g.BucketID
}

func (g *GetStorageBucketLifecycleRuleRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetStorageBucketLifecycleRuleResponseBody - Success
type GetStorageBucketLifecycleRuleResponseBody struct {
	Data *components.LifecycleRuleData `json:"data,omitempty"`
}

func (g *GetStorageBucketLifecycleRuleResponseBody) GetData() *components.LifecycleRuleData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetStorageBucketLifecycleRuleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetStorageBucketLifecycleRuleResponseBody
}

func (g *GetStorageBucketLifecycleRuleResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStorageBucketLifecycleRuleResponse) GetObject() *GetStorageBucketLifecycleRuleResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
