// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetStorageVolumesRequest struct {
	// The project ID or Slug to filter by
	FilterProject *string `queryParam:"style=form,explode=true,name=filter[project]"`
}

func (g *GetStorageVolumesRequest) GetFilterProject() *string {
	if g == nil {
		return nil
	}
	return g.FilterProject
}

// GetStorageVolumesResponseBody - Success
type GetStorageVolumesResponseBody struct {
	Data []components.VolumeData `json:"data,omitempty"`
}

func (g *GetStorageVolumesResponseBody) GetData() []components.VolumeData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetStorageVolumesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetStorageVolumesResponseBody
}

func (g *GetStorageVolumesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStorageVolumesResponse) GetObject() *GetStorageVolumesResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
