// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetUsersDataRequest struct {
	// Project ID or slug
	FilterProject *string `queryParam:"style=form,explode=true,name=filter[project]"`
	// Filter by scope: `project` (has project), `team` (no project), or empty (all)
	FilterScope *string `queryParam:"style=form,explode=true,name=filter[scope]"`
	// Request aggregate stats in the response `meta`. Use `count` to get the total number of records, returned as `meta.stats.total.count`.
	StatsTotal *string `queryParam:"style=form,explode=true,name=stats[total]"`
	// The `decoded_content` is provided as an extra attribute that shows content in decoded form.
	ExtraFieldsUserData *string `default:"decoded_content" queryParam:"style=form,explode=true,name=extra_fields[user_data]"`
	// Number of items to return per page
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=page[size]"`
	// Page number to return (starts at 1)
	PageNumber *int64 `default:"1" queryParam:"style=form,explode=true,name=page[number]"`
}

func (g GetUsersDataRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUsersDataRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUsersDataRequest) GetFilterProject() *string {
	if g == nil {
		return nil
	}
	return g.FilterProject
}

func (g *GetUsersDataRequest) GetFilterScope() *string {
	if g == nil {
		return nil
	}
	return g.FilterScope
}

func (g *GetUsersDataRequest) GetStatsTotal() *string {
	if g == nil {
		return nil
	}
	return g.StatsTotal
}

func (g *GetUsersDataRequest) GetExtraFieldsUserData() *string {
	if g == nil {
		return nil
	}
	return g.ExtraFieldsUserData
}

func (g *GetUsersDataRequest) GetPageSize() *int64 {
	if g == nil {
		return nil
	}
	return g.PageSize
}

func (g *GetUsersDataRequest) GetPageNumber() *int64 {
	if g == nil {
		return nil
	}
	return g.PageNumber
}

type GetUsersDataResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	UserData *components.UserData

	Next func() (*GetUsersDataResponse, error)
}

func (g *GetUsersDataResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUsersDataResponse) GetUserData() *components.UserData {
	if g == nil {
		return nil
	}
	return g.UserData
}
