// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetUsersDataRequest struct {
	// Project ID or slug
	FilterProject *string `queryParam:"style=form,explode=true,name=filter[project]"`
	// The `decoded_content` is provided as an extra attribute that shows content in decoded form.
	ExtraFieldsUserData *string `default:"decoded_content" queryParam:"style=form,explode=true,name=extra_fields[user_data]"`
}

func (g GetUsersDataRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUsersDataRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUsersDataRequest) GetFilterProject() *string {
	if g == nil {
		return nil
	}
	return g.FilterProject
}

func (g *GetUsersDataRequest) GetExtraFieldsUserData() *string {
	if g == nil {
		return nil
	}
	return g.ExtraFieldsUserData
}

// GetUsersDataResponseBody - Success
type GetUsersDataResponseBody struct {
	Data []components.UserData `json:"data,omitempty"`
}

func (g *GetUsersDataResponseBody) GetData() []components.UserData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetUsersDataResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetUsersDataResponseBody
}

func (g *GetUsersDataResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUsersDataResponse) GetObject() *GetUsersDataResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
