// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetUserDataRequest struct {
	UserDataID string `pathParam:"style=simple,explode=false,name=user_data_id"`
	// The `decoded_content` is provided as an extra attribute that shows content in decoded form.
	ExtraFieldsUserData *string `default:"decoded_content" queryParam:"style=form,explode=true,name=extra_fields[user_data]"`
}

func (g GetUserDataRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUserDataRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"user_data_id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetUserDataRequest) GetUserDataID() string {
	if g == nil {
		return ""
	}
	return g.UserDataID
}

func (g *GetUserDataRequest) GetExtraFieldsUserData() *string {
	if g == nil {
		return nil
	}
	return g.ExtraFieldsUserData
}

type GetUserDataResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	UserData *components.UserData
}

func (g *GetUserDataResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUserDataResponse) GetUserData() *components.UserData {
	if g == nil {
		return nil
	}
	return g.UserData
}
