// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetVirtualNetworksRequest struct {
	// The location slug to filter by
	FilterLocation *string `queryParam:"style=form,explode=true,name=filter[location]"`
	// The project id or slug to filter by
	FilterProject *string `queryParam:"style=form,explode=true,name=filter[project]"`
	// The tags ids to filter by, separated by comma, e.g. `filter[tags]=tag_1,tag_2`will return ssh keys with `tag_1` AND `tag_2`
	FilterTags *string `queryParam:"style=form,explode=true,name=filter[tags]"`
	// Number of items to return per page
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=page[size]"`
	// Page number to return (starts at 1)
	PageNumber *int64 `default:"1" queryParam:"style=form,explode=true,name=page[number]"`
}

func (g GetVirtualNetworksRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetVirtualNetworksRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetVirtualNetworksRequest) GetFilterLocation() *string {
	if g == nil {
		return nil
	}
	return g.FilterLocation
}

func (g *GetVirtualNetworksRequest) GetFilterProject() *string {
	if g == nil {
		return nil
	}
	return g.FilterProject
}

func (g *GetVirtualNetworksRequest) GetFilterTags() *string {
	if g == nil {
		return nil
	}
	return g.FilterTags
}

func (g *GetVirtualNetworksRequest) GetPageSize() *int64 {
	if g == nil {
		return nil
	}
	return g.PageSize
}

func (g *GetVirtualNetworksRequest) GetPageNumber() *int64 {
	if g == nil {
		return nil
	}
	return g.PageNumber
}

type GetVirtualNetworksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	VirtualNetworks *components.VirtualNetworks

	Next func() (*GetVirtualNetworksResponse, error)
}

func (g *GetVirtualNetworksResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetVirtualNetworksResponse) GetVirtualNetworks() *components.VirtualNetworks {
	if g == nil {
		return nil
	}
	return g.VirtualNetworks
}
