// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type FilterLocation string

const (
	FilterLocationAsh  FilterLocation = "ASH"
	FilterLocationBue  FilterLocation = "BUE"
	FilterLocationChi  FilterLocation = "CHI"
	FilterLocationDal  FilterLocation = "DAL"
	FilterLocationFra  FilterLocation = "FRA"
	FilterLocationLax  FilterLocation = "LAX"
	FilterLocationLon  FilterLocation = "LON"
	FilterLocationMex  FilterLocation = "MEX"
	FilterLocationMex2 FilterLocation = "MEX2"
	FilterLocationMia  FilterLocation = "MIA"
	FilterLocationMia2 FilterLocation = "MIA2"
	FilterLocationNyc  FilterLocation = "NYC"
	FilterLocationSao  FilterLocation = "SAO"
	FilterLocationSao2 FilterLocation = "SAO2"
	FilterLocationSgp  FilterLocation = "SGP"
	FilterLocationSyd  FilterLocation = "SYD"
	FilterLocationTyo  FilterLocation = "TYO"
	FilterLocationTyo2 FilterLocation = "TYO2"
)

func (e FilterLocation) ToPointer() *FilterLocation {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FilterLocation) IsExact() bool {
	if e != nil {
		switch *e {
		case "ASH", "BUE", "CHI", "DAL", "FRA", "LAX", "LON", "MEX", "MEX2", "MIA", "MIA2", "NYC", "SAO", "SAO2", "SGP", "SYD", "TYO", "TYO2":
			return true
		}
	}
	return false
}

type GetVpnSessionsRequest struct {
	FilterLocation *FilterLocation `queryParam:"style=form,explode=true,name=filter[location]"`
}

func (g *GetVpnSessionsRequest) GetFilterLocation() *FilterLocation {
	if g == nil {
		return nil
	}
	return g.FilterLocation
}

type GetVpnSessionsMeta struct {
}

// GetVpnSessionsResponseBody - Success
type GetVpnSessionsResponseBody struct {
	Data []components.VpnSessionDataWithPassword `json:"data,omitempty"`
	Meta *GetVpnSessionsMeta                     `json:"meta,omitempty"`
}

func (g *GetVpnSessionsResponseBody) GetData() []components.VpnSessionDataWithPassword {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetVpnSessionsResponseBody) GetMeta() *GetVpnSessionsMeta {
	if g == nil {
		return nil
	}
	return g.Meta
}

type GetVpnSessionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetVpnSessionsResponseBody
}

func (g *GetVpnSessionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetVpnSessionsResponse) GetObject() *GetVpnSessionsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
