// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetVMPlansRequest struct {
	// Filter plans by GPU availability
	FilterGpu *bool `queryParam:"style=form,explode=true,name=filter[gpu]"`
}

func (g *GetVMPlansRequest) GetFilterGpu() *bool {
	if g == nil {
		return nil
	}
	return g.FilterGpu
}

type GetVMPlansResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	VirtualMachinePlans *components.VirtualMachinePlans
}

func (g *GetVMPlansResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetVMPlansResponse) GetVirtualMachinePlans() *components.VirtualMachinePlans {
	if g == nil {
		return nil
	}
	return g.VirtualMachinePlans
}
