// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetVirtualNetworksAssignmentsRequest struct {
	// The server ID to filter by
	FilterServer *string `queryParam:"style=form,explode=true,name=filter[server]"`
	// The vlan ID to filter by
	FilterVid *string `queryParam:"style=form,explode=true,name=filter[vid]"`
	// The virtual network ID to filter by
	FilterVirtualNetworkID *string `queryParam:"style=form,explode=true,name=filter[virtual_network_id]"`
}

func (o *GetVirtualNetworksAssignmentsRequest) GetFilterServer() *string {
	if o == nil {
		return nil
	}
	return o.FilterServer
}

func (o *GetVirtualNetworksAssignmentsRequest) GetFilterVid() *string {
	if o == nil {
		return nil
	}
	return o.FilterVid
}

func (o *GetVirtualNetworksAssignmentsRequest) GetFilterVirtualNetworkID() *string {
	if o == nil {
		return nil
	}
	return o.FilterVirtualNetworkID
}

type GetVirtualNetworksAssignmentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	VirtualNetworkAssignments *components.VirtualNetworkAssignments
}

func (o *GetVirtualNetworksAssignmentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetVirtualNetworksAssignmentsResponse) GetVirtualNetworkAssignments() *components.VirtualNetworkAssignments {
	if o == nil {
		return nil
	}
	return o.VirtualNetworkAssignments
}
