// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type GetVMPlansResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	VirtualMachinePlans *components.VirtualMachinePlans
}

func (g *GetVMPlansResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetVMPlansResponse) GetVirtualMachinePlans() *components.VirtualMachinePlans {
	if g == nil {
		return nil
	}
	return g.VirtualMachinePlans
}
