// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type IndexVirtualMachineRequest struct {
	// The project ID or Slug to filter by
	FilterProject *string `queryParam:"style=form,explode=true,name=filter[project]"`
}

func (i *IndexVirtualMachineRequest) GetFilterProject() *string {
	if i == nil {
		return nil
	}
	return i.FilterProject
}

type IndexVirtualMachineResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (i *IndexVirtualMachineResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}
