// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
	"github.com/latitudesh/latitudesh-go-sdk/types"
)

type IndexProjectStorageUsageRequest struct {
	// Project ID or Slug
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	// Restrict the result to a single storage. Accepts the storage/bucket ID
	StorageID *string `queryParam:"style=form,explode=true,name=storage_id"`
	// Defaults to yesterday
	StartDate *types.Date `queryParam:"style=form,explode=true,name=start_date"`
	// Defaults to today; clamped to today when a future date is given
	EndDate *types.Date `queryParam:"style=form,explode=true,name=end_date"`
}

func (i IndexProjectStorageUsageRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IndexProjectStorageUsageRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IndexProjectStorageUsageRequest) GetProjectID() string {
	if i == nil {
		return ""
	}
	return i.ProjectID
}

func (i *IndexProjectStorageUsageRequest) GetStorageID() *string {
	if i == nil {
		return nil
	}
	return i.StorageID
}

func (i *IndexProjectStorageUsageRequest) GetStartDate() *types.Date {
	if i == nil {
		return nil
	}
	return i.StartDate
}

func (i *IndexProjectStorageUsageRequest) GetEndDate() *types.Date {
	if i == nil {
		return nil
	}
	return i.EndDate
}

type IndexProjectStorageUsageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	StorageUsage *components.StorageUsage
}

func (i *IndexProjectStorageUsageResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IndexProjectStorageUsageResponse) GetStorageUsage() *components.StorageUsage {
	if i == nil {
		return nil
	}
	return i.StorageUsage
}
