// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type ListManagedDatabaseBackupsRequest struct {
	// Managed database ID
	ManagedDatabaseID string `pathParam:"style=simple,explode=false,name=managed_database_id"`
	// Filter backups by phase. Use 'completed' to return only finished backups.
	Phase *string `queryParam:"style=form,explode=true,name=phase"`
}

func (l *ListManagedDatabaseBackupsRequest) GetManagedDatabaseID() string {
	if l == nil {
		return ""
	}
	return l.ManagedDatabaseID
}

func (l *ListManagedDatabaseBackupsRequest) GetPhase() *string {
	if l == nil {
		return nil
	}
	return l.Phase
}

type ScheduledBackup struct {
	Name            *string `json:"name,omitempty"`
	Schedule        *string `json:"schedule,omitempty"`
	Suspended       *bool   `json:"suspended,omitempty"`
	Immediate       *bool   `json:"immediate,omitempty"`
	LastScheduledAt *string `json:"last_scheduled_at,omitempty"`
}

func (s *ScheduledBackup) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *ScheduledBackup) GetSchedule() *string {
	if s == nil {
		return nil
	}
	return s.Schedule
}

func (s *ScheduledBackup) GetSuspended() *bool {
	if s == nil {
		return nil
	}
	return s.Suspended
}

func (s *ScheduledBackup) GetImmediate() *bool {
	if s == nil {
		return nil
	}
	return s.Immediate
}

func (s *ScheduledBackup) GetLastScheduledAt() *string {
	if s == nil {
		return nil
	}
	return s.LastScheduledAt
}

type Backups struct {
	ID        string  `json:"id"`
	Phase     *string `json:"phase"`
	CreatedAt *string `json:"created_at"`
}

func (b *Backups) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *Backups) GetPhase() *string {
	if b == nil {
		return nil
	}
	return b.Phase
}

func (b *Backups) GetCreatedAt() *string {
	if b == nil {
		return nil
	}
	return b.CreatedAt
}

// ListManagedDatabaseBackupsResponseBody - OK
type ListManagedDatabaseBackupsResponseBody struct {
	ScheduledBackup *ScheduledBackup `json:"scheduled_backup"`
	Backups         []Backups        `json:"backups"`
}

func (l *ListManagedDatabaseBackupsResponseBody) GetScheduledBackup() *ScheduledBackup {
	if l == nil {
		return nil
	}
	return l.ScheduledBackup
}

func (l *ListManagedDatabaseBackupsResponseBody) GetBackups() []Backups {
	if l == nil {
		return []Backups{}
	}
	return l.Backups
}

type ListManagedDatabaseBackupsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *ListManagedDatabaseBackupsResponseBody
}

func (l *ListManagedDatabaseBackupsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListManagedDatabaseBackupsResponse) GetObject() *ListManagedDatabaseBackupsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
