// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type ListVirtualMachineBackupsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	VirtualMachineBackups *components.VirtualMachineBackups
}

func (l *ListVirtualMachineBackupsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListVirtualMachineBackupsResponse) GetVirtualMachineBackups() *components.VirtualMachineBackups {
	if l == nil {
		return nil
	}
	return l.VirtualMachineBackups
}
