// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type MountVolumeType string

const (
	MountVolumeTypeVolumes MountVolumeType = "volumes"
)

func (e MountVolumeType) ToPointer() *MountVolumeType {
	return &e
}
func (e *MountVolumeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "volumes":
		*e = MountVolumeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MountVolumeType: %v", v)
	}
}

type MountVolumeAttributes struct {
	// NVMe Qualified Name (NQN) of the client/server that will access the volume. Format: nqn.YYYY-MM.domain:identifier (e.g., "nqn.2024-01.com.example:server01"). This uniquely identifies the NVMe client and must be configured on the client server.
	Nqn string `json:"nqn"`
}

func (m *MountVolumeAttributes) GetNqn() string {
	if m == nil {
		return ""
	}
	return m.Nqn
}

type MountVolumeData struct {
	Type       MountVolumeType       `json:"type"`
	Attributes MountVolumeAttributes `json:"attributes"`
}

func (m *MountVolumeData) GetType() MountVolumeType {
	if m == nil {
		return MountVolumeType("")
	}
	return m.Type
}

func (m *MountVolumeData) GetAttributes() MountVolumeAttributes {
	if m == nil {
		return MountVolumeAttributes{}
	}
	return m.Attributes
}

type MountVolumeRequestBody struct {
	Data MountVolumeData `json:"data"`
}

func (m *MountVolumeRequestBody) GetData() MountVolumeData {
	if m == nil {
		return MountVolumeData{}
	}
	return m.Data
}

type MountVolumeRequest struct {
	// Volume ID
	ID          string                 `pathParam:"style=simple,explode=false,name=id"`
	RequestBody MountVolumeRequestBody `request:"mediaType=application/json"`
}

func (m *MountVolumeRequest) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *MountVolumeRequest) GetRequestBody() MountVolumeRequestBody {
	if m == nil {
		return MountVolumeRequestBody{}
	}
	return m.RequestBody
}

type MountVolumeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (m *MountVolumeResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}
