// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type PatchAPIKeyRequest struct {
	APIKeyID     string                  `pathParam:"style=simple,explode=false,name=api_key_id"`
	UpdateAPIKey components.UpdateAPIKey `request:"mediaType=application/vnd.api+json"`
}

func (p *PatchAPIKeyRequest) GetAPIKeyID() string {
	if p == nil {
		return ""
	}
	return p.APIKeyID
}

func (p *PatchAPIKeyRequest) GetUpdateAPIKey() components.UpdateAPIKey {
	if p == nil {
		return components.UpdateAPIKey{}
	}
	return p.UpdateAPIKey
}

// PatchAPIKeyResponseBody - Success
type PatchAPIKeyResponseBody struct {
	Data *components.APIKey `json:"data,omitempty"`
}

func (p *PatchAPIKeyResponseBody) GetData() *components.APIKey {
	if p == nil {
		return nil
	}
	return p.Data
}

type PatchAPIKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *PatchAPIKeyResponseBody
}

func (p *PatchAPIKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PatchAPIKeyResponse) GetObject() *PatchAPIKeyResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
