// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type PatchStorageBucketLifecycleRuleType string

const (
	PatchStorageBucketLifecycleRuleTypeLifecycleRules PatchStorageBucketLifecycleRuleType = "lifecycle_rules"
)

func (e PatchStorageBucketLifecycleRuleType) ToPointer() *PatchStorageBucketLifecycleRuleType {
	return &e
}
func (e *PatchStorageBucketLifecycleRuleType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "lifecycle_rules":
		*e = PatchStorageBucketLifecycleRuleType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PatchStorageBucketLifecycleRuleType: %v", v)
	}
}

type PatchStorageBucketLifecycleRuleAttributes struct {
	// Name of the lifecycle rule
	Name string `json:"name"`
	// Whether the rule is active
	Enabled *bool `json:"enabled,omitempty"`
	// Object key prefix to filter which objects the rule applies to
	Prefix *string `json:"prefix,omitempty"`
	// Number of days after object creation when the object expires
	ExpirationDays *int64 `json:"expiration_days,omitempty"`
	// Number of days after which noncurrent object versions expire
	NoncurrentDays *int64 `json:"noncurrent_days,omitempty"`
	// Number of days after initiation to abort incomplete multipart uploads
	AbortMpuDaysAfterInitiation *int64 `json:"abort_mpu_days_after_initiation,omitempty"`
}

func (p *PatchStorageBucketLifecycleRuleAttributes) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PatchStorageBucketLifecycleRuleAttributes) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

func (p *PatchStorageBucketLifecycleRuleAttributes) GetPrefix() *string {
	if p == nil {
		return nil
	}
	return p.Prefix
}

func (p *PatchStorageBucketLifecycleRuleAttributes) GetExpirationDays() *int64 {
	if p == nil {
		return nil
	}
	return p.ExpirationDays
}

func (p *PatchStorageBucketLifecycleRuleAttributes) GetNoncurrentDays() *int64 {
	if p == nil {
		return nil
	}
	return p.NoncurrentDays
}

func (p *PatchStorageBucketLifecycleRuleAttributes) GetAbortMpuDaysAfterInitiation() *int64 {
	if p == nil {
		return nil
	}
	return p.AbortMpuDaysAfterInitiation
}

type PatchStorageBucketLifecycleRuleData struct {
	Type       PatchStorageBucketLifecycleRuleType       `json:"type"`
	Attributes PatchStorageBucketLifecycleRuleAttributes `json:"attributes"`
}

func (p *PatchStorageBucketLifecycleRuleData) GetType() PatchStorageBucketLifecycleRuleType {
	if p == nil {
		return PatchStorageBucketLifecycleRuleType("")
	}
	return p.Type
}

func (p *PatchStorageBucketLifecycleRuleData) GetAttributes() PatchStorageBucketLifecycleRuleAttributes {
	if p == nil {
		return PatchStorageBucketLifecycleRuleAttributes{}
	}
	return p.Attributes
}

type PatchStorageBucketLifecycleRuleRequestBody struct {
	Data PatchStorageBucketLifecycleRuleData `json:"data"`
}

func (p *PatchStorageBucketLifecycleRuleRequestBody) GetData() PatchStorageBucketLifecycleRuleData {
	if p == nil {
		return PatchStorageBucketLifecycleRuleData{}
	}
	return p.Data
}

type PatchStorageBucketLifecycleRuleRequest struct {
	// The object storage bucket ID
	BucketID string `pathParam:"style=simple,explode=false,name=bucket_id"`
	// The lifecycle rule ID
	ID          string                                     `pathParam:"style=simple,explode=false,name=id"`
	RequestBody PatchStorageBucketLifecycleRuleRequestBody `request:"mediaType=application/vnd.api+json"`
}

func (p *PatchStorageBucketLifecycleRuleRequest) GetBucketID() string {
	if p == nil {
		return ""
	}
	return p.BucketID
}

func (p *PatchStorageBucketLifecycleRuleRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PatchStorageBucketLifecycleRuleRequest) GetRequestBody() PatchStorageBucketLifecycleRuleRequestBody {
	if p == nil {
		return PatchStorageBucketLifecycleRuleRequestBody{}
	}
	return p.RequestBody
}

// PatchStorageBucketLifecycleRuleResponseBody - Success
type PatchStorageBucketLifecycleRuleResponseBody struct {
	Data *components.LifecycleRuleData `json:"data,omitempty"`
}

func (p *PatchStorageBucketLifecycleRuleResponseBody) GetData() *components.LifecycleRuleData {
	if p == nil {
		return nil
	}
	return p.Data
}

type PatchStorageBucketLifecycleRuleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *PatchStorageBucketLifecycleRuleResponseBody
}

func (p *PatchStorageBucketLifecycleRuleResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PatchStorageBucketLifecycleRuleResponse) GetObject() *PatchStorageBucketLifecycleRuleResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
