// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type PostTeamMembersTeamMembersType string

const (
	PostTeamMembersTeamMembersTypeMemberships PostTeamMembersTeamMembersType = "memberships"
)

func (e PostTeamMembersTeamMembersType) ToPointer() *PostTeamMembersTeamMembersType {
	return &e
}
func (e *PostTeamMembersTeamMembersType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "memberships":
		*e = PostTeamMembersTeamMembersType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostTeamMembersTeamMembersType: %v", v)
	}
}

type PostTeamMembersRole string

const (
	PostTeamMembersRoleOwner         PostTeamMembersRole = "owner"
	PostTeamMembersRoleAdministrator PostTeamMembersRole = "administrator"
	PostTeamMembersRoleCollaborator  PostTeamMembersRole = "collaborator"
	PostTeamMembersRoleBilling       PostTeamMembersRole = "billing"
)

func (e PostTeamMembersRole) ToPointer() *PostTeamMembersRole {
	return &e
}
func (e *PostTeamMembersRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "owner":
		fallthrough
	case "administrator":
		fallthrough
	case "collaborator":
		fallthrough
	case "billing":
		*e = PostTeamMembersRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostTeamMembersRole: %v", v)
	}
}

type PostTeamMembersTeamMembersAttributes struct {
	FirstName *string             `json:"first_name,omitempty"`
	LastName  *string             `json:"last_name,omitempty"`
	Email     string              `json:"email"`
	Role      PostTeamMembersRole `json:"role"`
}

func (p *PostTeamMembersTeamMembersAttributes) GetFirstName() *string {
	if p == nil {
		return nil
	}
	return p.FirstName
}

func (p *PostTeamMembersTeamMembersAttributes) GetLastName() *string {
	if p == nil {
		return nil
	}
	return p.LastName
}

func (p *PostTeamMembersTeamMembersAttributes) GetEmail() string {
	if p == nil {
		return ""
	}
	return p.Email
}

func (p *PostTeamMembersTeamMembersAttributes) GetRole() PostTeamMembersRole {
	if p == nil {
		return PostTeamMembersRole("")
	}
	return p.Role
}

type PostTeamMembersTeamMembersData struct {
	Type       PostTeamMembersTeamMembersType        `json:"type"`
	Attributes *PostTeamMembersTeamMembersAttributes `json:"attributes,omitempty"`
}

func (p *PostTeamMembersTeamMembersData) GetType() PostTeamMembersTeamMembersType {
	if p == nil {
		return PostTeamMembersTeamMembersType("")
	}
	return p.Type
}

func (p *PostTeamMembersTeamMembersData) GetAttributes() *PostTeamMembersTeamMembersAttributes {
	if p == nil {
		return nil
	}
	return p.Attributes
}

type PostTeamMembersTeamMembersRequestBody struct {
	Data PostTeamMembersTeamMembersData `json:"data"`
}

func (p *PostTeamMembersTeamMembersRequestBody) GetData() PostTeamMembersTeamMembersData {
	if p == nil {
		return PostTeamMembersTeamMembersData{}
	}
	return p.Data
}

type PostTeamMembersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	Membership *components.Membership
}

func (p *PostTeamMembersResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostTeamMembersResponse) GetMembership() *components.Membership {
	if p == nil {
		return nil
	}
	return p.Membership
}
