// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type PostStorageBucketLifecycleRulesType string

const (
	PostStorageBucketLifecycleRulesTypeLifecycleRules PostStorageBucketLifecycleRulesType = "lifecycle_rules"
)

func (e PostStorageBucketLifecycleRulesType) ToPointer() *PostStorageBucketLifecycleRulesType {
	return &e
}
func (e *PostStorageBucketLifecycleRulesType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "lifecycle_rules":
		*e = PostStorageBucketLifecycleRulesType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostStorageBucketLifecycleRulesType: %v", v)
	}
}

type PostStorageBucketLifecycleRulesAttributes struct {
	// Name of the lifecycle rule
	Name string `json:"name"`
	// Whether the rule is active. Defaults to true if not specified.
	Enabled *bool `default:"true" json:"enabled"`
	// Object key prefix to filter which objects the rule applies to. If not specified, the rule applies to all objects in the bucket.
	Prefix *string `json:"prefix,omitempty"`
	// Number of days after object creation when the object expires and is automatically deleted
	ExpirationDays int64 `json:"expiration_days"`
	// Number of days after which noncurrent object versions expire (for versioned buckets)
	NoncurrentDays *int64 `json:"noncurrent_days,omitempty"`
	// Number of days after initiation to abort incomplete multipart uploads
	AbortMpuDaysAfterInitiation *int64 `json:"abort_mpu_days_after_initiation,omitempty"`
}

func (p PostStorageBucketLifecycleRulesAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostStorageBucketLifecycleRulesAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostStorageBucketLifecycleRulesAttributes) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PostStorageBucketLifecycleRulesAttributes) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

func (p *PostStorageBucketLifecycleRulesAttributes) GetPrefix() *string {
	if p == nil {
		return nil
	}
	return p.Prefix
}

func (p *PostStorageBucketLifecycleRulesAttributes) GetExpirationDays() int64 {
	if p == nil {
		return 0
	}
	return p.ExpirationDays
}

func (p *PostStorageBucketLifecycleRulesAttributes) GetNoncurrentDays() *int64 {
	if p == nil {
		return nil
	}
	return p.NoncurrentDays
}

func (p *PostStorageBucketLifecycleRulesAttributes) GetAbortMpuDaysAfterInitiation() *int64 {
	if p == nil {
		return nil
	}
	return p.AbortMpuDaysAfterInitiation
}

type PostStorageBucketLifecycleRulesData struct {
	Type       PostStorageBucketLifecycleRulesType       `json:"type"`
	Attributes PostStorageBucketLifecycleRulesAttributes `json:"attributes"`
}

func (p *PostStorageBucketLifecycleRulesData) GetType() PostStorageBucketLifecycleRulesType {
	if p == nil {
		return PostStorageBucketLifecycleRulesType("")
	}
	return p.Type
}

func (p *PostStorageBucketLifecycleRulesData) GetAttributes() PostStorageBucketLifecycleRulesAttributes {
	if p == nil {
		return PostStorageBucketLifecycleRulesAttributes{}
	}
	return p.Attributes
}

type PostStorageBucketLifecycleRulesRequestBody struct {
	Data PostStorageBucketLifecycleRulesData `json:"data"`
}

func (p *PostStorageBucketLifecycleRulesRequestBody) GetData() PostStorageBucketLifecycleRulesData {
	if p == nil {
		return PostStorageBucketLifecycleRulesData{}
	}
	return p.Data
}

type PostStorageBucketLifecycleRulesRequest struct {
	// The object storage bucket ID
	BucketID    string                                     `pathParam:"style=simple,explode=false,name=bucket_id"`
	RequestBody PostStorageBucketLifecycleRulesRequestBody `request:"mediaType=application/vnd.api+json"`
}

func (p *PostStorageBucketLifecycleRulesRequest) GetBucketID() string {
	if p == nil {
		return ""
	}
	return p.BucketID
}

func (p *PostStorageBucketLifecycleRulesRequest) GetRequestBody() PostStorageBucketLifecycleRulesRequestBody {
	if p == nil {
		return PostStorageBucketLifecycleRulesRequestBody{}
	}
	return p.RequestBody
}

// PostStorageBucketLifecycleRulesResponseBody - Created
type PostStorageBucketLifecycleRulesResponseBody struct {
	Data *components.LifecycleRuleData `json:"data,omitempty"`
}

func (p *PostStorageBucketLifecycleRulesResponseBody) GetData() *components.LifecycleRuleData {
	if p == nil {
		return nil
	}
	return p.Data
}

type PostStorageBucketLifecycleRulesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	Object *PostStorageBucketLifecycleRulesResponseBody
}

func (p *PostStorageBucketLifecycleRulesResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostStorageBucketLifecycleRulesResponse) GetObject() *PostStorageBucketLifecycleRulesResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
