// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type PostStorageObjectsType string

const (
	PostStorageObjectsTypeObjects PostStorageObjectsType = "objects"
)

func (e PostStorageObjectsType) ToPointer() *PostStorageObjectsType {
	return &e
}
func (e *PostStorageObjectsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "objects":
		*e = PostStorageObjectsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostStorageObjectsType: %v", v)
	}
}

type PostStorageObjectsAttributes struct {
	// Project ID or slug
	Project string `json:"project"`
	// Object storage name. Cannot contain special characters or spaces.
	Name string `json:"name"`
	// Site slug representing the region (e.g., DAL, SAO2)
	Region string `json:"region"`
	// Whether to create a scoped storage bucket. When true, the bucket is isolated to a specific customer context. Defaults to false.
	Scoped *bool `default:"false" json:"scoped"`
	// Customer identifier for scoped storage. Used when `scoped` is true to create customer-specific bucket isolation.
	Customer *string `json:"customer,omitempty"`
}

func (p PostStorageObjectsAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostStorageObjectsAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostStorageObjectsAttributes) GetProject() string {
	if p == nil {
		return ""
	}
	return p.Project
}

func (p *PostStorageObjectsAttributes) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PostStorageObjectsAttributes) GetRegion() string {
	if p == nil {
		return ""
	}
	return p.Region
}

func (p *PostStorageObjectsAttributes) GetScoped() *bool {
	if p == nil {
		return nil
	}
	return p.Scoped
}

func (p *PostStorageObjectsAttributes) GetCustomer() *string {
	if p == nil {
		return nil
	}
	return p.Customer
}

type PostStorageObjectsData struct {
	Type       PostStorageObjectsType       `json:"type"`
	Attributes PostStorageObjectsAttributes `json:"attributes"`
}

func (p *PostStorageObjectsData) GetType() PostStorageObjectsType {
	if p == nil {
		return PostStorageObjectsType("")
	}
	return p.Type
}

func (p *PostStorageObjectsData) GetAttributes() PostStorageObjectsAttributes {
	if p == nil {
		return PostStorageObjectsAttributes{}
	}
	return p.Attributes
}

type PostStorageObjectsRequestBody struct {
	Data PostStorageObjectsData `json:"data"`
}

func (p *PostStorageObjectsRequestBody) GetData() PostStorageObjectsData {
	if p == nil {
		return PostStorageObjectsData{}
	}
	return p.Data
}

// PostStorageObjectsResponseBody - Created
type PostStorageObjectsResponseBody struct {
	Data *components.ObjectStorageData `json:"data,omitempty"`
}

func (p *PostStorageObjectsResponseBody) GetData() *components.ObjectStorageData {
	if p == nil {
		return nil
	}
	return p.Data
}

type PostStorageObjectsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	Object *PostStorageObjectsResponseBody
}

func (p *PostStorageObjectsResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostStorageObjectsResponse) GetObject() *PostStorageObjectsResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
