// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type PostStorageVolumesMapType string

const (
	PostStorageVolumesMapTypeVolumes PostStorageVolumesMapType = "volumes"
)

func (e PostStorageVolumesMapType) ToPointer() *PostStorageVolumesMapType {
	return &e
}
func (e *PostStorageVolumesMapType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "volumes":
		*e = PostStorageVolumesMapType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostStorageVolumesMapType: %v", v)
	}
}

type PostStorageVolumesMapAttributes struct {
	// ID of the server that will access the volume. The server must belong to the same project and location as the volume, and must be eligible for bonding.
	ServerID string `json:"server_id"`
}

func (p *PostStorageVolumesMapAttributes) GetServerID() string {
	if p == nil {
		return ""
	}
	return p.ServerID
}

type PostStorageVolumesMapData struct {
	Type       PostStorageVolumesMapType       `json:"type"`
	Attributes PostStorageVolumesMapAttributes `json:"attributes"`
}

func (p *PostStorageVolumesMapData) GetType() PostStorageVolumesMapType {
	if p == nil {
		return PostStorageVolumesMapType("")
	}
	return p.Type
}

func (p *PostStorageVolumesMapData) GetAttributes() PostStorageVolumesMapAttributes {
	if p == nil {
		return PostStorageVolumesMapAttributes{}
	}
	return p.Attributes
}

type PostStorageVolumesMapRequestBody struct {
	Data PostStorageVolumesMapData `json:"data"`
}

func (p *PostStorageVolumesMapRequestBody) GetData() PostStorageVolumesMapData {
	if p == nil {
		return PostStorageVolumesMapData{}
	}
	return p.Data
}

type PostStorageVolumesMapRequest struct {
	// Volume ID
	ID          string                           `pathParam:"style=simple,explode=false,name=id"`
	RequestBody PostStorageVolumesMapRequestBody `request:"mediaType=application/json"`
}

func (p *PostStorageVolumesMapRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PostStorageVolumesMapRequest) GetRequestBody() PostStorageVolumesMapRequestBody {
	if p == nil {
		return PostStorageVolumesMapRequestBody{}
	}
	return p.RequestBody
}

type PostStorageVolumesMapMeta struct {
}

// PostStorageVolumesMapResponseBody - Success
type PostStorageVolumesMapResponseBody struct {
	Data *components.VolumeData     `json:"data,omitempty"`
	Meta *PostStorageVolumesMapMeta `json:"meta,omitempty"`
}

func (p *PostStorageVolumesMapResponseBody) GetData() *components.VolumeData {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PostStorageVolumesMapResponseBody) GetMeta() *PostStorageVolumesMapMeta {
	if p == nil {
		return nil
	}
	return p.Meta
}

type PostStorageVolumesMapResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *PostStorageVolumesMapResponseBody
}

func (p *PostStorageVolumesMapResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostStorageVolumesMapResponse) GetObject() *PostStorageVolumesMapResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
