// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

// PostAPIKeyResponseBody - Created
type PostAPIKeyResponseBody struct {
	Data *components.APIKey `json:"data,omitempty"`
}

func (p *PostAPIKeyResponseBody) GetData() *components.APIKey {
	if p == nil {
		return nil
	}
	return p.Data
}

type PostAPIKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	Object *PostAPIKeyResponseBody
}

func (p *PostAPIKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostAPIKeyResponse) GetObject() *PostAPIKeyResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
