// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type PostStorageBucketsType string

const (
	PostStorageBucketsTypeObjects PostStorageBucketsType = "objects"
)

func (e PostStorageBucketsType) ToPointer() *PostStorageBucketsType {
	return &e
}
func (e *PostStorageBucketsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "objects":
		*e = PostStorageBucketsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostStorageBucketsType: %v", v)
	}
}

// StorageClass - Storage class tier for the bucket.
type StorageClass string

const (
	StorageClassStandard        StorageClass = "standard"
	StorageClassHighPerformance StorageClass = "high_performance"
)

func (e StorageClass) ToPointer() *StorageClass {
	return &e
}
func (e *StorageClass) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "standard":
		fallthrough
	case "high_performance":
		*e = StorageClass(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StorageClass: %v", v)
	}
}

// RetentionMode - Object lock retention mode. Requires `locking` to be true when not `NONE`.
type RetentionMode string

const (
	RetentionModeNone       RetentionMode = "NONE"
	RetentionModeCompliance RetentionMode = "COMPLIANCE"
	RetentionModeGovernance RetentionMode = "GOVERNANCE"
)

func (e RetentionMode) ToPointer() *RetentionMode {
	return &e
}
func (e *RetentionMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NONE":
		fallthrough
	case "COMPLIANCE":
		fallthrough
	case "GOVERNANCE":
		*e = RetentionMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RetentionMode: %v", v)
	}
}

type PostStorageBucketsAttributes struct {
	// Project ID or slug
	Project string `json:"project"`
	// Object storage name. Cannot contain special characters or spaces.
	Name string `json:"name"`
	// Site slug representing the region (e.g., DAL, SAO2)
	Region string `json:"region"`
	// Whether to create a scoped storage bucket. When true, the bucket is isolated to a specific customer context. Defaults to false.
	Scoped *bool `default:"false" json:"scoped"`
	// Customer identifier for scoped storage. Used when `scoped` is true to create customer-specific bucket isolation.
	Customer *string `json:"customer,omitempty"`
	// Storage class tier for the bucket.
	StorageClass *StorageClass `default:"standard" json:"storage_class"`
	// Enable bucket versioning.
	Versioning *bool `default:"false" json:"versioning"`
	// Enable object lock on the bucket.
	Locking *bool `default:"false" json:"locking"`
	// Object lock retention mode. Requires `locking` to be true when not `NONE`.
	RetentionMode *RetentionMode `default:"NONE" json:"retention_mode"`
	// Default retention period in days when object lock is enabled.
	RetentionPeriod *int64 `json:"retention_period,omitempty"`
}

func (p PostStorageBucketsAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostStorageBucketsAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostStorageBucketsAttributes) GetProject() string {
	if p == nil {
		return ""
	}
	return p.Project
}

func (p *PostStorageBucketsAttributes) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PostStorageBucketsAttributes) GetRegion() string {
	if p == nil {
		return ""
	}
	return p.Region
}

func (p *PostStorageBucketsAttributes) GetScoped() *bool {
	if p == nil {
		return nil
	}
	return p.Scoped
}

func (p *PostStorageBucketsAttributes) GetCustomer() *string {
	if p == nil {
		return nil
	}
	return p.Customer
}

func (p *PostStorageBucketsAttributes) GetStorageClass() *StorageClass {
	if p == nil {
		return nil
	}
	return p.StorageClass
}

func (p *PostStorageBucketsAttributes) GetVersioning() *bool {
	if p == nil {
		return nil
	}
	return p.Versioning
}

func (p *PostStorageBucketsAttributes) GetLocking() *bool {
	if p == nil {
		return nil
	}
	return p.Locking
}

func (p *PostStorageBucketsAttributes) GetRetentionMode() *RetentionMode {
	if p == nil {
		return nil
	}
	return p.RetentionMode
}

func (p *PostStorageBucketsAttributes) GetRetentionPeriod() *int64 {
	if p == nil {
		return nil
	}
	return p.RetentionPeriod
}

type PostStorageBucketsData struct {
	Type       PostStorageBucketsType       `json:"type"`
	Attributes PostStorageBucketsAttributes `json:"attributes"`
}

func (p *PostStorageBucketsData) GetType() PostStorageBucketsType {
	if p == nil {
		return PostStorageBucketsType("")
	}
	return p.Type
}

func (p *PostStorageBucketsData) GetAttributes() PostStorageBucketsAttributes {
	if p == nil {
		return PostStorageBucketsAttributes{}
	}
	return p.Attributes
}

type PostStorageBucketsRequestBody struct {
	Data PostStorageBucketsData `json:"data"`
}

func (p *PostStorageBucketsRequestBody) GetData() PostStorageBucketsData {
	if p == nil {
		return PostStorageBucketsData{}
	}
	return p.Data
}

// PostStorageBucketsResponseBody - Created
type PostStorageBucketsResponseBody struct {
	Data *components.ObjectStorageData `json:"data,omitempty"`
}

func (p *PostStorageBucketsResponseBody) GetData() *components.ObjectStorageData {
	if p == nil {
		return nil
	}
	return p.Data
}

type PostStorageBucketsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	Object *PostStorageBucketsResponseBody
}

func (p *PostStorageBucketsResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostStorageBucketsResponse) GetObject() *PostStorageBucketsResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
