// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type PutStorageBucketLifecycleRuleType string

const (
	PutStorageBucketLifecycleRuleTypeLifecycleRules PutStorageBucketLifecycleRuleType = "lifecycle_rules"
)

func (e PutStorageBucketLifecycleRuleType) ToPointer() *PutStorageBucketLifecycleRuleType {
	return &e
}
func (e *PutStorageBucketLifecycleRuleType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "lifecycle_rules":
		*e = PutStorageBucketLifecycleRuleType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PutStorageBucketLifecycleRuleType: %v", v)
	}
}

type PutStorageBucketLifecycleRuleAttributes struct {
	// Name of the lifecycle rule
	Name string `json:"name"`
	// Whether the rule is active
	Enabled *bool `json:"enabled,omitempty"`
	// Object key prefix to filter which objects the rule applies to
	Prefix *string `json:"prefix,omitempty"`
	// Number of days after object creation when the object expires
	ExpirationDays *int64 `json:"expiration_days,omitempty"`
	// Number of days after which noncurrent object versions expire
	NoncurrentDays *int64 `json:"noncurrent_days,omitempty"`
	// Number of days after initiation to abort incomplete multipart uploads
	AbortMpuDaysAfterInitiation *int64 `json:"abort_mpu_days_after_initiation,omitempty"`
}

func (p *PutStorageBucketLifecycleRuleAttributes) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PutStorageBucketLifecycleRuleAttributes) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

func (p *PutStorageBucketLifecycleRuleAttributes) GetPrefix() *string {
	if p == nil {
		return nil
	}
	return p.Prefix
}

func (p *PutStorageBucketLifecycleRuleAttributes) GetExpirationDays() *int64 {
	if p == nil {
		return nil
	}
	return p.ExpirationDays
}

func (p *PutStorageBucketLifecycleRuleAttributes) GetNoncurrentDays() *int64 {
	if p == nil {
		return nil
	}
	return p.NoncurrentDays
}

func (p *PutStorageBucketLifecycleRuleAttributes) GetAbortMpuDaysAfterInitiation() *int64 {
	if p == nil {
		return nil
	}
	return p.AbortMpuDaysAfterInitiation
}

type PutStorageBucketLifecycleRuleData struct {
	Type       PutStorageBucketLifecycleRuleType       `json:"type"`
	Attributes PutStorageBucketLifecycleRuleAttributes `json:"attributes"`
}

func (p *PutStorageBucketLifecycleRuleData) GetType() PutStorageBucketLifecycleRuleType {
	if p == nil {
		return PutStorageBucketLifecycleRuleType("")
	}
	return p.Type
}

func (p *PutStorageBucketLifecycleRuleData) GetAttributes() PutStorageBucketLifecycleRuleAttributes {
	if p == nil {
		return PutStorageBucketLifecycleRuleAttributes{}
	}
	return p.Attributes
}

type PutStorageBucketLifecycleRuleRequestBody struct {
	Data PutStorageBucketLifecycleRuleData `json:"data"`
}

func (p *PutStorageBucketLifecycleRuleRequestBody) GetData() PutStorageBucketLifecycleRuleData {
	if p == nil {
		return PutStorageBucketLifecycleRuleData{}
	}
	return p.Data
}

type PutStorageBucketLifecycleRuleRequest struct {
	// The object storage bucket ID
	BucketID string `pathParam:"style=simple,explode=false,name=bucket_id"`
	// The lifecycle rule ID
	ID          string                                   `pathParam:"style=simple,explode=false,name=id"`
	RequestBody PutStorageBucketLifecycleRuleRequestBody `request:"mediaType=application/vnd.api+json"`
}

func (p *PutStorageBucketLifecycleRuleRequest) GetBucketID() string {
	if p == nil {
		return ""
	}
	return p.BucketID
}

func (p *PutStorageBucketLifecycleRuleRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PutStorageBucketLifecycleRuleRequest) GetRequestBody() PutStorageBucketLifecycleRuleRequestBody {
	if p == nil {
		return PutStorageBucketLifecycleRuleRequestBody{}
	}
	return p.RequestBody
}

// PutStorageBucketLifecycleRuleResponseBody - Success
type PutStorageBucketLifecycleRuleResponseBody struct {
	Data *components.LifecycleRuleData `json:"data,omitempty"`
}

func (p *PutStorageBucketLifecycleRuleResponseBody) GetData() *components.LifecycleRuleData {
	if p == nil {
		return nil
	}
	return p.Data
}

type PutStorageBucketLifecycleRuleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *PutStorageBucketLifecycleRuleResponseBody
}

func (p *PutStorageBucketLifecycleRuleResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PutStorageBucketLifecycleRuleResponse) GetObject() *PutStorageBucketLifecycleRuleResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
