// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type RetrieveVolumeRequest struct {
	// The volume ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (r *RetrieveVolumeRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

// RetrieveVolumeResponseBody - Success
type RetrieveVolumeResponseBody struct {
	Data *components.VolumeData `json:"data,omitempty"`
}

func (r *RetrieveVolumeResponseBody) GetData() *components.VolumeData {
	if r == nil {
		return nil
	}
	return r.Data
}

type RetrieveVolumeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *RetrieveVolumeResponseBody
}

func (r *RetrieveVolumeResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RetrieveVolumeResponse) GetObject() *RetrieveVolumeResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
