// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type RotateAPIKeyRequest struct {
	APIKeyID     string                  `pathParam:"style=simple,explode=false,name=api_key_id"`
	UpdateAPIKey components.UpdateAPIKey `request:"mediaType=application/json"`
}

func (r *RotateAPIKeyRequest) GetAPIKeyID() string {
	if r == nil {
		return ""
	}
	return r.APIKeyID
}

func (r *RotateAPIKeyRequest) GetUpdateAPIKey() components.UpdateAPIKey {
	if r == nil {
		return components.UpdateAPIKey{}
	}
	return r.UpdateAPIKey
}

// RotateAPIKeyResponseBody - Success
type RotateAPIKeyResponseBody struct {
	Data *components.APIKey `json:"data,omitempty"`
}

func (r *RotateAPIKeyResponseBody) GetData() *components.APIKey {
	if r == nil {
		return nil
	}
	return r.Data
}

type RotateAPIKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *RotateAPIKeyResponseBody
}

func (r *RotateAPIKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RotateAPIKeyResponse) GetObject() *RotateAPIKeyResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
