// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type Metric string

const (
	MetricCPU     Metric = "cpu"
	MetricMemory  Metric = "memory"
	MetricNetwork Metric = "network"
	MetricDisk    Metric = "disk"
)

func (e Metric) ToPointer() *Metric {
	return &e
}
func (e *Metric) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cpu":
		fallthrough
	case "memory":
		fallthrough
	case "network":
		fallthrough
	case "disk":
		*e = Metric(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Metric: %v", v)
	}
}

type Range string

const (
	RangeFivem       Range = "5m"
	RangeFifteenm    Range = "15m"
	RangeOneh        Range = "1h"
	RangeTwentyFourh Range = "24h"
)

func (e Range) ToPointer() *Range {
	return &e
}
func (e *Range) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "5m":
		fallthrough
	case "15m":
		fallthrough
	case "1h":
		fallthrough
	case "24h":
		*e = Range(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Range: %v", v)
	}
}

type ShowVirtualMachineMetricsRequest struct {
	VirtualMachineID string `pathParam:"style=simple,explode=false,name=virtual_machine_id"`
	Metric           Metric `queryParam:"style=form,explode=true,name=metric"`
	Range            *Range `queryParam:"style=form,explode=true,name=range"`
	ForceRefresh     *bool  `queryParam:"style=form,explode=true,name=force_refresh"`
}

func (s *ShowVirtualMachineMetricsRequest) GetVirtualMachineID() string {
	if s == nil {
		return ""
	}
	return s.VirtualMachineID
}

func (s *ShowVirtualMachineMetricsRequest) GetMetric() Metric {
	if s == nil {
		return Metric("")
	}
	return s.Metric
}

func (s *ShowVirtualMachineMetricsRequest) GetRange() *Range {
	if s == nil {
		return nil
	}
	return s.Range
}

func (s *ShowVirtualMachineMetricsRequest) GetForceRefresh() *bool {
	if s == nil {
		return nil
	}
	return s.ForceRefresh
}

type ShowVirtualMachineMetricsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	VirtualMachineMetrics *components.VirtualMachineMetrics
}

func (s *ShowVirtualMachineMetricsResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *ShowVirtualMachineMetricsResponse) GetVirtualMachineMetrics() *components.VirtualMachineMetrics {
	if s == nil {
		return nil
	}
	return s.VirtualMachineMetrics
}
