// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type UpdateVirtualMachineRequest struct {
	VirtualMachineID            string                                 `pathParam:"style=simple,explode=false,name=virtual_machine_id"`
	VirtualMachineUpdatePayload components.VirtualMachineUpdatePayload `request:"mediaType=application/json"`
}

func (u *UpdateVirtualMachineRequest) GetVirtualMachineID() string {
	if u == nil {
		return ""
	}
	return u.VirtualMachineID
}

func (u *UpdateVirtualMachineRequest) GetVirtualMachineUpdatePayload() components.VirtualMachineUpdatePayload {
	if u == nil {
		return components.VirtualMachineUpdatePayload{}
	}
	return u.VirtualMachineUpdatePayload
}

type UpdateVirtualMachineResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	VirtualMachine *components.VirtualMachine
}

func (u *UpdateVirtualMachineResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateVirtualMachineResponse) GetVirtualMachine() *components.VirtualMachine {
	if u == nil {
		return nil
	}
	return u.VirtualMachine
}
