// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type UpdateFilesystemFilesystemStorageType string

const (
	UpdateFilesystemFilesystemStorageTypeFilesystems UpdateFilesystemFilesystemStorageType = "filesystems"
)

func (e UpdateFilesystemFilesystemStorageType) ToPointer() *UpdateFilesystemFilesystemStorageType {
	return &e
}
func (e *UpdateFilesystemFilesystemStorageType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "filesystems":
		*e = UpdateFilesystemFilesystemStorageType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateFilesystemFilesystemStorageType: %v", v)
	}
}

type UpdateFilesystemFilesystemStorageAttributes struct {
	// Size in GB (not required, default is 1500)
	SizeInGb int64 `json:"size_in_gb"`
}

func (u *UpdateFilesystemFilesystemStorageAttributes) GetSizeInGb() int64 {
	if u == nil {
		return 0
	}
	return u.SizeInGb
}

type UpdateFilesystemFilesystemStorageData struct {
	// Filesystem ID
	ID         *string                                     `json:"id,omitempty"`
	Type       UpdateFilesystemFilesystemStorageType       `json:"type"`
	Attributes UpdateFilesystemFilesystemStorageAttributes `json:"attributes"`
}

func (u *UpdateFilesystemFilesystemStorageData) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UpdateFilesystemFilesystemStorageData) GetType() UpdateFilesystemFilesystemStorageType {
	if u == nil {
		return UpdateFilesystemFilesystemStorageType("")
	}
	return u.Type
}

func (u *UpdateFilesystemFilesystemStorageData) GetAttributes() UpdateFilesystemFilesystemStorageAttributes {
	if u == nil {
		return UpdateFilesystemFilesystemStorageAttributes{}
	}
	return u.Attributes
}

type UpdateFilesystemFilesystemStorageRequestBody struct {
	Data UpdateFilesystemFilesystemStorageData `json:"data"`
}

func (u *UpdateFilesystemFilesystemStorageRequestBody) GetData() UpdateFilesystemFilesystemStorageData {
	if u == nil {
		return UpdateFilesystemFilesystemStorageData{}
	}
	return u.Data
}

type UpdateFilesystemRequest struct {
	FilesystemID string                                       `pathParam:"style=simple,explode=false,name=filesystem_id"`
	RequestBody  UpdateFilesystemFilesystemStorageRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateFilesystemRequest) GetFilesystemID() string {
	if u == nil {
		return ""
	}
	return u.FilesystemID
}

func (u *UpdateFilesystemRequest) GetRequestBody() UpdateFilesystemFilesystemStorageRequestBody {
	if u == nil {
		return UpdateFilesystemFilesystemStorageRequestBody{}
	}
	return u.RequestBody
}

// UpdateFilesystemResponseBody - Success
type UpdateFilesystemResponseBody struct {
	Data *components.FilesystemData `json:"data,omitempty"`
}

func (u *UpdateFilesystemResponseBody) GetData() *components.FilesystemData {
	if u == nil {
		return nil
	}
	return u.Data
}

type UpdateFilesystemResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *UpdateFilesystemResponseBody
}

func (u *UpdateFilesystemResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateFilesystemResponse) GetObject() *UpdateFilesystemResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
