// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/latitudesh/latitudesh-go-sdk/models/components"
)

type UpdatePublicNetworkIPRequest struct {
	ID                    string                           `pathParam:"style=simple,explode=false,name=id"`
	UpdatePublicNetworkIP components.UpdatePublicNetworkIP `request:"mediaType=application/json"`
}

func (u *UpdatePublicNetworkIPRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePublicNetworkIPRequest) GetUpdatePublicNetworkIP() components.UpdatePublicNetworkIP {
	if u == nil {
		return components.UpdatePublicNetworkIP{}
	}
	return u.UpdatePublicNetworkIP
}

type UpdatePublicNetworkIPResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PublicNetwork *components.PublicNetwork
}

func (u *UpdatePublicNetworkIPResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdatePublicNetworkIPResponse) GetPublicNetwork() *components.PublicNetwork {
	if u == nil {
		return nil
	}
	return u.PublicNetwork
}
