// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BgpSession struct {
	Data *BgpSessionData `json:"data,omitempty"`
}

func (b *BgpSession) GetData() *BgpSessionData {
	if b == nil {
		return nil
	}
	return b.Data
}
