// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"time"
)

type BillingUsageMeta struct {
}

// BillingUsageProject - The project in which the returned usage belongs to
type BillingUsageProject struct {
	ID   *string `json:"id,omitempty"`
	Slug *string `json:"slug,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (b *BillingUsageProject) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *BillingUsageProject) GetSlug() *string {
	if b == nil {
		return nil
	}
	return b.Slug
}

func (b *BillingUsageProject) GetName() *string {
	if b == nil {
		return nil
	}
	return b.Name
}

// Period - The period from the returned billing cycle
type Period struct {
	Start *time.Time `json:"start,omitempty"`
	End   *time.Time `json:"end,omitempty"`
}

func (p Period) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Period) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Period) GetStart() *time.Time {
	if p == nil {
		return nil
	}
	return p.Start
}

func (p *Period) GetEnd() *time.Time {
	if p == nil {
		return nil
	}
	return p.End
}

// BillingUsageType - Type of discount (percentage or fixed amount)
type BillingUsageType string

const (
	BillingUsageTypePercent BillingUsageType = "percent"
	BillingUsageTypeAmount  BillingUsageType = "amount"
)

func (e BillingUsageType) ToPointer() *BillingUsageType {
	return &e
}
func (e *BillingUsageType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "percent":
		fallthrough
	case "amount":
		*e = BillingUsageType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingUsageType: %v", v)
	}
}

type Discounts struct {
	// Description of the discount
	Description string `json:"description"`
	// Type of discount (percentage or fixed amount)
	Type BillingUsageType `json:"type"`
	// Value of the discount (percentage or amount)
	Value float32 `json:"value"`
}

func (d *Discounts) GetDescription() string {
	if d == nil {
		return ""
	}
	return d.Description
}

func (d *Discounts) GetType() BillingUsageType {
	if d == nil {
		return BillingUsageType("")
	}
	return d.Type
}

func (d *Discounts) GetValue() float32 {
	if d == nil {
		return 0.0
	}
	return d.Value
}

type BillingUsageUnit string

const (
	BillingUsageUnitQuantity BillingUsageUnit = "quantity"
	BillingUsageUnitHour     BillingUsageUnit = "hour"
	BillingUsageUnitMinute   BillingUsageUnit = "minute"
	BillingUsageUnitGb       BillingUsageUnit = "GB"
)

func (e BillingUsageUnit) ToPointer() *BillingUsageUnit {
	return &e
}
func (e *BillingUsageUnit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "quantity":
		fallthrough
	case "hour":
		fallthrough
	case "minute":
		fallthrough
	case "GB":
		*e = BillingUsageUnit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingUsageUnit: %v", v)
	}
}

type UsageType string

const (
	UsageTypeLicensed UsageType = "licensed"
	UsageTypeMetered  UsageType = "metered"
)

func (e UsageType) ToPointer() *UsageType {
	return &e
}
func (e *UsageType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "licensed":
		fallthrough
	case "metered":
		*e = UsageType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UsageType: %v", v)
	}
}

type BillingUsageServers struct {
	ID       *string  `json:"id,omitempty"`
	Hostname *string  `json:"hostname,omitempty"`
	Plan     *string  `json:"plan,omitempty"`
	Tags     []string `json:"tags,omitempty"`
}

func (b *BillingUsageServers) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *BillingUsageServers) GetHostname() *string {
	if b == nil {
		return nil
	}
	return b.Hostname
}

func (b *BillingUsageServers) GetPlan() *string {
	if b == nil {
		return nil
	}
	return b.Plan
}

func (b *BillingUsageServers) GetTags() []string {
	if b == nil {
		return nil
	}
	return b.Tags
}

type Bucket struct {
	ID       *string `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Location *string `json:"location,omitempty"`
}

func (b *Bucket) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *Bucket) GetName() *string {
	if b == nil {
		return nil
	}
	return b.Name
}

func (b *Bucket) GetLocation() *string {
	if b == nil {
		return nil
	}
	return b.Location
}

type Metadata struct {
	Servers []BillingUsageServers `json:"servers,omitempty"`
	Bucket  *Bucket               `json:"bucket,omitempty"`
	// For products priced per divided unit (e.g. $0.01 per 1000 API calls), the divisor applied to the quantity before pricing. Omitted for products that are not priced by divided units.
	BillingUnitDivisor *int64 `json:"billing_unit_divisor,omitempty"`
}

func (m *Metadata) GetServers() []BillingUsageServers {
	if m == nil {
		return nil
	}
	return m.Servers
}

func (m *Metadata) GetBucket() *Bucket {
	if m == nil {
		return nil
	}
	return m.Bucket
}

func (m *Metadata) GetBillingUnitDivisor() *int64 {
	if m == nil {
		return nil
	}
	return m.BillingUnitDivisor
}

type Products struct {
	ID                    *string           `json:"id,omitempty"`
	Resource              *string           `json:"resource,omitempty"`
	Name                  *string           `json:"name,omitempty"`
	Proration             *bool             `json:"proration,omitempty"`
	Discounts             []Discounts       `json:"discounts,omitempty"`
	Discountable          *bool             `json:"discountable,omitempty"`
	Description           *string           `json:"description,omitempty"`
	AmountWithoutDiscount *int64            `json:"amount_without_discount,omitempty"`
	Start                 *time.Time        `json:"start,omitempty"`
	End                   *time.Time        `json:"end,omitempty"`
	Unit                  *BillingUsageUnit `json:"unit,omitempty"`
	// The unit amount of the product in cents
	UnitAmount *float64 `json:"unit_amount,omitempty"`
	// The unit price of the product in cents
	UnitPrice *float64   `json:"unit_price,omitempty"`
	UsageType *UsageType `json:"usage_type,omitempty"`
	Quantity  *float64   `json:"quantity,omitempty"`
	// The total usage amount of the product in cents
	Amount *float64 `json:"amount,omitempty"`
	// The total usage price of the product in cents
	Price    *float64  `json:"price,omitempty"`
	Metadata *Metadata `json:"metadata,omitempty"`
}

func (p Products) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Products) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Products) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *Products) GetResource() *string {
	if p == nil {
		return nil
	}
	return p.Resource
}

func (p *Products) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *Products) GetProration() *bool {
	if p == nil {
		return nil
	}
	return p.Proration
}

func (p *Products) GetDiscounts() []Discounts {
	if p == nil {
		return nil
	}
	return p.Discounts
}

func (p *Products) GetDiscountable() *bool {
	if p == nil {
		return nil
	}
	return p.Discountable
}

func (p *Products) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *Products) GetAmountWithoutDiscount() *int64 {
	if p == nil {
		return nil
	}
	return p.AmountWithoutDiscount
}

func (p *Products) GetStart() *time.Time {
	if p == nil {
		return nil
	}
	return p.Start
}

func (p *Products) GetEnd() *time.Time {
	if p == nil {
		return nil
	}
	return p.End
}

func (p *Products) GetUnit() *BillingUsageUnit {
	if p == nil {
		return nil
	}
	return p.Unit
}

func (p *Products) GetUnitAmount() *float64 {
	if p == nil {
		return nil
	}
	return p.UnitAmount
}

func (p *Products) GetUnitPrice() *float64 {
	if p == nil {
		return nil
	}
	return p.UnitPrice
}

func (p *Products) GetUsageType() *UsageType {
	if p == nil {
		return nil
	}
	return p.UsageType
}

func (p *Products) GetQuantity() *float64 {
	if p == nil {
		return nil
	}
	return p.Quantity
}

func (p *Products) GetAmount() *float64 {
	if p == nil {
		return nil
	}
	return p.Amount
}

func (p *Products) GetPrice() *float64 {
	if p == nil {
		return nil
	}
	return p.Price
}

func (p *Products) GetMetadata() *Metadata {
	if p == nil {
		return nil
	}
	return p.Metadata
}

type BillingUsageAttributes struct {
	// The project in which the returned usage belongs to
	Project *BillingUsageProject `json:"project,omitempty"`
	// The period from the returned billing cycle
	Period *Period `json:"period,omitempty"`
	// The available credit balance in cents
	AvailableCreditBalance *int64 `json:"available_credit_balance,omitempty"`
	// The total usage amount in cents
	Amount *float64 `json:"amount,omitempty"`
	// The total usage price in cents
	Price *float64 `json:"price,omitempty"`
	// The threshold which we use to charge your usage, in cents
	Threshold *float64   `json:"threshold,omitempty"`
	Products  []Products `json:"products,omitempty"`
}

func (b *BillingUsageAttributes) GetProject() *BillingUsageProject {
	if b == nil {
		return nil
	}
	return b.Project
}

func (b *BillingUsageAttributes) GetPeriod() *Period {
	if b == nil {
		return nil
	}
	return b.Period
}

func (b *BillingUsageAttributes) GetAvailableCreditBalance() *int64 {
	if b == nil {
		return nil
	}
	return b.AvailableCreditBalance
}

func (b *BillingUsageAttributes) GetAmount() *float64 {
	if b == nil {
		return nil
	}
	return b.Amount
}

func (b *BillingUsageAttributes) GetPrice() *float64 {
	if b == nil {
		return nil
	}
	return b.Price
}

func (b *BillingUsageAttributes) GetThreshold() *float64 {
	if b == nil {
		return nil
	}
	return b.Threshold
}

func (b *BillingUsageAttributes) GetProducts() []Products {
	if b == nil {
		return nil
	}
	return b.Products
}

type BillingUsageData struct {
	ID         *string                 `json:"id,omitempty"`
	Type       *string                 `json:"type,omitempty"`
	Attributes *BillingUsageAttributes `json:"attributes,omitempty"`
}

func (b *BillingUsageData) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *BillingUsageData) GetType() *string {
	if b == nil {
		return nil
	}
	return b.Type
}

func (b *BillingUsageData) GetAttributes() *BillingUsageAttributes {
	if b == nil {
		return nil
	}
	return b.Attributes
}

type BillingUsage struct {
	Meta *BillingUsageMeta `json:"meta,omitempty"`
	Data *BillingUsageData `json:"data,omitempty"`
}

func (b *BillingUsage) GetMeta() *BillingUsageMeta {
	if b == nil {
		return nil
	}
	return b.Meta
}

func (b *BillingUsage) GetData() *BillingUsageData {
	if b == nil {
		return nil
	}
	return b.Data
}
