// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CreatePrefixType string

const (
	CreatePrefixTypePrefixes CreatePrefixType = "prefixes"
)

func (e CreatePrefixType) ToPointer() *CreatePrefixType {
	return &e
}
func (e *CreatePrefixType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "prefixes":
		*e = CreatePrefixType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreatePrefixType: %v", v)
	}
}

// CreatePrefixSize - IPv4 prefix length. Determines how many servers the network can host.
type CreatePrefixSize int64

const (
	CreatePrefixSizeTwentySix   CreatePrefixSize = 26
	CreatePrefixSizeTwentySeven CreatePrefixSize = 27
	CreatePrefixSizeTwentyEight CreatePrefixSize = 28
)

func (e CreatePrefixSize) ToPointer() *CreatePrefixSize {
	return &e
}
func (e *CreatePrefixSize) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 26:
		fallthrough
	case 27:
		fallthrough
	case 28:
		*e = CreatePrefixSize(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreatePrefixSize: %v", v)
	}
}

type CreatePrefixAttributes struct {
	// The project to create the network in
	ProjectID string `json:"project_id"`
	// The site slug the network is bound to
	Site string `json:"site"`
	// IPv4 prefix length. Determines how many servers the network can host.
	Size CreatePrefixSize `json:"size"`
}

func (c *CreatePrefixAttributes) GetProjectID() string {
	if c == nil {
		return ""
	}
	return c.ProjectID
}

func (c *CreatePrefixAttributes) GetSite() string {
	if c == nil {
		return ""
	}
	return c.Site
}

func (c *CreatePrefixAttributes) GetSize() CreatePrefixSize {
	if c == nil {
		return CreatePrefixSize(0)
	}
	return c.Size
}

type CreatePrefixData struct {
	Type       CreatePrefixType        `json:"type"`
	Attributes *CreatePrefixAttributes `json:"attributes,omitempty"`
}

func (c *CreatePrefixData) GetType() CreatePrefixType {
	if c == nil {
		return CreatePrefixType("")
	}
	return c.Type
}

func (c *CreatePrefixData) GetAttributes() *CreatePrefixAttributes {
	if c == nil {
		return nil
	}
	return c.Attributes
}

type CreatePrefix struct {
	Data CreatePrefixData `json:"data"`
}

func (c *CreatePrefix) GetData() CreatePrefixData {
	if c == nil {
		return CreatePrefixData{}
	}
	return c.Data
}
