// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CustomTagDataType string

const (
	CustomTagDataTypeTags CustomTagDataType = "tags"
)

func (e CustomTagDataType) ToPointer() *CustomTagDataType {
	return &e
}
func (e *CustomTagDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tags":
		*e = CustomTagDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomTagDataType: %v", v)
	}
}

type CustomTagDataAttributes struct {
	// Name of the Tag
	Name *string `json:"name,omitempty"`
	// Slug of the Tag
	Slug *string `json:"slug,omitempty"`
	// Description of the Tag
	Description *string `json:"description,omitempty"`
	// Color of the Tag
	Color *string      `json:"color,omitempty"`
	Team  *TeamInclude `json:"team,omitempty"`
}

func (c *CustomTagDataAttributes) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomTagDataAttributes) GetSlug() *string {
	if c == nil {
		return nil
	}
	return c.Slug
}

func (c *CustomTagDataAttributes) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CustomTagDataAttributes) GetColor() *string {
	if c == nil {
		return nil
	}
	return c.Color
}

func (c *CustomTagDataAttributes) GetTeam() *TeamInclude {
	if c == nil {
		return nil
	}
	return c.Team
}

type CustomTagData struct {
	ID         *string                  `json:"id,omitempty"`
	Type       *CustomTagDataType       `json:"type,omitempty"`
	Attributes *CustomTagDataAttributes `json:"attributes,omitempty"`
}

func (c *CustomTagData) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *CustomTagData) GetType() *CustomTagDataType {
	if c == nil {
		return nil
	}
	return c.Type
}

func (c *CustomTagData) GetAttributes() *CustomTagDataAttributes {
	if c == nil {
		return nil
	}
	return c.Attributes
}
