// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"time"
)

type ElasticIPDataType string

const (
	ElasticIPDataTypeElasticIps ElasticIPDataType = "elastic_ips"
)

func (e ElasticIPDataType) ToPointer() *ElasticIPDataType {
	return &e
}
func (e *ElasticIPDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "elastic_ips":
		*e = ElasticIPDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ElasticIPDataType: %v", v)
	}
}

// Family - The IP address family
type Family string

const (
	FamilyIPv4 Family = "IPv4"
)

func (e Family) ToPointer() *Family {
	return &e
}
func (e *Family) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "IPv4":
		*e = Family(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Family: %v", v)
	}
}

// Mode - The routing mode for this Elastic IP
type Mode string

const (
	ModeRouted Mode = "routed"
)

func (e Mode) ToPointer() *Mode {
	return &e
}
func (e *Mode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "routed":
		*e = Mode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Mode: %v", v)
	}
}

// Status - The current status of the Elastic IP
type Status string

const (
	StatusConfiguring Status = "configuring"
	StatusActive      Status = "active"
	StatusMoving      Status = "moving"
	StatusReleasing   Status = "releasing"
	StatusError       Status = "error"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "configuring":
		fallthrough
	case "active":
		fallthrough
	case "moving":
		fallthrough
	case "releasing":
		fallthrough
	case "error":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

// ElasticIPDataServer - The server this Elastic IP is assigned to
type ElasticIPDataServer struct {
	ID              *string `json:"id,omitempty"`
	Hostname        *string `json:"hostname,omitempty"`
	PrimaryIpv4     *string `json:"primary_ipv4,omitempty"`
	OperatingSystem *string `json:"operating_system,omitempty"`
}

func (e *ElasticIPDataServer) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *ElasticIPDataServer) GetHostname() *string {
	if e == nil {
		return nil
	}
	return e.Hostname
}

func (e *ElasticIPDataServer) GetPrimaryIpv4() *string {
	if e == nil {
		return nil
	}
	return e.PrimaryIpv4
}

func (e *ElasticIPDataServer) GetOperatingSystem() *string {
	if e == nil {
		return nil
	}
	return e.OperatingSystem
}

// ElasticIPDataProject - The project this Elastic IP belongs to
type ElasticIPDataProject struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Slug *string `json:"slug,omitempty"`
}

func (e *ElasticIPDataProject) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *ElasticIPDataProject) GetName() *string {
	if e == nil {
		return nil
	}
	return e.Name
}

func (e *ElasticIPDataProject) GetSlug() *string {
	if e == nil {
		return nil
	}
	return e.Slug
}

// Location - The site/location within the region
type Location struct {
	// The site ID
	ID *string `json:"id,omitempty"`
	// The site name
	Name *string `json:"name,omitempty"`
	// The site slug
	Slug *string `json:"slug,omitempty"`
}

func (l *Location) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *Location) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *Location) GetSlug() *string {
	if l == nil {
		return nil
	}
	return l.Slug
}

// ElasticIPDataRegion - The region where this Elastic IP is located
type ElasticIPDataRegion struct {
	// The region ID
	ID *string `json:"id,omitempty"`
	// The region name
	Name *string `json:"name,omitempty"`
	// The site/location within the region
	Location *Location `json:"location,omitempty"`
}

func (e *ElasticIPDataRegion) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *ElasticIPDataRegion) GetName() *string {
	if e == nil {
		return nil
	}
	return e.Name
}

func (e *ElasticIPDataRegion) GetLocation() *Location {
	if e == nil {
		return nil
	}
	return e.Location
}

type ElasticIPDataAttributes struct {
	// The IP address
	Address *string `json:"address,omitempty"`
	// The IP address family
	Family *Family `json:"family,omitempty"`
	// The prefix length (e.g., 32 for a single IP)
	PrefixLength *int64 `json:"prefix_length,omitempty"`
	// The routing mode for this Elastic IP
	Mode *Mode `json:"mode,omitempty"`
	// The current status of the Elastic IP
	Status *Status `json:"status,omitempty"`
	// The timestamp when the Elastic IP was created
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The server this Elastic IP is assigned to
	Server *ElasticIPDataServer `json:"server,omitempty"`
	// The project this Elastic IP belongs to
	Project *ElasticIPDataProject `json:"project,omitempty"`
	// The region where this Elastic IP is located
	Region *ElasticIPDataRegion `json:"region,omitempty"`
}

func (e ElasticIPDataAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ElasticIPDataAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ElasticIPDataAttributes) GetAddress() *string {
	if e == nil {
		return nil
	}
	return e.Address
}

func (e *ElasticIPDataAttributes) GetFamily() *Family {
	if e == nil {
		return nil
	}
	return e.Family
}

func (e *ElasticIPDataAttributes) GetPrefixLength() *int64 {
	if e == nil {
		return nil
	}
	return e.PrefixLength
}

func (e *ElasticIPDataAttributes) GetMode() *Mode {
	if e == nil {
		return nil
	}
	return e.Mode
}

func (e *ElasticIPDataAttributes) GetStatus() *Status {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *ElasticIPDataAttributes) GetCreatedAt() *time.Time {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}

func (e *ElasticIPDataAttributes) GetServer() *ElasticIPDataServer {
	if e == nil {
		return nil
	}
	return e.Server
}

func (e *ElasticIPDataAttributes) GetProject() *ElasticIPDataProject {
	if e == nil {
		return nil
	}
	return e.Project
}

func (e *ElasticIPDataAttributes) GetRegion() *ElasticIPDataRegion {
	if e == nil {
		return nil
	}
	return e.Region
}

type ElasticIPData struct {
	// The Elastic IP ID. May be null during initial provisioning.
	ID         *string                  `json:"id,omitempty"`
	Type       *ElasticIPDataType       `json:"type,omitempty"`
	Attributes *ElasticIPDataAttributes `json:"attributes,omitempty"`
}

func (e *ElasticIPData) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *ElasticIPData) GetType() *ElasticIPDataType {
	if e == nil {
		return nil
	}
	return e.Type
}

func (e *ElasticIPData) GetAttributes() *ElasticIPDataAttributes {
	if e == nil {
		return nil
	}
	return e.Attributes
}
