// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Meta struct {
}

type Events struct {
	Data []EventData `json:"data,omitempty"`
	Meta *Meta       `json:"meta,omitempty"`
}

func (e *Events) GetData() []EventData {
	if e == nil {
		return nil
	}
	return e.Data
}

func (e *Events) GetMeta() *Meta {
	if e == nil {
		return nil
	}
	return e.Meta
}
