// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"time"
)

type FilesystemDataType string

const (
	FilesystemDataTypeFilesystems FilesystemDataType = "filesystems"
)

func (e FilesystemDataType) ToPointer() *FilesystemDataType {
	return &e
}
func (e *FilesystemDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "filesystems":
		*e = FilesystemDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FilesystemDataType: %v", v)
	}
}

type StorageClass string

const (
	StorageClassStandard        StorageClass = "standard"
	StorageClassHighPerformance StorageClass = "high_performance"
)

func (e StorageClass) ToPointer() *StorageClass {
	return &e
}
func (e *StorageClass) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "standard":
		fallthrough
	case "high_performance":
		*e = StorageClass(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StorageClass: %v", v)
	}
}

type FilesystemDataAttributes struct {
	Name         *string         `json:"name,omitempty"`
	SizeInGb     *int64          `json:"size_in_gb,omitempty"`
	StorageClass *StorageClass   `json:"storage_class,omitempty"`
	CreatedAt    *time.Time      `json:"created_at,omitempty"`
	Project      *ProjectInclude `json:"project,omitempty"`
	Team         *TeamInclude    `json:"team,omitempty"`
}

func (f FilesystemDataAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilesystemDataAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FilesystemDataAttributes) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}

func (f *FilesystemDataAttributes) GetSizeInGb() *int64 {
	if f == nil {
		return nil
	}
	return f.SizeInGb
}

func (f *FilesystemDataAttributes) GetStorageClass() *StorageClass {
	if f == nil {
		return nil
	}
	return f.StorageClass
}

func (f *FilesystemDataAttributes) GetCreatedAt() *time.Time {
	if f == nil {
		return nil
	}
	return f.CreatedAt
}

func (f *FilesystemDataAttributes) GetProject() *ProjectInclude {
	if f == nil {
		return nil
	}
	return f.Project
}

func (f *FilesystemDataAttributes) GetTeam() *TeamInclude {
	if f == nil {
		return nil
	}
	return f.Team
}

type FilesystemData struct {
	ID         *string                   `json:"id,omitempty"`
	Type       *FilesystemDataType       `json:"type,omitempty"`
	Attributes *FilesystemDataAttributes `json:"attributes,omitempty"`
}

func (f *FilesystemData) GetID() *string {
	if f == nil {
		return nil
	}
	return f.ID
}

func (f *FilesystemData) GetType() *FilesystemDataType {
	if f == nil {
		return nil
	}
	return f.Type
}

func (f *FilesystemData) GetAttributes() *FilesystemDataAttributes {
	if f == nil {
		return nil
	}
	return f.Attributes
}
