// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type IpmiSessionType string

const (
	IpmiSessionTypeIpmiSessions IpmiSessionType = "ipmi_sessions"
)

func (e IpmiSessionType) ToPointer() *IpmiSessionType {
	return &e
}
func (e *IpmiSessionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ipmi_sessions":
		*e = IpmiSessionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IpmiSessionType: %v", v)
	}
}

type IpmiSessionAttributes struct {
	// The IPMI IP Address
	IpmiAddress *string `json:"ipmi_address,omitempty"`
	// The IPMI username
	IpmiUsername *string `json:"ipmi_username,omitempty"`
	// The IPMI password
	IpmiPassword *string `json:"ipmi_password,omitempty"`
}

func (i *IpmiSessionAttributes) GetIpmiAddress() *string {
	if i == nil {
		return nil
	}
	return i.IpmiAddress
}

func (i *IpmiSessionAttributes) GetIpmiUsername() *string {
	if i == nil {
		return nil
	}
	return i.IpmiUsername
}

func (i *IpmiSessionAttributes) GetIpmiPassword() *string {
	if i == nil {
		return nil
	}
	return i.IpmiPassword
}

type IpmiSessionData struct {
	ID         *string                `json:"id,omitempty"`
	Type       *IpmiSessionType       `json:"type,omitempty"`
	Attributes *IpmiSessionAttributes `json:"attributes,omitempty"`
}

func (i *IpmiSessionData) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IpmiSessionData) GetType() *IpmiSessionType {
	if i == nil {
		return nil
	}
	return i.Type
}

func (i *IpmiSessionData) GetAttributes() *IpmiSessionAttributes {
	if i == nil {
		return nil
	}
	return i.Attributes
}

type IpmiSession struct {
	Data *IpmiSessionData `json:"data,omitempty"`
}

func (i *IpmiSession) GetData() *IpmiSessionData {
	if i == nil {
		return nil
	}
	return i.Data
}
