// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type KubernetesAvailableVersionsData struct {
	// The full Kubernetes version string (e.g., v1.35.3+rke2r1)
	Version *string `json:"version,omitempty"`
	// The minor version number (e.g., 1.35)
	Minor *string `json:"minor,omitempty"`
}

func (k *KubernetesAvailableVersionsData) GetVersion() *string {
	if k == nil {
		return nil
	}
	return k.Version
}

func (k *KubernetesAvailableVersionsData) GetMinor() *string {
	if k == nil {
		return nil
	}
	return k.Minor
}

// KubernetesAvailableVersions - Response schema for available Kubernetes versions
type KubernetesAvailableVersions struct {
	Data []KubernetesAvailableVersionsData `json:"data,omitempty"`
}

func (k *KubernetesAvailableVersions) GetData() []KubernetesAvailableVersionsData {
	if k == nil {
		return nil
	}
	return k.Data
}
