// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// KubernetesClusters - Response schema for listing clusters (uses summary representation)
type KubernetesClusters struct {
	Data []KubernetesClusterSummaryData `json:"data,omitempty"`
}

func (k *KubernetesClusters) GetData() []KubernetesClusterSummaryData {
	if k == nil {
		return nil
	}
	return k.Data
}
