// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type KubernetesCluster struct {
	Data *KubernetesClusterData `json:"data,omitempty"`
}

func (k *KubernetesCluster) GetData() *KubernetesClusterData {
	if k == nil {
		return nil
	}
	return k.Data
}
