// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"time"
)

// KubernetesClusterDataPhase - The current phase of the cluster lifecycle
type KubernetesClusterDataPhase string

const (
	KubernetesClusterDataPhasePending      KubernetesClusterDataPhase = "Pending"
	KubernetesClusterDataPhaseProvisioning KubernetesClusterDataPhase = "Provisioning"
	KubernetesClusterDataPhaseProvisioned  KubernetesClusterDataPhase = "Provisioned"
	KubernetesClusterDataPhaseDeleting     KubernetesClusterDataPhase = "Deleting"
	KubernetesClusterDataPhaseFailed       KubernetesClusterDataPhase = "Failed"
)

func (e KubernetesClusterDataPhase) ToPointer() *KubernetesClusterDataPhase {
	return &e
}
func (e *KubernetesClusterDataPhase) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Pending":
		fallthrough
	case "Provisioning":
		fallthrough
	case "Provisioned":
		fallthrough
	case "Deleting":
		fallthrough
	case "Failed":
		*e = KubernetesClusterDataPhase(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KubernetesClusterDataPhase: %v", v)
	}
}

// ControlPlane - Control plane status information
type ControlPlane struct {
	Ready         *bool  `json:"ready,omitempty"`
	Replicas      *int64 `json:"replicas,omitempty"`
	ReadyReplicas *int64 `json:"ready_replicas,omitempty"`
}

func (c *ControlPlane) GetReady() *bool {
	if c == nil {
		return nil
	}
	return c.Ready
}

func (c *ControlPlane) GetReplicas() *int64 {
	if c == nil {
		return nil
	}
	return c.Replicas
}

func (c *ControlPlane) GetReadyReplicas() *int64 {
	if c == nil {
		return nil
	}
	return c.ReadyReplicas
}

// Workers - Worker nodes status information
type Workers struct {
	Replicas          *int64 `json:"replicas,omitempty"`
	ReadyReplicas     *int64 `json:"ready_replicas,omitempty"`
	AvailableReplicas *int64 `json:"available_replicas,omitempty"`
}

func (w *Workers) GetReplicas() *int64 {
	if w == nil {
		return nil
	}
	return w.Replicas
}

func (w *Workers) GetReadyReplicas() *int64 {
	if w == nil {
		return nil
	}
	return w.ReadyReplicas
}

func (w *Workers) GetAvailableReplicas() *int64 {
	if w == nil {
		return nil
	}
	return w.AvailableReplicas
}

// WorkerStatus - Current status of worker nodes. 'idle' when 0 workers, 'ready' when all workers are ready, 'scaling' when workers are being provisioned/removed, 'error' when a worker has failed.
type WorkerStatus string

const (
	WorkerStatusIdle    WorkerStatus = "idle"
	WorkerStatusReady   WorkerStatus = "ready"
	WorkerStatusScaling WorkerStatus = "scaling"
	WorkerStatusError   WorkerStatus = "error"
)

func (e WorkerStatus) ToPointer() *WorkerStatus {
	return &e
}
func (e *WorkerStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "idle":
		fallthrough
	case "ready":
		fallthrough
	case "scaling":
		fallthrough
	case "error":
		*e = WorkerStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WorkerStatus: %v", v)
	}
}

// KubernetesClusterDataName - Step identifier
type KubernetesClusterDataName string

const (
	KubernetesClusterDataNameInfrastructure KubernetesClusterDataName = "infrastructure"
	KubernetesClusterDataNameControlPlane   KubernetesClusterDataName = "control_plane"
	KubernetesClusterDataNameWorkers        KubernetesClusterDataName = "workers"
)

func (e KubernetesClusterDataName) ToPointer() *KubernetesClusterDataName {
	return &e
}
func (e *KubernetesClusterDataName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "infrastructure":
		fallthrough
	case "control_plane":
		fallthrough
	case "workers":
		*e = KubernetesClusterDataName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KubernetesClusterDataName: %v", v)
	}
}

// KubernetesClusterDataStatus - Current status of this step
type KubernetesClusterDataStatus string

const (
	KubernetesClusterDataStatusPending    KubernetesClusterDataStatus = "pending"
	KubernetesClusterDataStatusInProgress KubernetesClusterDataStatus = "in_progress"
	KubernetesClusterDataStatusCompleted  KubernetesClusterDataStatus = "completed"
)

func (e KubernetesClusterDataStatus) ToPointer() *KubernetesClusterDataStatus {
	return &e
}
func (e *KubernetesClusterDataStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "in_progress":
		fallthrough
	case "completed":
		*e = KubernetesClusterDataStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KubernetesClusterDataStatus: %v", v)
	}
}

type KubernetesClusterDataSteps struct {
	// Step identifier
	Name *KubernetesClusterDataName `json:"name,omitempty"`
	// Current status of this step
	Status *KubernetesClusterDataStatus `json:"status,omitempty"`
}

func (k *KubernetesClusterDataSteps) GetName() *KubernetesClusterDataName {
	if k == nil {
		return nil
	}
	return k.Name
}

func (k *KubernetesClusterDataSteps) GetStatus() *KubernetesClusterDataStatus {
	if k == nil {
		return nil
	}
	return k.Status
}

// KubernetesClusterDataType - The role of this node in the cluster
type KubernetesClusterDataType string

const (
	KubernetesClusterDataTypeControlPlane KubernetesClusterDataType = "control_plane"
	KubernetesClusterDataTypeWorker       KubernetesClusterDataType = "worker"
)

func (e KubernetesClusterDataType) ToPointer() *KubernetesClusterDataType {
	return &e
}
func (e *KubernetesClusterDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "control_plane":
		fallthrough
	case "worker":
		*e = KubernetesClusterDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KubernetesClusterDataType: %v", v)
	}
}

// KubernetesClusterDataAttributesStatus - Current status of the node
type KubernetesClusterDataAttributesStatus string

const (
	KubernetesClusterDataAttributesStatusReady    KubernetesClusterDataAttributesStatus = "ready"
	KubernetesClusterDataAttributesStatusPending  KubernetesClusterDataAttributesStatus = "pending"
	KubernetesClusterDataAttributesStatusFailed   KubernetesClusterDataAttributesStatus = "failed"
	KubernetesClusterDataAttributesStatusDeleting KubernetesClusterDataAttributesStatus = "deleting"
)

func (e KubernetesClusterDataAttributesStatus) ToPointer() *KubernetesClusterDataAttributesStatus {
	return &e
}
func (e *KubernetesClusterDataAttributesStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ready":
		fallthrough
	case "pending":
		fallthrough
	case "failed":
		fallthrough
	case "deleting":
		*e = KubernetesClusterDataAttributesStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KubernetesClusterDataAttributesStatus: %v", v)
	}
}

type Nodes struct {
	// Unique identifier for the node (machine name)
	ID *string `json:"id,omitempty"`
	// Name of the node
	Name *string `json:"name,omitempty"`
	// Hostname of the node
	Hostname *string `json:"hostname,omitempty"`
	// The Latitude server ID associated with this node
	ServerID *string `json:"server_id,omitempty"`
	// The role of this node in the cluster
	Type *KubernetesClusterDataType `json:"type,omitempty"`
	// Current status of the node
	Status *KubernetesClusterDataAttributesStatus `json:"status,omitempty"`
	// Primary IP address (external if available, otherwise internal)
	IP *string `json:"ip,omitempty"`
	// Internal/private IP address
	InternalIP *string `json:"internal_ip,omitempty"`
	// External/public IP address
	ExternalIP *string `json:"external_ip,omitempty"`
}

func (n *Nodes) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *Nodes) GetName() *string {
	if n == nil {
		return nil
	}
	return n.Name
}

func (n *Nodes) GetHostname() *string {
	if n == nil {
		return nil
	}
	return n.Hostname
}

func (n *Nodes) GetServerID() *string {
	if n == nil {
		return nil
	}
	return n.ServerID
}

func (n *Nodes) GetType() *KubernetesClusterDataType {
	if n == nil {
		return nil
	}
	return n.Type
}

func (n *Nodes) GetStatus() *KubernetesClusterDataAttributesStatus {
	if n == nil {
		return nil
	}
	return n.Status
}

func (n *Nodes) GetIP() *string {
	if n == nil {
		return nil
	}
	return n.IP
}

func (n *Nodes) GetInternalIP() *string {
	if n == nil {
		return nil
	}
	return n.InternalIP
}

func (n *Nodes) GetExternalIP() *string {
	if n == nil {
		return nil
	}
	return n.ExternalIP
}

// KubernetesClusterDataProject - The project this cluster belongs to
type KubernetesClusterDataProject struct {
	// The project ID
	ID *string `json:"id,omitempty"`
	// The project name
	Name *string `json:"name,omitempty"`
	// The project slug
	Slug *string `json:"slug,omitempty"`
}

func (k *KubernetesClusterDataProject) GetID() *string {
	if k == nil {
		return nil
	}
	return k.ID
}

func (k *KubernetesClusterDataProject) GetName() *string {
	if k == nil {
		return nil
	}
	return k.Name
}

func (k *KubernetesClusterDataProject) GetSlug() *string {
	if k == nil {
		return nil
	}
	return k.Slug
}

type KubernetesClusterDataAttributes struct {
	// The cluster name
	Name *string `json:"name,omitempty"`
	// The current phase of the cluster lifecycle
	Phase *KubernetesClusterDataPhase `json:"phase,omitempty"`
	// Whether the cluster is ready to accept workloads
	Ready *bool `json:"ready,omitempty"`
	// The URL endpoint for the Kubernetes API server
	ControlPlaneEndpoint *string `json:"control_plane_endpoint,omitempty"`
	// The URL to retrieve the kubeconfig file
	KubeconfigURL *string `json:"kubeconfig_url,omitempty"`
	// The site/region where the cluster is deployed
	Location *string `json:"location,omitempty"`
	// IP addresses assigned to the cluster's load balancer
	LoadBalancerIps []string `json:"load_balancer_ips,omitempty"`
	// The Kubernetes version running on the cluster
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`
	// When the cluster was created
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The machine plan slug for control plane nodes
	Plan *string `json:"plan,omitempty"`
	// The machine plan slug for worker nodes. Null if no workers exist.
	WorkerPlan *string `json:"worker_plan,omitempty"`
	// Number of control plane node replicas
	ControlPlaneCount *int64 `json:"control_plane_count,omitempty"`
	// Number of worker node replicas. Returns 0 if no workers exist.
	WorkerCount *int64 `json:"worker_count,omitempty"`
	// Control plane status information
	ControlPlane *ControlPlane `json:"control_plane,omitempty"`
	// Worker nodes status information
	Workers *Workers `json:"workers,omitempty"`
	// Current status of worker nodes. 'idle' when 0 workers, 'ready' when all workers are ready, 'scaling' when workers are being provisioned/removed, 'error' when a worker has failed.
	WorkerStatus *WorkerStatus `json:"worker_status,omitempty"`
	// Whether the underlying infrastructure is ready
	InfrastructureReady *bool `json:"infrastructure_ready,omitempty"`
	// Whether the control plane is ready
	ControlPlaneReady *bool `json:"control_plane_ready,omitempty"`
	// Human-readable status message describing the current provisioning state
	Message *string `json:"message,omitempty"`
	// Provisioning progress steps for dashboard display
	Steps []KubernetesClusterDataSteps `json:"steps,omitempty"`
	// Timestamp of the most recent status condition change
	LastStatusChange *time.Time `json:"last_status_change,omitempty"`
	// Error message if the cluster has failed
	FailureMessage *string `json:"failure_message,omitempty"`
	// Reason code for cluster failure
	FailureReason *string `json:"failure_reason,omitempty"`
	// List of nodes (servers) in the cluster
	Nodes []Nodes `json:"nodes,omitempty"`
	// The project this cluster belongs to
	Project *KubernetesClusterDataProject `json:"project,omitempty"`
}

func (k KubernetesClusterDataAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KubernetesClusterDataAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KubernetesClusterDataAttributes) GetName() *string {
	if k == nil {
		return nil
	}
	return k.Name
}

func (k *KubernetesClusterDataAttributes) GetPhase() *KubernetesClusterDataPhase {
	if k == nil {
		return nil
	}
	return k.Phase
}

func (k *KubernetesClusterDataAttributes) GetReady() *bool {
	if k == nil {
		return nil
	}
	return k.Ready
}

func (k *KubernetesClusterDataAttributes) GetControlPlaneEndpoint() *string {
	if k == nil {
		return nil
	}
	return k.ControlPlaneEndpoint
}

func (k *KubernetesClusterDataAttributes) GetKubeconfigURL() *string {
	if k == nil {
		return nil
	}
	return k.KubeconfigURL
}

func (k *KubernetesClusterDataAttributes) GetLocation() *string {
	if k == nil {
		return nil
	}
	return k.Location
}

func (k *KubernetesClusterDataAttributes) GetLoadBalancerIps() []string {
	if k == nil {
		return nil
	}
	return k.LoadBalancerIps
}

func (k *KubernetesClusterDataAttributes) GetKubernetesVersion() *string {
	if k == nil {
		return nil
	}
	return k.KubernetesVersion
}

func (k *KubernetesClusterDataAttributes) GetCreatedAt() *time.Time {
	if k == nil {
		return nil
	}
	return k.CreatedAt
}

func (k *KubernetesClusterDataAttributes) GetPlan() *string {
	if k == nil {
		return nil
	}
	return k.Plan
}

func (k *KubernetesClusterDataAttributes) GetWorkerPlan() *string {
	if k == nil {
		return nil
	}
	return k.WorkerPlan
}

func (k *KubernetesClusterDataAttributes) GetControlPlaneCount() *int64 {
	if k == nil {
		return nil
	}
	return k.ControlPlaneCount
}

func (k *KubernetesClusterDataAttributes) GetWorkerCount() *int64 {
	if k == nil {
		return nil
	}
	return k.WorkerCount
}

func (k *KubernetesClusterDataAttributes) GetControlPlane() *ControlPlane {
	if k == nil {
		return nil
	}
	return k.ControlPlane
}

func (k *KubernetesClusterDataAttributes) GetWorkers() *Workers {
	if k == nil {
		return nil
	}
	return k.Workers
}

func (k *KubernetesClusterDataAttributes) GetWorkerStatus() *WorkerStatus {
	if k == nil {
		return nil
	}
	return k.WorkerStatus
}

func (k *KubernetesClusterDataAttributes) GetInfrastructureReady() *bool {
	if k == nil {
		return nil
	}
	return k.InfrastructureReady
}

func (k *KubernetesClusterDataAttributes) GetControlPlaneReady() *bool {
	if k == nil {
		return nil
	}
	return k.ControlPlaneReady
}

func (k *KubernetesClusterDataAttributes) GetMessage() *string {
	if k == nil {
		return nil
	}
	return k.Message
}

func (k *KubernetesClusterDataAttributes) GetSteps() []KubernetesClusterDataSteps {
	if k == nil {
		return nil
	}
	return k.Steps
}

func (k *KubernetesClusterDataAttributes) GetLastStatusChange() *time.Time {
	if k == nil {
		return nil
	}
	return k.LastStatusChange
}

func (k *KubernetesClusterDataAttributes) GetFailureMessage() *string {
	if k == nil {
		return nil
	}
	return k.FailureMessage
}

func (k *KubernetesClusterDataAttributes) GetFailureReason() *string {
	if k == nil {
		return nil
	}
	return k.FailureReason
}

func (k *KubernetesClusterDataAttributes) GetNodes() []Nodes {
	if k == nil {
		return nil
	}
	return k.Nodes
}

func (k *KubernetesClusterDataAttributes) GetProject() *KubernetesClusterDataProject {
	if k == nil {
		return nil
	}
	return k.Project
}

type KubernetesClusterData struct {
	// The cluster ID in hashed format (kc_<hash>)
	ID         *string                          `json:"id,omitempty"`
	Type       *string                          `json:"type,omitempty"`
	Attributes *KubernetesClusterDataAttributes `json:"attributes,omitempty"`
}

func (k *KubernetesClusterData) GetID() *string {
	if k == nil {
		return nil
	}
	return k.ID
}

func (k *KubernetesClusterData) GetType() *string {
	if k == nil {
		return nil
	}
	return k.Type
}

func (k *KubernetesClusterData) GetAttributes() *KubernetesClusterDataAttributes {
	if k == nil {
		return nil
	}
	return k.Attributes
}
