// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LifecycleRules struct {
	Data []LifecycleRuleData `json:"data,omitempty"`
}

func (l *LifecycleRules) GetData() []LifecycleRuleData {
	if l == nil {
		return nil
	}
	return l.Data
}
