// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LksCluster struct {
	Data *LksClusterData `json:"data,omitempty"`
}

func (l *LksCluster) GetData() *LksClusterData {
	if l == nil {
		return nil
	}
	return l.Data
}
