// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type LksClusterDataType string

const (
	LksClusterDataTypeLksClusters LksClusterDataType = "lks_clusters"
)

func (e LksClusterDataType) ToPointer() *LksClusterDataType {
	return &e
}
func (e *LksClusterDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "lks_clusters":
		*e = LksClusterDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LksClusterDataType: %v", v)
	}
}

// Network - Configured cluster CIDRs. Always present: the ranges are columns on the cluster with platform defaults.
type Network struct {
	PodCidrs     []string `json:"pod_cidrs,omitempty"`
	ServiceCidrs []string `json:"service_cidrs,omitempty"`
	NodeCidrs    []string `json:"node_cidrs,omitempty"`
}

func (n *Network) GetPodCidrs() []string {
	if n == nil {
		return nil
	}
	return n.PodCidrs
}

func (n *Network) GetServiceCidrs() []string {
	if n == nil {
		return nil
	}
	return n.ServiceCidrs
}

func (n *Network) GetNodeCidrs() []string {
	if n == nil {
		return nil
	}
	return n.NodeCidrs
}

type LksClusterDataAttributes struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	ProjectID   *string `json:"project_id,omitempty"`
	Site        *string `json:"site,omitempty"`
	// Lifecycle state (open enum, sourced from NetBox/controller)
	Status  *string `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	// Machine-readable status reason (open enum)
	Reason               *string `json:"reason,omitempty"`
	ControlPlaneEndpoint *string `json:"control_plane_endpoint,omitempty"`
	KubeconfigURL        *string `json:"kubeconfig_url,omitempty"`
	KubernetesVersion    *string `json:"kubernetes_version,omitempty"`
	PlatformVersion      *string `json:"platform_version,omitempty"`
	// Configured cluster CIDRs. Always present: the ranges are columns on the cluster with platform defaults.
	Network   *Network `json:"network,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
}

func (l *LksClusterDataAttributes) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *LksClusterDataAttributes) GetDescription() *string {
	if l == nil {
		return nil
	}
	return l.Description
}

func (l *LksClusterDataAttributes) GetProjectID() *string {
	if l == nil {
		return nil
	}
	return l.ProjectID
}

func (l *LksClusterDataAttributes) GetSite() *string {
	if l == nil {
		return nil
	}
	return l.Site
}

func (l *LksClusterDataAttributes) GetStatus() *string {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *LksClusterDataAttributes) GetMessage() *string {
	if l == nil {
		return nil
	}
	return l.Message
}

func (l *LksClusterDataAttributes) GetReason() *string {
	if l == nil {
		return nil
	}
	return l.Reason
}

func (l *LksClusterDataAttributes) GetControlPlaneEndpoint() *string {
	if l == nil {
		return nil
	}
	return l.ControlPlaneEndpoint
}

func (l *LksClusterDataAttributes) GetKubeconfigURL() *string {
	if l == nil {
		return nil
	}
	return l.KubeconfigURL
}

func (l *LksClusterDataAttributes) GetKubernetesVersion() *string {
	if l == nil {
		return nil
	}
	return l.KubernetesVersion
}

func (l *LksClusterDataAttributes) GetPlatformVersion() *string {
	if l == nil {
		return nil
	}
	return l.PlatformVersion
}

func (l *LksClusterDataAttributes) GetNetwork() *Network {
	if l == nil {
		return nil
	}
	return l.Network
}

func (l *LksClusterDataAttributes) GetCreatedAt() *string {
	if l == nil {
		return nil
	}
	return l.CreatedAt
}

func (l *LksClusterDataAttributes) GetUpdatedAt() *string {
	if l == nil {
		return nil
	}
	return l.UpdatedAt
}

type LksClusterData struct {
	ID         *string                   `json:"id,omitempty"`
	Type       *LksClusterDataType       `json:"type,omitempty"`
	Attributes *LksClusterDataAttributes `json:"attributes,omitempty"`
}

func (l *LksClusterData) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *LksClusterData) GetType() *LksClusterDataType {
	if l == nil {
		return nil
	}
	return l.Type
}

func (l *LksClusterData) GetAttributes() *LksClusterDataAttributes {
	if l == nil {
		return nil
	}
	return l.Attributes
}
