// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Effect string

const (
	EffectNoSchedule       Effect = "NoSchedule"
	EffectPreferNoSchedule Effect = "PreferNoSchedule"
	EffectNoExecute        Effect = "NoExecute"
)

func (e Effect) ToPointer() *Effect {
	return &e
}
func (e *Effect) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NoSchedule":
		fallthrough
	case "PreferNoSchedule":
		fallthrough
	case "NoExecute":
		*e = Effect(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Effect: %v", v)
	}
}

type LksNodePoolTaint struct {
	Key string `json:"key"`
	// May be empty; max 63 chars. Absent or null when the taint carries no value.
	Value  *string `json:"value,omitempty"`
	Effect Effect  `json:"effect"`
}

func (l *LksNodePoolTaint) GetKey() string {
	if l == nil {
		return ""
	}
	return l.Key
}

func (l *LksNodePoolTaint) GetValue() *string {
	if l == nil {
		return nil
	}
	return l.Value
}

func (l *LksNodePoolTaint) GetEffect() Effect {
	if l == nil {
		return Effect("")
	}
	return l.Effect
}
