// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type LksNodePoolDataType string

const (
	LksNodePoolDataTypeLksNodePools LksNodePoolDataType = "lks_node_pools"
)

func (e LksNodePoolDataType) ToPointer() *LksNodePoolDataType {
	return &e
}
func (e *LksNodePoolDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "lks_node_pools":
		*e = LksNodePoolDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LksNodePoolDataType: %v", v)
	}
}

type LksNodePoolDataAttributes struct {
	Name        *string `json:"name,omitempty"`
	Type        *string `json:"type,omitempty"`
	Mode        *string `json:"mode,omitempty"`
	Plan        *string `json:"plan,omitempty"`
	Description *string `json:"description,omitempty"`
	Count       *int64  `json:"count,omitempty"`
	// null when it was not set at creation — the platform default (110) applies
	MaxPodsPerNode    *int64  `json:"max_pods_per_node,omitempty"`
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`
	PlatformVersion   *string `json:"platform_version,omitempty"`
	Status            *string `json:"status,omitempty"`
	Message           *string `json:"message,omitempty"`
	// Machine-readable status reason (open enum)
	Reason     *string            `json:"reason,omitempty"`
	ReadyNodes *int64             `json:"ready_nodes,omitempty"`
	Labels     map[string]string  `json:"labels,omitempty"`
	Taints     []LksNodePoolTaint `json:"taints,omitempty"`
	CreatedAt  *string            `json:"created_at,omitempty"`
	UpdatedAt  *string            `json:"updated_at,omitempty"`
}

func (l *LksNodePoolDataAttributes) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *LksNodePoolDataAttributes) GetType() *string {
	if l == nil {
		return nil
	}
	return l.Type
}

func (l *LksNodePoolDataAttributes) GetMode() *string {
	if l == nil {
		return nil
	}
	return l.Mode
}

func (l *LksNodePoolDataAttributes) GetPlan() *string {
	if l == nil {
		return nil
	}
	return l.Plan
}

func (l *LksNodePoolDataAttributes) GetDescription() *string {
	if l == nil {
		return nil
	}
	return l.Description
}

func (l *LksNodePoolDataAttributes) GetCount() *int64 {
	if l == nil {
		return nil
	}
	return l.Count
}

func (l *LksNodePoolDataAttributes) GetMaxPodsPerNode() *int64 {
	if l == nil {
		return nil
	}
	return l.MaxPodsPerNode
}

func (l *LksNodePoolDataAttributes) GetKubernetesVersion() *string {
	if l == nil {
		return nil
	}
	return l.KubernetesVersion
}

func (l *LksNodePoolDataAttributes) GetPlatformVersion() *string {
	if l == nil {
		return nil
	}
	return l.PlatformVersion
}

func (l *LksNodePoolDataAttributes) GetStatus() *string {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *LksNodePoolDataAttributes) GetMessage() *string {
	if l == nil {
		return nil
	}
	return l.Message
}

func (l *LksNodePoolDataAttributes) GetReason() *string {
	if l == nil {
		return nil
	}
	return l.Reason
}

func (l *LksNodePoolDataAttributes) GetReadyNodes() *int64 {
	if l == nil {
		return nil
	}
	return l.ReadyNodes
}

func (l *LksNodePoolDataAttributes) GetLabels() map[string]string {
	if l == nil {
		return nil
	}
	return l.Labels
}

func (l *LksNodePoolDataAttributes) GetTaints() []LksNodePoolTaint {
	if l == nil {
		return nil
	}
	return l.Taints
}

func (l *LksNodePoolDataAttributes) GetCreatedAt() *string {
	if l == nil {
		return nil
	}
	return l.CreatedAt
}

func (l *LksNodePoolDataAttributes) GetUpdatedAt() *string {
	if l == nil {
		return nil
	}
	return l.UpdatedAt
}

type LksNodePoolData struct {
	ID         *string                    `json:"id,omitempty"`
	Type       *LksNodePoolDataType       `json:"type,omitempty"`
	Attributes *LksNodePoolDataAttributes `json:"attributes,omitempty"`
}

func (l *LksNodePoolData) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *LksNodePoolData) GetType() *LksNodePoolDataType {
	if l == nil {
		return nil
	}
	return l.Type
}

func (l *LksNodePoolData) GetAttributes() *LksNodePoolDataAttributes {
	if l == nil {
		return nil
	}
	return l.Attributes
}
