// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LksSitesMeta struct {
	Total *int64 `json:"total,omitempty"`
}

func (l *LksSitesMeta) GetTotal() *int64 {
	if l == nil {
		return nil
	}
	return l.Total
}

type LksSites struct {
	Data []LksSiteData `json:"data,omitempty"`
	Meta *LksSitesMeta `json:"meta,omitempty"`
}

func (l *LksSites) GetData() []LksSiteData {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *LksSites) GetMeta() *LksSitesMeta {
	if l == nil {
		return nil
	}
	return l.Meta
}
