// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ManagedDatabases struct {
	Data []ManagedDatabaseAttributes `json:"data,omitempty"`
}

func (m *ManagedDatabases) GetData() []ManagedDatabaseAttributes {
	if m == nil {
		return nil
	}
	return m.Data
}
