// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ManagedDatabase struct {
	Data *ManagedDatabaseAttributes `json:"data,omitempty"`
}

func (m *ManagedDatabase) GetData() *ManagedDatabaseAttributes {
	if m == nil {
		return nil
	}
	return m.Data
}
