// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ManagedDatabasePlanAttributesType string

const (
	ManagedDatabasePlanAttributesTypeManagedDatabasePlans ManagedDatabasePlanAttributesType = "managed_database_plans"
)

func (e ManagedDatabasePlanAttributesType) ToPointer() *ManagedDatabasePlanAttributesType {
	return &e
}
func (e *ManagedDatabasePlanAttributesType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "managed_database_plans":
		*e = ManagedDatabasePlanAttributesType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ManagedDatabasePlanAttributesType: %v", v)
	}
}

type ManagedDatabasePlanAttributesSpecs struct {
	CPU      *string `json:"cpu,omitempty"`
	Memory   *string `json:"memory,omitempty"`
	Storage  *string `json:"storage,omitempty"`
	Shards   *int64  `json:"shards,omitempty"`
	Replicas *int64  `json:"replicas,omitempty"`
	Iops     *string `json:"iops,omitempty"`
}

func (m *ManagedDatabasePlanAttributesSpecs) GetCPU() *string {
	if m == nil {
		return nil
	}
	return m.CPU
}

func (m *ManagedDatabasePlanAttributesSpecs) GetMemory() *string {
	if m == nil {
		return nil
	}
	return m.Memory
}

func (m *ManagedDatabasePlanAttributesSpecs) GetStorage() *string {
	if m == nil {
		return nil
	}
	return m.Storage
}

func (m *ManagedDatabasePlanAttributesSpecs) GetShards() *int64 {
	if m == nil {
		return nil
	}
	return m.Shards
}

func (m *ManagedDatabasePlanAttributesSpecs) GetReplicas() *int64 {
	if m == nil {
		return nil
	}
	return m.Replicas
}

func (m *ManagedDatabasePlanAttributesSpecs) GetIops() *string {
	if m == nil {
		return nil
	}
	return m.Iops
}

type ManagedDatabasePlanAttributesSite struct {
	ID       *string `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Slug     *string `json:"slug,omitempty"`
	Facility *string `json:"facility,omitempty"`
}

func (m *ManagedDatabasePlanAttributesSite) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *ManagedDatabasePlanAttributesSite) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *ManagedDatabasePlanAttributesSite) GetSlug() *string {
	if m == nil {
		return nil
	}
	return m.Slug
}

func (m *ManagedDatabasePlanAttributesSite) GetFacility() *string {
	if m == nil {
		return nil
	}
	return m.Facility
}

type ManagedDatabasePlanAttributesPricing struct {
	Month *float64 `json:"month,omitempty"`
	Year  *float64 `json:"year,omitempty"`
}

func (m *ManagedDatabasePlanAttributesPricing) GetMonth() *float64 {
	if m == nil {
		return nil
	}
	return m.Month
}

func (m *ManagedDatabasePlanAttributesPricing) GetYear() *float64 {
	if m == nil {
		return nil
	}
	return m.Year
}

type ManagedDatabasePlanAttributesRegions struct {
	Region  *string                                         `json:"region,omitempty"`
	City    *string                                         `json:"city,omitempty"`
	Country *string                                         `json:"country,omitempty"`
	Site    *ManagedDatabasePlanAttributesSite              `json:"site,omitempty"`
	Pricing map[string]ManagedDatabasePlanAttributesPricing `json:"pricing,omitempty"`
}

func (m *ManagedDatabasePlanAttributesRegions) GetRegion() *string {
	if m == nil {
		return nil
	}
	return m.Region
}

func (m *ManagedDatabasePlanAttributesRegions) GetCity() *string {
	if m == nil {
		return nil
	}
	return m.City
}

func (m *ManagedDatabasePlanAttributesRegions) GetCountry() *string {
	if m == nil {
		return nil
	}
	return m.Country
}

func (m *ManagedDatabasePlanAttributesRegions) GetSite() *ManagedDatabasePlanAttributesSite {
	if m == nil {
		return nil
	}
	return m.Site
}

func (m *ManagedDatabasePlanAttributesRegions) GetPricing() map[string]ManagedDatabasePlanAttributesPricing {
	if m == nil {
		return nil
	}
	return m.Pricing
}

type ManagedDatabasePlanAttributesAttributes struct {
	Name    *string                                `json:"name,omitempty"`
	Slug    *string                                `json:"slug,omitempty"`
	Engine  *string                                `json:"engine,omitempty"`
	Specs   *ManagedDatabasePlanAttributesSpecs    `json:"specs,omitempty"`
	Regions []ManagedDatabasePlanAttributesRegions `json:"regions,omitempty"`
}

func (m *ManagedDatabasePlanAttributesAttributes) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *ManagedDatabasePlanAttributesAttributes) GetSlug() *string {
	if m == nil {
		return nil
	}
	return m.Slug
}

func (m *ManagedDatabasePlanAttributesAttributes) GetEngine() *string {
	if m == nil {
		return nil
	}
	return m.Engine
}

func (m *ManagedDatabasePlanAttributesAttributes) GetSpecs() *ManagedDatabasePlanAttributesSpecs {
	if m == nil {
		return nil
	}
	return m.Specs
}

func (m *ManagedDatabasePlanAttributesAttributes) GetRegions() []ManagedDatabasePlanAttributesRegions {
	if m == nil {
		return nil
	}
	return m.Regions
}

type ManagedDatabasePlanAttributes struct {
	ID         *string                                  `json:"id,omitempty"`
	Type       *ManagedDatabasePlanAttributesType       `json:"type,omitempty"`
	Attributes *ManagedDatabasePlanAttributesAttributes `json:"attributes,omitempty"`
}

func (m *ManagedDatabasePlanAttributes) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *ManagedDatabasePlanAttributes) GetType() *ManagedDatabasePlanAttributesType {
	if m == nil {
		return nil
	}
	return m.Type
}

func (m *ManagedDatabasePlanAttributes) GetAttributes() *ManagedDatabasePlanAttributesAttributes {
	if m == nil {
		return nil
	}
	return m.Attributes
}
