// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type MarketplaceAppDataType string

const (
	MarketplaceAppDataTypeMarketplaceApps MarketplaceAppDataType = "marketplace_apps"
)

func (e MarketplaceAppDataType) ToPointer() *MarketplaceAppDataType {
	return &e
}
func (e *MarketplaceAppDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "marketplace_apps":
		*e = MarketplaceAppDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MarketplaceAppDataType: %v", v)
	}
}

type SystemRequirements struct {
	Vcpus       *int64 `json:"vcpus,omitempty"`
	MemoryInGb  *int64 `json:"memory_in_gb,omitempty"`
	StorageInGb *int64 `json:"storage_in_gb,omitempty"`
	Gpu         *bool  `json:"gpu,omitempty"`
}

func (s *SystemRequirements) GetVcpus() *int64 {
	if s == nil {
		return nil
	}
	return s.Vcpus
}

func (s *SystemRequirements) GetMemoryInGb() *int64 {
	if s == nil {
		return nil
	}
	return s.MemoryInGb
}

func (s *SystemRequirements) GetStorageInGb() *int64 {
	if s == nil {
		return nil
	}
	return s.StorageInGb
}

func (s *SystemRequirements) GetGpu() *bool {
	if s == nil {
		return nil
	}
	return s.Gpu
}

// DeploymentStrategy - How the app is delivered: cloud-init install on a stock OS image (user_data) or a pre-built disk image (image)
type DeploymentStrategy string

const (
	DeploymentStrategyUserData DeploymentStrategy = "user_data"
	DeploymentStrategyImage    DeploymentStrategy = "image"
)

func (e DeploymentStrategy) ToPointer() *DeploymentStrategy {
	return &e
}
func (e *DeploymentStrategy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user_data":
		fallthrough
	case "image":
		*e = DeploymentStrategy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeploymentStrategy: %v", v)
	}
}

type MarketplaceAppDataAttributes struct {
	Name               *string             `json:"name,omitempty"`
	Slug               *string             `json:"slug,omitempty"`
	Description        *string             `json:"description,omitempty"`
	ShortDescription   *string             `json:"short_description,omitempty"`
	Category           *string             `json:"category,omitempty"`
	Version            *string             `json:"version,omitempty"`
	SystemRequirements *SystemRequirements `json:"system_requirements,omitempty"`
	// How the app is delivered: cloud-init install on a stock OS image (user_data) or a pre-built disk image (image)
	DeploymentStrategy     *DeploymentStrategy `json:"deployment_strategy,omitempty"`
	DefaultOperatingSystem *string             `json:"default_operating_system,omitempty"`
	CompatiblePlans        []string            `json:"compatible_plans,omitempty"`
	AccessInstructions     *string             `json:"access_instructions,omitempty"`
	UpstreamURL            *string             `json:"upstream_url,omitempty"`
	DocumentationURL       *string             `json:"documentation_url,omitempty"`
	LogoURL                *string             `json:"logo_url,omitempty"`
	CreatedAt              *string             `json:"created_at,omitempty"`
}

func (m *MarketplaceAppDataAttributes) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MarketplaceAppDataAttributes) GetSlug() *string {
	if m == nil {
		return nil
	}
	return m.Slug
}

func (m *MarketplaceAppDataAttributes) GetDescription() *string {
	if m == nil {
		return nil
	}
	return m.Description
}

func (m *MarketplaceAppDataAttributes) GetShortDescription() *string {
	if m == nil {
		return nil
	}
	return m.ShortDescription
}

func (m *MarketplaceAppDataAttributes) GetCategory() *string {
	if m == nil {
		return nil
	}
	return m.Category
}

func (m *MarketplaceAppDataAttributes) GetVersion() *string {
	if m == nil {
		return nil
	}
	return m.Version
}

func (m *MarketplaceAppDataAttributes) GetSystemRequirements() *SystemRequirements {
	if m == nil {
		return nil
	}
	return m.SystemRequirements
}

func (m *MarketplaceAppDataAttributes) GetDeploymentStrategy() *DeploymentStrategy {
	if m == nil {
		return nil
	}
	return m.DeploymentStrategy
}

func (m *MarketplaceAppDataAttributes) GetDefaultOperatingSystem() *string {
	if m == nil {
		return nil
	}
	return m.DefaultOperatingSystem
}

func (m *MarketplaceAppDataAttributes) GetCompatiblePlans() []string {
	if m == nil {
		return nil
	}
	return m.CompatiblePlans
}

func (m *MarketplaceAppDataAttributes) GetAccessInstructions() *string {
	if m == nil {
		return nil
	}
	return m.AccessInstructions
}

func (m *MarketplaceAppDataAttributes) GetUpstreamURL() *string {
	if m == nil {
		return nil
	}
	return m.UpstreamURL
}

func (m *MarketplaceAppDataAttributes) GetDocumentationURL() *string {
	if m == nil {
		return nil
	}
	return m.DocumentationURL
}

func (m *MarketplaceAppDataAttributes) GetLogoURL() *string {
	if m == nil {
		return nil
	}
	return m.LogoURL
}

func (m *MarketplaceAppDataAttributes) GetCreatedAt() *string {
	if m == nil {
		return nil
	}
	return m.CreatedAt
}

type MarketplaceAppData struct {
	ID         *string                       `json:"id,omitempty"`
	Type       *MarketplaceAppDataType       `json:"type,omitempty"`
	Attributes *MarketplaceAppDataAttributes `json:"attributes,omitempty"`
}

func (m *MarketplaceAppData) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *MarketplaceAppData) GetType() *MarketplaceAppDataType {
	if m == nil {
		return nil
	}
	return m.Type
}

func (m *MarketplaceAppData) GetAttributes() *MarketplaceAppDataAttributes {
	if m == nil {
		return nil
	}
	return m.Attributes
}
