// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Total struct {
	// Total number of records, returned when `stats[total]=count` is requested
	Count *int64 `json:"count,omitempty"`
}

func (t *Total) GetCount() *int64 {
	if t == nil {
		return nil
	}
	return t.Count
}

type Stats struct {
	Total *Total `json:"total,omitempty"`
}

func (s *Stats) GetTotal() *Total {
	if s == nil {
		return nil
	}
	return s.Total
}

type PaginationMeta struct {
	Stats *Stats `json:"stats,omitempty"`
}

func (p *PaginationMeta) GetStats() *Stats {
	if p == nil {
		return nil
	}
	return p.Stats
}
