// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlanMeta struct {
}

type Plan struct {
	Data *PlanData `json:"data,omitempty"`
	Meta *PlanMeta `json:"meta,omitempty"`
}

func (p *Plan) GetData() *PlanData {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *Plan) GetMeta() *PlanMeta {
	if p == nil {
		return nil
	}
	return p.Meta
}
