// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type BillingType string

const (
	BillingTypeYearly  BillingType = "Yearly"
	BillingTypeMonthly BillingType = "Monthly"
	BillingTypeHourly  BillingType = "Hourly"
	BillingTypeNormal  BillingType = "Normal"
	BillingTypeCustom  BillingType = "Custom"
)

func (e BillingType) ToPointer() *BillingType {
	return &e
}
func (e *BillingType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Yearly":
		fallthrough
	case "Monthly":
		fallthrough
	case "Hourly":
		fallthrough
	case "Normal":
		fallthrough
	case "Custom":
		*e = BillingType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingType: %v", v)
	}
}

type BillingMethod string

const (
	BillingMethodNormal                 BillingMethod = "Normal"
	BillingMethodNinetyFivethPercentile BillingMethod = "95th percentile"
)

func (e BillingMethod) ToPointer() *BillingMethod {
	return &e
}
func (e *BillingMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Normal":
		fallthrough
	case "95th percentile":
		*e = BillingMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingMethod: %v", v)
	}
}

type Environment string

const (
	EnvironmentDevelopment Environment = "Development"
	EnvironmentStaging     Environment = "Staging"
	EnvironmentProduction  Environment = "Production"
)

func (e Environment) ToPointer() *Environment {
	return &e
}
func (e *Environment) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Development":
		fallthrough
	case "Staging":
		fallthrough
	case "Production":
		*e = Environment(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Environment: %v", v)
	}
}

type ProjectStats struct {
	// The number of IP addresses assigned to the project
	IPAddresses *float64 `json:"ip_addresses,omitempty"`
	// The IP address prefixes in the project
	Prefixes *float64 `json:"prefixes,omitempty"`
	// The number of servers assigned to the project
	Servers *float64 `json:"servers,omitempty"`
	// The number of containers assigned to the project
	Containers *float64 `json:"containers,omitempty"`
	// The number of VLANs assigned to the project
	Vlans *float64 `json:"vlans,omitempty"`
}

func (p *ProjectStats) GetIPAddresses() *float64 {
	if p == nil {
		return nil
	}
	return p.IPAddresses
}

func (p *ProjectStats) GetPrefixes() *float64 {
	if p == nil {
		return nil
	}
	return p.Prefixes
}

func (p *ProjectStats) GetServers() *float64 {
	if p == nil {
		return nil
	}
	return p.Servers
}

func (p *ProjectStats) GetContainers() *float64 {
	if p == nil {
		return nil
	}
	return p.Containers
}

func (p *ProjectStats) GetVlans() *float64 {
	if p == nil {
		return nil
	}
	return p.Vlans
}

type ProjectBilling struct {
	SubscriptionID *string `json:"subscription_id,omitempty"`
	Type           *string `json:"type,omitempty"`
	Method         *string `json:"method,omitempty"`
}

func (p *ProjectBilling) GetSubscriptionID() *string {
	if p == nil {
		return nil
	}
	return p.SubscriptionID
}

func (p *ProjectBilling) GetType() *string {
	if p == nil {
		return nil
	}
	return p.Type
}

func (p *ProjectBilling) GetMethod() *string {
	if p == nil {
		return nil
	}
	return p.Method
}

type ProjectAttributes struct {
	// The project name
	Name *string `json:"name,omitempty"`
	// A unique project identifier
	Slug *string `json:"slug,omitempty"`
	// The project description
	Description   *string         `json:"description,omitempty"`
	BillingType   *BillingType    `json:"billing_type,omitempty"`
	BillingMethod *BillingMethod  `json:"billing_method,omitempty"`
	Cost          *string         `json:"cost,omitempty"`
	Environment   *Environment    `json:"environment,omitempty"`
	Stats         *ProjectStats   `json:"stats,omitempty"`
	Billing       *ProjectBilling `json:"billing,omitempty"`
	Team          *TeamInclude    `json:"team,omitempty"`
	CreatedAt     *string         `json:"created_at,omitempty"`
	UpdatedAt     *string         `json:"updated_at,omitempty"`
}

func (p *ProjectAttributes) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *ProjectAttributes) GetSlug() *string {
	if p == nil {
		return nil
	}
	return p.Slug
}

func (p *ProjectAttributes) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *ProjectAttributes) GetBillingType() *BillingType {
	if p == nil {
		return nil
	}
	return p.BillingType
}

func (p *ProjectAttributes) GetBillingMethod() *BillingMethod {
	if p == nil {
		return nil
	}
	return p.BillingMethod
}

func (p *ProjectAttributes) GetCost() *string {
	if p == nil {
		return nil
	}
	return p.Cost
}

func (p *ProjectAttributes) GetEnvironment() *Environment {
	if p == nil {
		return nil
	}
	return p.Environment
}

func (p *ProjectAttributes) GetStats() *ProjectStats {
	if p == nil {
		return nil
	}
	return p.Stats
}

func (p *ProjectAttributes) GetBilling() *ProjectBilling {
	if p == nil {
		return nil
	}
	return p.Billing
}

func (p *ProjectAttributes) GetTeam() *TeamInclude {
	if p == nil {
		return nil
	}
	return p.Team
}

func (p *ProjectAttributes) GetCreatedAt() *string {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *ProjectAttributes) GetUpdatedAt() *string {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}

type Project struct {
	// The project ID
	ID         *string            `json:"id,omitempty"`
	Attributes *ProjectAttributes `json:"attributes,omitempty"`
}

func (p *Project) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *Project) GetAttributes() *ProjectAttributes {
	if p == nil {
		return nil
	}
	return p.Attributes
}
