// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RegionCountry struct {
	Slug *string `json:"slug,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (r *RegionCountry) GetSlug() *string {
	if r == nil {
		return nil
	}
	return r.Slug
}

func (r *RegionCountry) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}
