// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Country struct {
	Slug *string `json:"slug,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (c *Country) GetSlug() *string {
	if c == nil {
		return nil
	}
	return c.Slug
}

func (c *Country) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

type RegionsAttributes struct {
	Slug    *string  `json:"slug,omitempty"`
	Name    *string  `json:"name,omitempty"`
	Country *Country `json:"country,omitempty"`
}

func (r *RegionsAttributes) GetSlug() *string {
	if r == nil {
		return nil
	}
	return r.Slug
}

func (r *RegionsAttributes) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *RegionsAttributes) GetCountry() *Country {
	if r == nil {
		return nil
	}
	return r.Country
}

type RegionsData struct {
	ID         *string            `json:"id,omitempty"`
	Attributes *RegionsAttributes `json:"attributes,omitempty"`
}

func (r *RegionsData) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RegionsData) GetAttributes() *RegionsAttributes {
	if r == nil {
		return nil
	}
	return r.Attributes
}

type Regions struct {
	Data []RegionsData `json:"data,omitempty"`
}

func (r *Regions) GetData() []RegionsData {
	if r == nil {
		return nil
	}
	return r.Data
}
