// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type RegionType string

const (
	RegionTypeRegions RegionType = "regions"
)

func (e RegionType) ToPointer() *RegionType {
	return &e
}
func (e *RegionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "regions":
		*e = RegionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RegionType: %v", v)
	}
}

type RegionCountry struct {
	Slug *string `json:"slug,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (r *RegionCountry) GetSlug() *string {
	if r == nil {
		return nil
	}
	return r.Slug
}

func (r *RegionCountry) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

type RegionAttributes struct {
	Slug     *string        `json:"slug,omitempty"`
	Name     *string        `json:"name,omitempty"`
	Facility *string        `json:"facility,omitempty"`
	Country  *RegionCountry `json:"country,omitempty"`
	Type     *string        `json:"type,omitempty"`
	// Location capabilities available at this location (e.g. `public_network`, `elastic_ip_bgp`).
	Features []string `json:"features,omitempty"`
	// The location's network group slug (e.g. `TYO`, `LON2`).
	NetworkGroup *string `json:"network_group,omitempty"`
}

func (r *RegionAttributes) GetSlug() *string {
	if r == nil {
		return nil
	}
	return r.Slug
}

func (r *RegionAttributes) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *RegionAttributes) GetFacility() *string {
	if r == nil {
		return nil
	}
	return r.Facility
}

func (r *RegionAttributes) GetCountry() *RegionCountry {
	if r == nil {
		return nil
	}
	return r.Country
}

func (r *RegionAttributes) GetType() *string {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *RegionAttributes) GetFeatures() []string {
	if r == nil {
		return nil
	}
	return r.Features
}

func (r *RegionAttributes) GetNetworkGroup() *string {
	if r == nil {
		return nil
	}
	return r.NetworkGroup
}

type RegionData struct {
	ID         *string           `json:"id,omitempty"`
	Type       *RegionType       `json:"type,omitempty"`
	Attributes *RegionAttributes `json:"attributes,omitempty"`
}

func (r *RegionData) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RegionData) GetType() *RegionType {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *RegionData) GetAttributes() *RegionAttributes {
	if r == nil {
		return nil
	}
	return r.Attributes
}

type Region struct {
	Data *RegionData `json:"data,omitempty"`
}

func (r *Region) GetData() *RegionData {
	if r == nil {
		return nil
	}
	return r.Data
}
