// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	Bearer *string `security:"scheme,type=apiKey,subtype=header,name=Authorization,env=latitudesh_bearer"`
}

func (s *Security) GetBearer() *string {
	if s == nil {
		return nil
	}
	return s.Bearer
}
