// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type SSHKeyDataType string

const (
	SSHKeyDataTypeSSHKeys SSHKeyDataType = "ssh_keys"
)

func (e SSHKeyDataType) ToPointer() *SSHKeyDataType {
	return &e
}
func (e *SSHKeyDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ssh_keys":
		*e = SSHKeyDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SSHKeyDataType: %v", v)
	}
}

type SSHKeyDataAttributes struct {
	// Name of the SSH Key
	Name *string `json:"name,omitempty"`
	// SSH Public Key
	PublicKey *string `json:"public_key,omitempty"`
	// SSH Key fingerprint
	Fingerprint *string      `json:"fingerprint,omitempty"`
	User        *UserInclude `json:"user,omitempty"`
	CreatedAt   *string      `json:"created_at,omitempty"`
	UpdatedAt   *string      `json:"updated_at,omitempty"`
}

func (s *SSHKeyDataAttributes) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SSHKeyDataAttributes) GetPublicKey() *string {
	if s == nil {
		return nil
	}
	return s.PublicKey
}

func (s *SSHKeyDataAttributes) GetFingerprint() *string {
	if s == nil {
		return nil
	}
	return s.Fingerprint
}

func (s *SSHKeyDataAttributes) GetUser() *UserInclude {
	if s == nil {
		return nil
	}
	return s.User
}

func (s *SSHKeyDataAttributes) GetCreatedAt() *string {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *SSHKeyDataAttributes) GetUpdatedAt() *string {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

type SSHKeyData struct {
	ID         *string               `json:"id,omitempty"`
	Type       SSHKeyDataType        `json:"type"`
	Attributes *SSHKeyDataAttributes `json:"attributes,omitempty"`
}

func (s *SSHKeyData) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SSHKeyData) GetType() SSHKeyDataType {
	if s == nil {
		return SSHKeyDataType("")
	}
	return s.Type
}

func (s *SSHKeyData) GetAttributes() *SSHKeyDataAttributes {
	if s == nil {
		return nil
	}
	return s.Attributes
}
