// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type StoragePlanDataType string

const (
	StoragePlanDataTypeStoragePlans StoragePlanDataType = "storage_plans"
)

func (e StoragePlanDataType) ToPointer() *StoragePlanDataType {
	return &e
}
func (e *StoragePlanDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "storage_plans":
		*e = StoragePlanDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StoragePlanDataType: %v", v)
	}
}

type StoragePlanStorageType string

const (
	StoragePlanStorageTypeFilesystem StoragePlanStorageType = "filesystem"
	StoragePlanStorageTypeObject     StoragePlanStorageType = "object"
)

func (e StoragePlanStorageType) ToPointer() *StoragePlanStorageType {
	return &e
}
func (e *StoragePlanStorageType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "filesystem":
		fallthrough
	case "object":
		*e = StoragePlanStorageType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StoragePlanStorageType: %v", v)
	}
}

type StoragePlanStorageClass string

const (
	StoragePlanStorageClassStandard        StoragePlanStorageClass = "standard"
	StoragePlanStorageClassHighPerformance StoragePlanStorageClass = "high_performance"
)

func (e StoragePlanStorageClass) ToPointer() *StoragePlanStorageClass {
	return &e
}
func (e *StoragePlanStorageClass) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "standard":
		fallthrough
	case "high_performance":
		*e = StoragePlanStorageClass(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StoragePlanStorageClass: %v", v)
	}
}

type StoragePlanDataUSD struct {
	Month *float64 `json:"month,omitempty"`
}

func (s *StoragePlanDataUSD) GetMonth() *float64 {
	if s == nil {
		return nil
	}
	return s.Month
}

type StoragePlanDataBRL struct {
	Month *float64 `json:"month,omitempty"`
}

func (s *StoragePlanDataBRL) GetMonth() *float64 {
	if s == nil {
		return nil
	}
	return s.Month
}

type StoragePlanDataPricing struct {
	Usd *StoragePlanDataUSD `json:"USD,omitempty"`
	Brl *StoragePlanDataBRL `json:"BRL,omitempty"`
}

func (s *StoragePlanDataPricing) GetUsd() *StoragePlanDataUSD {
	if s == nil {
		return nil
	}
	return s.Usd
}

func (s *StoragePlanDataPricing) GetBrl() *StoragePlanDataBRL {
	if s == nil {
		return nil
	}
	return s.Brl
}

type StoragePlanDataRegions struct {
	Name      *string                 `json:"name,omitempty"`
	Locations []string                `json:"locations,omitempty"`
	Pricing   *StoragePlanDataPricing `json:"pricing,omitempty"`
}

func (s *StoragePlanDataRegions) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *StoragePlanDataRegions) GetLocations() []string {
	if s == nil {
		return nil
	}
	return s.Locations
}

func (s *StoragePlanDataRegions) GetPricing() *StoragePlanDataPricing {
	if s == nil {
		return nil
	}
	return s.Pricing
}

type StoragePlanDataAttributes struct {
	Name                    *string                  `json:"name,omitempty"`
	StoragePlanStorageType  *StoragePlanStorageType  `json:"storage_type,omitempty"`
	StoragePlanStorageClass *StoragePlanStorageClass `json:"storage_class,omitempty"`
	Regions                 []StoragePlanDataRegions `json:"regions,omitempty"`
}

func (s *StoragePlanDataAttributes) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *StoragePlanDataAttributes) GetStoragePlanStorageType() *StoragePlanStorageType {
	if s == nil {
		return nil
	}
	return s.StoragePlanStorageType
}

func (s *StoragePlanDataAttributes) GetStoragePlanStorageClass() *StoragePlanStorageClass {
	if s == nil {
		return nil
	}
	return s.StoragePlanStorageClass
}

func (s *StoragePlanDataAttributes) GetRegions() []StoragePlanDataRegions {
	if s == nil {
		return nil
	}
	return s.Regions
}

type StoragePlanData struct {
	ID         *string                    `json:"id,omitempty"`
	Type       *StoragePlanDataType       `json:"type,omitempty"`
	Attributes *StoragePlanDataAttributes `json:"attributes,omitempty"`
}

func (s *StoragePlanData) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *StoragePlanData) GetType() *StoragePlanDataType {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *StoragePlanData) GetAttributes() *StoragePlanDataAttributes {
	if s == nil {
		return nil
	}
	return s.Attributes
}
