// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type StoragePlanDataType string

const (
	StoragePlanDataTypeStoragePlans StoragePlanDataType = "storage_plans"
)

func (e StoragePlanDataType) ToPointer() *StoragePlanDataType {
	return &e
}
func (e *StoragePlanDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "storage_plans":
		*e = StoragePlanDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StoragePlanDataType: %v", v)
	}
}

type StorageType string

const (
	StorageTypeFilesystem StorageType = "filesystem"
	StorageTypeObject     StorageType = "object"
)

func (e StorageType) ToPointer() *StorageType {
	return &e
}
func (e *StorageType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "filesystem":
		fallthrough
	case "object":
		*e = StorageType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StorageType: %v", v)
	}
}

type StorageClass string

const (
	StorageClassStandard        StorageClass = "standard"
	StorageClassHighPerformance StorageClass = "high_performance"
)

func (e StorageClass) ToPointer() *StorageClass {
	return &e
}
func (e *StorageClass) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "standard":
		fallthrough
	case "high_performance":
		*e = StorageClass(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StorageClass: %v", v)
	}
}

type StoragePlanDataUSD struct {
	Month *float64 `json:"month,omitempty"`
}

func (s *StoragePlanDataUSD) GetMonth() *float64 {
	if s == nil {
		return nil
	}
	return s.Month
}

type StoragePlanDataBRL struct {
	Month *float64 `json:"month,omitempty"`
}

func (s *StoragePlanDataBRL) GetMonth() *float64 {
	if s == nil {
		return nil
	}
	return s.Month
}

type StoragePlanDataPricing struct {
	Usd *StoragePlanDataUSD `json:"USD,omitempty"`
	Brl *StoragePlanDataBRL `json:"BRL,omitempty"`
}

func (s *StoragePlanDataPricing) GetUsd() *StoragePlanDataUSD {
	if s == nil {
		return nil
	}
	return s.Usd
}

func (s *StoragePlanDataPricing) GetBrl() *StoragePlanDataBRL {
	if s == nil {
		return nil
	}
	return s.Brl
}

type StoragePlanDataRegions struct {
	Name      *string                 `json:"name,omitempty"`
	Locations []string                `json:"locations,omitempty"`
	Pricing   *StoragePlanDataPricing `json:"pricing,omitempty"`
}

func (s *StoragePlanDataRegions) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *StoragePlanDataRegions) GetLocations() []string {
	if s == nil {
		return nil
	}
	return s.Locations
}

func (s *StoragePlanDataRegions) GetPricing() *StoragePlanDataPricing {
	if s == nil {
		return nil
	}
	return s.Pricing
}

type StoragePlanDataAttributes struct {
	Name         *string                  `json:"name,omitempty"`
	StorageType  *StorageType             `json:"storage_type,omitempty"`
	StorageClass *StorageClass            `json:"storage_class,omitempty"`
	Regions      []StoragePlanDataRegions `json:"regions,omitempty"`
}

func (s *StoragePlanDataAttributes) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *StoragePlanDataAttributes) GetStorageType() *StorageType {
	if s == nil {
		return nil
	}
	return s.StorageType
}

func (s *StoragePlanDataAttributes) GetStorageClass() *StorageClass {
	if s == nil {
		return nil
	}
	return s.StorageClass
}

func (s *StoragePlanDataAttributes) GetRegions() []StoragePlanDataRegions {
	if s == nil {
		return nil
	}
	return s.Regions
}

type StoragePlanData struct {
	ID         *string                    `json:"id,omitempty"`
	Type       *StoragePlanDataType       `json:"type,omitempty"`
	Attributes *StoragePlanDataAttributes `json:"attributes,omitempty"`
}

func (s *StoragePlanData) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *StoragePlanData) GetType() *StoragePlanDataType {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *StoragePlanData) GetAttributes() *StoragePlanDataAttributes {
	if s == nil {
		return nil
	}
	return s.Attributes
}
