// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"github.com/latitudesh/latitudesh-go-sdk/types"
	"time"
)

type StorageUsageAttributes struct {
	// The day this usage row refers to
	Date *types.Date `json:"date,omitempty"`
	// The storage/bucket ID. A numeric value serialized as a string, e.g. "42".
	StorageID *string `json:"storage_id,omitempty"`
	// The project ID. A numeric value serialized as a string, e.g. "1234".
	ProjectID *string `json:"project_id,omitempty"`
	// Storage kind. One of: object, file, block.
	StorageType *string `json:"storage_type,omitempty"`
	// Performance tier. One of: high, standard.
	Tier   *string `json:"tier,omitempty"`
	Region *string `json:"region,omitempty"`
	// Canonical storage usage for the day, in bytes
	Bytes *int64 `json:"bytes,omitempty"`
	// The provider-reported usage value, in raw_unit
	RawValue *float64 `json:"raw_value,omitempty"`
	// The unit raw_value is expressed in
	RawUnit    *string    `json:"raw_unit,omitempty"`
	IngestedAt *time.Time `json:"ingested_at,omitempty"`
}

func (s StorageUsageAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StorageUsageAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StorageUsageAttributes) GetDate() *types.Date {
	if s == nil {
		return nil
	}
	return s.Date
}

func (s *StorageUsageAttributes) GetStorageID() *string {
	if s == nil {
		return nil
	}
	return s.StorageID
}

func (s *StorageUsageAttributes) GetProjectID() *string {
	if s == nil {
		return nil
	}
	return s.ProjectID
}

func (s *StorageUsageAttributes) GetStorageType() *string {
	if s == nil {
		return nil
	}
	return s.StorageType
}

func (s *StorageUsageAttributes) GetTier() *string {
	if s == nil {
		return nil
	}
	return s.Tier
}

func (s *StorageUsageAttributes) GetRegion() *string {
	if s == nil {
		return nil
	}
	return s.Region
}

func (s *StorageUsageAttributes) GetBytes() *int64 {
	if s == nil {
		return nil
	}
	return s.Bytes
}

func (s *StorageUsageAttributes) GetRawValue() *float64 {
	if s == nil {
		return nil
	}
	return s.RawValue
}

func (s *StorageUsageAttributes) GetRawUnit() *string {
	if s == nil {
		return nil
	}
	return s.RawUnit
}

func (s *StorageUsageAttributes) GetIngestedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.IngestedAt
}

type StorageUsageData struct {
	ID         *string                 `json:"id,omitempty"`
	Type       *string                 `json:"type,omitempty"`
	Attributes *StorageUsageAttributes `json:"attributes,omitempty"`
}

func (s *StorageUsageData) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *StorageUsageData) GetType() *string {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *StorageUsageData) GetAttributes() *StorageUsageAttributes {
	if s == nil {
		return nil
	}
	return s.Attributes
}

type StorageUsage struct {
	Data []StorageUsageData `json:"data,omitempty"`
}

func (s *StorageUsage) GetData() []StorageUsageData {
	if s == nil {
		return nil
	}
	return s.Data
}
