// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
)

type UpdateAPIKeyType string

const (
	UpdateAPIKeyTypeAPIKeys UpdateAPIKeyType = "api_keys"
)

func (e UpdateAPIKeyType) ToPointer() *UpdateAPIKeyType {
	return &e
}
func (e *UpdateAPIKeyType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "api_keys":
		*e = UpdateAPIKeyType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateAPIKeyType: %v", v)
	}
}

type UpdateAPIKeyAttributes struct {
	// Name of the API Key
	Name *string `default:"Name of the API Key" json:"name"`
	// The API version to use
	APIVersion *string `default:"2023-06-01" json:"api_version"`
}

func (u UpdateAPIKeyAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAPIKeyAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAPIKeyAttributes) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateAPIKeyAttributes) GetAPIVersion() *string {
	if u == nil {
		return nil
	}
	return u.APIVersion
}

type UpdateAPIKeyData struct {
	ID         *string                 `json:"id,omitempty"`
	Type       UpdateAPIKeyType        `json:"type"`
	Attributes *UpdateAPIKeyAttributes `json:"attributes,omitempty"`
}

func (u *UpdateAPIKeyData) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UpdateAPIKeyData) GetType() UpdateAPIKeyType {
	if u == nil {
		return UpdateAPIKeyType("")
	}
	return u.Type
}

func (u *UpdateAPIKeyData) GetAttributes() *UpdateAPIKeyAttributes {
	if u == nil {
		return nil
	}
	return u.Attributes
}

type UpdateAPIKey struct {
	Data *UpdateAPIKeyData `json:"data,omitempty"`
}

func (u *UpdateAPIKey) GetData() *UpdateAPIKeyData {
	if u == nil {
		return nil
	}
	return u.Data
}
