// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type UpdateElasticIPType string

const (
	UpdateElasticIPTypeElasticIps UpdateElasticIPType = "elastic_ips"
)

func (e UpdateElasticIPType) ToPointer() *UpdateElasticIPType {
	return &e
}
func (e *UpdateElasticIPType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "elastic_ips":
		*e = UpdateElasticIPType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateElasticIPType: %v", v)
	}
}

type UpdateElasticIPAttributes struct {
	// The server ID to move the Elastic IP to
	ServerID string `json:"server_id"`
}

func (u *UpdateElasticIPAttributes) GetServerID() string {
	if u == nil {
		return ""
	}
	return u.ServerID
}

type UpdateElasticIPData struct {
	Type       UpdateElasticIPType       `json:"type"`
	Attributes UpdateElasticIPAttributes `json:"attributes"`
}

func (u *UpdateElasticIPData) GetType() UpdateElasticIPType {
	if u == nil {
		return UpdateElasticIPType("")
	}
	return u.Type
}

func (u *UpdateElasticIPData) GetAttributes() UpdateElasticIPAttributes {
	if u == nil {
		return UpdateElasticIPAttributes{}
	}
	return u.Attributes
}

type UpdateElasticIP struct {
	Data UpdateElasticIPData `json:"data"`
}

func (u *UpdateElasticIP) GetData() UpdateElasticIPData {
	if u == nil {
		return UpdateElasticIPData{}
	}
	return u.Data
}
