// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type UpdatePublicNetworkIPType string

const (
	UpdatePublicNetworkIPTypePublicNetworks UpdatePublicNetworkIPType = "public_networks"
)

func (e UpdatePublicNetworkIPType) ToPointer() *UpdatePublicNetworkIPType {
	return &e
}
func (e *UpdatePublicNetworkIPType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "public_networks":
		*e = UpdatePublicNetworkIPType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdatePublicNetworkIPType: %v", v)
	}
}

type UpdatePublicNetworkIPAttributes struct {
	// The IPv4 address, e.g. 203.0.113.4
	Address string `json:"address"`
	// true reserves an available address so servers are never attached with it; false releases an address you reserved
	Reserved bool `json:"reserved"`
}

func (u *UpdatePublicNetworkIPAttributes) GetAddress() string {
	if u == nil {
		return ""
	}
	return u.Address
}

func (u *UpdatePublicNetworkIPAttributes) GetReserved() bool {
	if u == nil {
		return false
	}
	return u.Reserved
}

type UpdatePublicNetworkIPData struct {
	Type       UpdatePublicNetworkIPType        `json:"type"`
	Attributes *UpdatePublicNetworkIPAttributes `json:"attributes,omitempty"`
}

func (u *UpdatePublicNetworkIPData) GetType() UpdatePublicNetworkIPType {
	if u == nil {
		return UpdatePublicNetworkIPType("")
	}
	return u.Type
}

func (u *UpdatePublicNetworkIPData) GetAttributes() *UpdatePublicNetworkIPAttributes {
	if u == nil {
		return nil
	}
	return u.Attributes
}

type UpdatePublicNetworkIP struct {
	Data UpdatePublicNetworkIPData `json:"data"`
}

func (u *UpdatePublicNetworkIP) GetData() UpdatePublicNetworkIPData {
	if u == nil {
		return UpdatePublicNetworkIPData{}
	}
	return u.Data
}
