// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type UpdateLksClusterType string

const (
	UpdateLksClusterTypeLksClusters UpdateLksClusterType = "lks_clusters"
)

func (e UpdateLksClusterType) ToPointer() *UpdateLksClusterType {
	return &e
}
func (e *UpdateLksClusterType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "lks_clusters":
		*e = UpdateLksClusterType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateLksClusterType: %v", v)
	}
}

// UpdateLksClusterAttributes - At least one of name, description or kubernetes_version must be provided.
type UpdateLksClusterAttributes struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	// Setting a newer patch consents to a control-plane upgrade. Must not be lower than the current patch (422 DOWNGRADE_NOT_ALLOWED)
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`
}

func (u *UpdateLksClusterAttributes) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateLksClusterAttributes) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateLksClusterAttributes) GetKubernetesVersion() *string {
	if u == nil {
		return nil
	}
	return u.KubernetesVersion
}

type UpdateLksClusterData struct {
	Type UpdateLksClusterType `json:"type"`
	// At least one of name, description or kubernetes_version must be provided.
	Attributes *UpdateLksClusterAttributes `json:"attributes,omitempty"`
}

func (u *UpdateLksClusterData) GetType() UpdateLksClusterType {
	if u == nil {
		return UpdateLksClusterType("")
	}
	return u.Type
}

func (u *UpdateLksClusterData) GetAttributes() *UpdateLksClusterAttributes {
	if u == nil {
		return nil
	}
	return u.Attributes
}

type UpdateLksCluster struct {
	Data UpdateLksClusterData `json:"data"`
}

func (u *UpdateLksCluster) GetData() UpdateLksClusterData {
	if u == nil {
		return UpdateLksClusterData{}
	}
	return u.Data
}
