// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UserUpdateAttributes struct {
	FirstName              *string `json:"first_name,omitempty"`
	LastName               *string `json:"last_name,omitempty"`
	Email                  *string `json:"email,omitempty"`
	AuthenticationFactorID *string `json:"authentication_factor_id,omitempty"`
	Role                   *string `json:"role,omitempty"`
}

func (u *UserUpdateAttributes) GetFirstName() *string {
	if u == nil {
		return nil
	}
	return u.FirstName
}

func (u *UserUpdateAttributes) GetLastName() *string {
	if u == nil {
		return nil
	}
	return u.LastName
}

func (u *UserUpdateAttributes) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *UserUpdateAttributes) GetAuthenticationFactorID() *string {
	if u == nil {
		return nil
	}
	return u.AuthenticationFactorID
}

func (u *UserUpdateAttributes) GetRole() *string {
	if u == nil {
		return nil
	}
	return u.Role
}

type UserUpdate struct {
	ID         *string               `json:"id,omitempty"`
	Attributes *UserUpdateAttributes `json:"attributes,omitempty"`
}

func (u *UserUpdate) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UserUpdate) GetAttributes() *UserUpdateAttributes {
	if u == nil {
		return nil
	}
	return u.Attributes
}
