// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"time"
)

type UserRole struct {
	ID        *string    `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

func (u UserRole) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserRole) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserRole) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UserRole) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UserRole) GetCreatedAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.CreatedAt
}

func (u *UserRole) GetUpdatedAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.UpdatedAt
}

type UserAttributes struct {
	FirstName              *string       `json:"first_name,omitempty"`
	LastName               *string       `json:"last_name,omitempty"`
	Email                  *string       `json:"email,omitempty"`
	AuthenticationFactorID *string       `json:"authentication_factor_id,omitempty"`
	Role                   *UserRole     `json:"role,omitempty"`
	Teams                  []TeamInclude `json:"teams,omitempty"`
}

func (u *UserAttributes) GetFirstName() *string {
	if u == nil {
		return nil
	}
	return u.FirstName
}

func (u *UserAttributes) GetLastName() *string {
	if u == nil {
		return nil
	}
	return u.LastName
}

func (u *UserAttributes) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *UserAttributes) GetAuthenticationFactorID() *string {
	if u == nil {
		return nil
	}
	return u.AuthenticationFactorID
}

func (u *UserAttributes) GetRole() *UserRole {
	if u == nil {
		return nil
	}
	return u.Role
}

func (u *UserAttributes) GetTeams() []TeamInclude {
	if u == nil {
		return nil
	}
	return u.Teams
}

type User struct {
	ID         *string         `json:"id,omitempty"`
	Attributes *UserAttributes `json:"attributes,omitempty"`
}

func (u *User) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *User) GetAttributes() *UserAttributes {
	if u == nil {
		return nil
	}
	return u.Attributes
}
