// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UserDataObjectMeta struct {
}

type UserDataObject struct {
	Data *UserDataProperties `json:"data,omitempty"`
	Meta *UserDataObjectMeta `json:"meta,omitempty"`
}

func (u *UserDataObject) GetData() *UserDataProperties {
	if u == nil {
		return nil
	}
	return u.Data
}

func (u *UserDataObject) GetMeta() *UserDataObjectMeta {
	if u == nil {
		return nil
	}
	return u.Meta
}
