// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UserIncludeRole struct {
	ID        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

func (u *UserIncludeRole) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UserIncludeRole) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UserIncludeRole) GetCreatedAt() *string {
	if u == nil {
		return nil
	}
	return u.CreatedAt
}

func (u *UserIncludeRole) GetUpdatedAt() *string {
	if u == nil {
		return nil
	}
	return u.UpdatedAt
}

type UserInclude struct {
	ID                     *string          `json:"id,omitempty"`
	FirstName              *string          `json:"first_name,omitempty"`
	LastName               *string          `json:"last_name,omitempty"`
	Email                  *string          `json:"email,omitempty"`
	AuthenticationFactorID *string          `json:"authentication_factor_id,omitempty"`
	CreatedAt              *string          `json:"created_at,omitempty"`
	UpdatedAt              *string          `json:"updated_at,omitempty"`
	Role                   *UserIncludeRole `json:"role,omitempty"`
}

func (u *UserInclude) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UserInclude) GetFirstName() *string {
	if u == nil {
		return nil
	}
	return u.FirstName
}

func (u *UserInclude) GetLastName() *string {
	if u == nil {
		return nil
	}
	return u.LastName
}

func (u *UserInclude) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *UserInclude) GetAuthenticationFactorID() *string {
	if u == nil {
		return nil
	}
	return u.AuthenticationFactorID
}

func (u *UserInclude) GetCreatedAt() *string {
	if u == nil {
		return nil
	}
	return u.CreatedAt
}

func (u *UserInclude) GetUpdatedAt() *string {
	if u == nil {
		return nil
	}
	return u.UpdatedAt
}

func (u *UserInclude) GetRole() *UserIncludeRole {
	if u == nil {
		return nil
	}
	return u.Role
}
