// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UserDataMeta struct {
}

type UserData struct {
	Data *UserDataProperties `json:"data,omitempty"`
	Meta *UserDataMeta       `json:"meta,omitempty"`
}

func (u *UserData) GetData() *UserDataProperties {
	if u == nil {
		return nil
	}
	return u.Data
}

func (u *UserData) GetMeta() *UserDataMeta {
	if u == nil {
		return nil
	}
	return u.Meta
}
