// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type VirtualMachineAttributesType string

const (
	VirtualMachineAttributesTypeVirtualMachines VirtualMachineAttributesType = "virtual_machines"
)

func (e VirtualMachineAttributesType) ToPointer() *VirtualMachineAttributesType {
	return &e
}
func (e *VirtualMachineAttributesType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "virtual_machines":
		*e = VirtualMachineAttributesType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VirtualMachineAttributesType: %v", v)
	}
}

type VirtualMachineAttributesStatus string

const (
	VirtualMachineAttributesStatusRunning            VirtualMachineAttributesStatus = "Running"
	VirtualMachineAttributesStatusConfiguringNetwork VirtualMachineAttributesStatus = "Configuring network"
	VirtualMachineAttributesStatusStarting           VirtualMachineAttributesStatus = "Starting"
	VirtualMachineAttributesStatusScheduling         VirtualMachineAttributesStatus = "Scheduling"
	VirtualMachineAttributesStatusScheduled          VirtualMachineAttributesStatus = "Scheduled"
)

func (e VirtualMachineAttributesStatus) ToPointer() *VirtualMachineAttributesStatus {
	return &e
}
func (e *VirtualMachineAttributesStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Running":
		fallthrough
	case "Configuring network":
		fallthrough
	case "Starting":
		fallthrough
	case "Scheduling":
		fallthrough
	case "Scheduled":
		*e = VirtualMachineAttributesStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VirtualMachineAttributesStatus: %v", v)
	}
}

type Credentials struct {
	Username *string  `json:"username,omitempty"`
	Host     *string  `json:"host,omitempty"`
	Password *string  `json:"password,omitempty"`
	SSHKeys  []string `json:"ssh_keys,omitempty"`
}

func (c *Credentials) GetUsername() *string {
	if c == nil {
		return nil
	}
	return c.Username
}

func (c *Credentials) GetHost() *string {
	if c == nil {
		return nil
	}
	return c.Host
}

func (c *Credentials) GetPassword() *string {
	if c == nil {
		return nil
	}
	return c.Password
}

func (c *Credentials) GetSSHKeys() []string {
	if c == nil {
		return nil
	}
	return c.SSHKeys
}

type VirtualMachineAttributesPlan struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (v *VirtualMachineAttributesPlan) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *VirtualMachineAttributesPlan) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

type VirtualMachineAttributesSpecs struct {
	Vcpu    *int64  `json:"vcpu,omitempty"`
	RAM     *string `json:"ram,omitempty"`
	Storage *string `json:"storage,omitempty"`
	Nic     *string `json:"nic,omitempty"`
	Gpu     *string `json:"gpu,omitempty"`
}

func (v *VirtualMachineAttributesSpecs) GetVcpu() *int64 {
	if v == nil {
		return nil
	}
	return v.Vcpu
}

func (v *VirtualMachineAttributesSpecs) GetRAM() *string {
	if v == nil {
		return nil
	}
	return v.RAM
}

func (v *VirtualMachineAttributesSpecs) GetStorage() *string {
	if v == nil {
		return nil
	}
	return v.Storage
}

func (v *VirtualMachineAttributesSpecs) GetNic() *string {
	if v == nil {
		return nil
	}
	return v.Nic
}

func (v *VirtualMachineAttributesSpecs) GetGpu() *string {
	if v == nil {
		return nil
	}
	return v.Gpu
}

type VirtualMachineAttributesAttributes struct {
	Name            *string                         `json:"name,omitempty"`
	CreatedAt       *string                         `json:"created_at,omitempty"`
	Status          *VirtualMachineAttributesStatus `json:"status,omitempty"`
	OperatingSystem *string                         `json:"operating_system,omitempty"`
	Credentials     *Credentials                    `json:"credentials,omitempty"`
	Plan            *VirtualMachineAttributesPlan   `json:"plan,omitempty"`
	Specs           *VirtualMachineAttributesSpecs  `json:"specs,omitempty"`
	Team            *TeamInclude                    `json:"team,omitempty"`
	Project         *ProjectInclude                 `json:"project,omitempty"`
}

func (v *VirtualMachineAttributesAttributes) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *VirtualMachineAttributesAttributes) GetCreatedAt() *string {
	if v == nil {
		return nil
	}
	return v.CreatedAt
}

func (v *VirtualMachineAttributesAttributes) GetStatus() *VirtualMachineAttributesStatus {
	if v == nil {
		return nil
	}
	return v.Status
}

func (v *VirtualMachineAttributesAttributes) GetOperatingSystem() *string {
	if v == nil {
		return nil
	}
	return v.OperatingSystem
}

func (v *VirtualMachineAttributesAttributes) GetCredentials() *Credentials {
	if v == nil {
		return nil
	}
	return v.Credentials
}

func (v *VirtualMachineAttributesAttributes) GetPlan() *VirtualMachineAttributesPlan {
	if v == nil {
		return nil
	}
	return v.Plan
}

func (v *VirtualMachineAttributesAttributes) GetSpecs() *VirtualMachineAttributesSpecs {
	if v == nil {
		return nil
	}
	return v.Specs
}

func (v *VirtualMachineAttributesAttributes) GetTeam() *TeamInclude {
	if v == nil {
		return nil
	}
	return v.Team
}

func (v *VirtualMachineAttributesAttributes) GetProject() *ProjectInclude {
	if v == nil {
		return nil
	}
	return v.Project
}

type VirtualMachineAttributes struct {
	ID         *string                             `json:"id,omitempty"`
	Type       *VirtualMachineAttributesType       `json:"type,omitempty"`
	Attributes *VirtualMachineAttributesAttributes `json:"attributes,omitempty"`
}

func (v *VirtualMachineAttributes) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *VirtualMachineAttributes) GetType() *VirtualMachineAttributesType {
	if v == nil {
		return nil
	}
	return v.Type
}

func (v *VirtualMachineAttributes) GetAttributes() *VirtualMachineAttributesAttributes {
	if v == nil {
		return nil
	}
	return v.Attributes
}
