// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type VirtualMachineNetworkAttachmentCreatePayloadType string

const (
	VirtualMachineNetworkAttachmentCreatePayloadTypeVirtualMachineNetworkAttachments VirtualMachineNetworkAttachmentCreatePayloadType = "virtual_machine_network_attachments"
)

func (e VirtualMachineNetworkAttachmentCreatePayloadType) ToPointer() *VirtualMachineNetworkAttachmentCreatePayloadType {
	return &e
}
func (e *VirtualMachineNetworkAttachmentCreatePayloadType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "virtual_machine_network_attachments":
		*e = VirtualMachineNetworkAttachmentCreatePayloadType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VirtualMachineNetworkAttachmentCreatePayloadType: %v", v)
	}
}

type VirtualMachineNetworkAttachmentCreatePayloadAttributes struct {
	// VLAN id_hash to attach (e.g. vlan_abc123).
	VirtualNetworkID string `json:"virtual_network_id"`
	// Optional static IPv4 address with prefix (e.g. 10.0.0.5/24) for the NIC inside the guest. When omitted the NIC is configured for DHCP without a default route. Applying the regenerated network configuration requires running `sudo cloud-init clean --logs --reboot` inside the guest. Warning: that command makes cloud-init treat the next boot as a first boot — it re-runs the instance user-data (e.g. runcmd scripts) and regenerates the SSH host keys, so SSH clients will see a host-key changed warning.
	Address *string `json:"address,omitempty"`
}

func (v *VirtualMachineNetworkAttachmentCreatePayloadAttributes) GetVirtualNetworkID() string {
	if v == nil {
		return ""
	}
	return v.VirtualNetworkID
}

func (v *VirtualMachineNetworkAttachmentCreatePayloadAttributes) GetAddress() *string {
	if v == nil {
		return nil
	}
	return v.Address
}

type VirtualMachineNetworkAttachmentCreatePayloadData struct {
	Type       VirtualMachineNetworkAttachmentCreatePayloadType       `json:"type"`
	Attributes VirtualMachineNetworkAttachmentCreatePayloadAttributes `json:"attributes"`
}

func (v *VirtualMachineNetworkAttachmentCreatePayloadData) GetType() VirtualMachineNetworkAttachmentCreatePayloadType {
	if v == nil {
		return VirtualMachineNetworkAttachmentCreatePayloadType("")
	}
	return v.Type
}

func (v *VirtualMachineNetworkAttachmentCreatePayloadData) GetAttributes() VirtualMachineNetworkAttachmentCreatePayloadAttributes {
	if v == nil {
		return VirtualMachineNetworkAttachmentCreatePayloadAttributes{}
	}
	return v.Attributes
}

type VirtualMachineNetworkAttachmentCreatePayload struct {
	Data VirtualMachineNetworkAttachmentCreatePayloadData `json:"data"`
}

func (v *VirtualMachineNetworkAttachmentCreatePayload) GetData() VirtualMachineNetworkAttachmentCreatePayloadData {
	if v == nil {
		return VirtualMachineNetworkAttachmentCreatePayloadData{}
	}
	return v.Data
}
