// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
)

type VirtualMachinePayloadType string

const (
	VirtualMachinePayloadTypeVirtualMachines VirtualMachinePayloadType = "virtual_machines"
)

func (e VirtualMachinePayloadType) ToPointer() *VirtualMachinePayloadType {
	return &e
}
func (e *VirtualMachinePayloadType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "virtual_machines":
		*e = VirtualMachinePayloadType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VirtualMachinePayloadType: %v", v)
	}
}

type VirtualMachinePayloadAttributes struct {
	Name *string `default:"my-vm" json:"name"`
	Plan *string `json:"plan,omitempty"`
	// The site slug where the virtual machine will be deployed. Defaults to 'DAL' if not specified. To see which sites are available for a given plan, check the 'available' array in the plan's regions.
	Site    *string  `json:"site,omitempty"`
	SSHKeys []string `json:"ssh_keys,omitempty"`
	Project *string  `default:"my-project" json:"project"`
}

func (v VirtualMachinePayloadAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VirtualMachinePayloadAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VirtualMachinePayloadAttributes) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *VirtualMachinePayloadAttributes) GetPlan() *string {
	if v == nil {
		return nil
	}
	return v.Plan
}

func (v *VirtualMachinePayloadAttributes) GetSite() *string {
	if v == nil {
		return nil
	}
	return v.Site
}

func (v *VirtualMachinePayloadAttributes) GetSSHKeys() []string {
	if v == nil {
		return nil
	}
	return v.SSHKeys
}

func (v *VirtualMachinePayloadAttributes) GetProject() *string {
	if v == nil {
		return nil
	}
	return v.Project
}

type VirtualMachinePayloadData struct {
	Type       *VirtualMachinePayloadType       `json:"type,omitempty"`
	Attributes *VirtualMachinePayloadAttributes `json:"attributes,omitempty"`
}

func (v *VirtualMachinePayloadData) GetType() *VirtualMachinePayloadType {
	if v == nil {
		return nil
	}
	return v.Type
}

func (v *VirtualMachinePayloadData) GetAttributes() *VirtualMachinePayloadAttributes {
	if v == nil {
		return nil
	}
	return v.Attributes
}

type VirtualMachinePayload struct {
	Data *VirtualMachinePayloadData `json:"data,omitempty"`
}

func (v *VirtualMachinePayload) GetData() *VirtualMachinePayloadData {
	if v == nil {
		return nil
	}
	return v.Data
}
