// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/latitudesh/latitudesh-go-sdk/internal/utils"
	"time"
)

type Metric string

const (
	MetricCPU     Metric = "cpu"
	MetricMemory  Metric = "memory"
	MetricNetwork Metric = "network"
	MetricDisk    Metric = "disk"
)

func (e Metric) ToPointer() *Metric {
	return &e
}
func (e *Metric) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cpu":
		fallthrough
	case "memory":
		fallthrough
	case "network":
		fallthrough
	case "disk":
		*e = Metric(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Metric: %v", v)
	}
}

type Range string

const (
	RangeFivem       Range = "5m"
	RangeFifteenm    Range = "15m"
	RangeOneh        Range = "1h"
	RangeTwentyFourh Range = "24h"
)

func (e Range) ToPointer() *Range {
	return &e
}
func (e *Range) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "5m":
		fallthrough
	case "15m":
		fallthrough
	case "1h":
		fallthrough
	case "24h":
		*e = Range(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Range: %v", v)
	}
}

// Unit applied to every point value
type Unit string

const (
	UnitPercent        Unit = "percent"
	UnitBytesPerSecond Unit = "bytes_per_second"
)

func (e Unit) ToPointer() *Unit {
	return &e
}
func (e *Unit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "percent":
		fallthrough
	case "bytes_per_second":
		*e = Unit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Unit: %v", v)
	}
}

type Points struct {
	// ISO 8601 UTC timestamp (seconds precision)
	Timestamp *time.Time `json:"timestamp,omitempty"`
	// Sampled value, rounded to 2 decimal places
	Value *float64 `json:"value,omitempty"`
}

func (p Points) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Points) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Points) GetTimestamp() *time.Time {
	if p == nil {
		return nil
	}
	return p.Timestamp
}

func (p *Points) GetValue() *float64 {
	if p == nil {
		return nil
	}
	return p.Value
}

type VirtualMachineMetrics struct {
	Metric *Metric `json:"metric,omitempty"`
	Range  *Range  `json:"range,omitempty"`
	// Sampling interval between adjacent points (e.g. "15s", "1m")
	Step *string `json:"step,omitempty"`
	// Unit applied to every point value
	Unit   *Unit    `json:"unit,omitempty"`
	Points []Points `json:"points,omitempty"`
}

func (v *VirtualMachineMetrics) GetMetric() *Metric {
	if v == nil {
		return nil
	}
	return v.Metric
}

func (v *VirtualMachineMetrics) GetRange() *Range {
	if v == nil {
		return nil
	}
	return v.Range
}

func (v *VirtualMachineMetrics) GetStep() *string {
	if v == nil {
		return nil
	}
	return v.Step
}

func (v *VirtualMachineMetrics) GetUnit() *Unit {
	if v == nil {
		return nil
	}
	return v.Unit
}

func (v *VirtualMachineMetrics) GetPoints() []Points {
	if v == nil {
		return nil
	}
	return v.Points
}
