// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type VirtualMachineAttributesType string

const (
	VirtualMachineAttributesTypeVirtualMachines VirtualMachineAttributesType = "virtual_machines"
)

func (e VirtualMachineAttributesType) ToPointer() *VirtualMachineAttributesType {
	return &e
}
func (e *VirtualMachineAttributesType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "virtual_machines":
		*e = VirtualMachineAttributesType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VirtualMachineAttributesType: %v", v)
	}
}

// VirtualMachineAttributesFeatures - Features supported by this operating system
type VirtualMachineAttributesFeatures struct {
	// Whether RAID is supported
	Raid *bool `json:"raid,omitempty"`
	// Whether SSH keys are supported
	SSHKeys *bool `json:"ssh_keys,omitempty"`
	// Whether user data is supported
	UserData *bool `json:"user_data,omitempty"`
	// Whether rescue mode is supported
	Rescue *bool `json:"rescue,omitempty"`
	// Whether workflow is supported
	Workflow *bool `json:"workflow,omitempty"`
}

func (v *VirtualMachineAttributesFeatures) GetRaid() *bool {
	if v == nil {
		return nil
	}
	return v.Raid
}

func (v *VirtualMachineAttributesFeatures) GetSSHKeys() *bool {
	if v == nil {
		return nil
	}
	return v.SSHKeys
}

func (v *VirtualMachineAttributesFeatures) GetUserData() *bool {
	if v == nil {
		return nil
	}
	return v.UserData
}

func (v *VirtualMachineAttributesFeatures) GetRescue() *bool {
	if v == nil {
		return nil
	}
	return v.Rescue
}

func (v *VirtualMachineAttributesFeatures) GetWorkflow() *bool {
	if v == nil {
		return nil
	}
	return v.Workflow
}

// VirtualMachineAttributesDistro - Distribution information
type VirtualMachineAttributesDistro struct {
	// The name of the Linux distribution
	Name *string `json:"name,omitempty"`
	// The slug of the Linux distribution
	Slug *string `json:"slug,omitempty"`
	// The distribution series code name
	Series *string `json:"series,omitempty"`
}

func (v *VirtualMachineAttributesDistro) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *VirtualMachineAttributesDistro) GetSlug() *string {
	if v == nil {
		return nil
	}
	return v.Slug
}

func (v *VirtualMachineAttributesDistro) GetSeries() *string {
	if v == nil {
		return nil
	}
	return v.Series
}

// VirtualMachineAttributesOperatingSystem - The operating system installed on the virtual machine
type VirtualMachineAttributesOperatingSystem struct {
	// The full name of the operating system
	Name *string `json:"name,omitempty"`
	// The unique slug identifier for the operating system
	Slug *string `json:"slug,omitempty"`
	// The version of the operating system
	Version *string `json:"version,omitempty"`
	// Features supported by this operating system
	Features *VirtualMachineAttributesFeatures `json:"features,omitempty"`
	// Distribution information
	Distro *VirtualMachineAttributesDistro `json:"distro,omitempty"`
}

func (v *VirtualMachineAttributesOperatingSystem) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *VirtualMachineAttributesOperatingSystem) GetSlug() *string {
	if v == nil {
		return nil
	}
	return v.Slug
}

func (v *VirtualMachineAttributesOperatingSystem) GetVersion() *string {
	if v == nil {
		return nil
	}
	return v.Version
}

func (v *VirtualMachineAttributesOperatingSystem) GetFeatures() *VirtualMachineAttributesFeatures {
	if v == nil {
		return nil
	}
	return v.Features
}

func (v *VirtualMachineAttributesOperatingSystem) GetDistro() *VirtualMachineAttributesDistro {
	if v == nil {
		return nil
	}
	return v.Distro
}

// Credentials - SSH credentials for connecting to the virtual machine. Only available when the VM is running. Opt-in extra field: request via `extra_fields[virtual_machines]=credentials`.
type Credentials struct {
	// The SSH username for the VM, determined by the operating system (e.g., ubuntu, centos, ec2-user). Defaults to ubuntu if not specified by the OS.
	Username *string  `json:"username,omitempty"`
	Host     *string  `json:"host,omitempty"`
	Password *string  `json:"password,omitempty"`
	SSHKeys  []string `json:"ssh_keys,omitempty"`
}

func (c *Credentials) GetUsername() *string {
	if c == nil {
		return nil
	}
	return c.Username
}

func (c *Credentials) GetHost() *string {
	if c == nil {
		return nil
	}
	return c.Host
}

func (c *Credentials) GetPassword() *string {
	if c == nil {
		return nil
	}
	return c.Password
}

func (c *Credentials) GetSSHKeys() []string {
	if c == nil {
		return nil
	}
	return c.SSHKeys
}

type VirtualMachineAttributesPlan struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (v *VirtualMachineAttributesPlan) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *VirtualMachineAttributesPlan) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

type VirtualMachineAttributesSpecs struct {
	Vcpu    *int64  `json:"vcpu,omitempty"`
	RAM     *string `json:"ram,omitempty"`
	Storage *string `json:"storage,omitempty"`
	Nic     *string `json:"nic,omitempty"`
	Gpu     *string `json:"gpu,omitempty"`
}

func (v *VirtualMachineAttributesSpecs) GetVcpu() *int64 {
	if v == nil {
		return nil
	}
	return v.Vcpu
}

func (v *VirtualMachineAttributesSpecs) GetRAM() *string {
	if v == nil {
		return nil
	}
	return v.RAM
}

func (v *VirtualMachineAttributesSpecs) GetStorage() *string {
	if v == nil {
		return nil
	}
	return v.Storage
}

func (v *VirtualMachineAttributesSpecs) GetNic() *string {
	if v == nil {
		return nil
	}
	return v.Nic
}

func (v *VirtualMachineAttributesSpecs) GetGpu() *string {
	if v == nil {
		return nil
	}
	return v.Gpu
}

type VirtualMachineAttributesTags struct {
	ID          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Color       *string `json:"color,omitempty"`
}

func (v *VirtualMachineAttributesTags) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *VirtualMachineAttributesTags) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *VirtualMachineAttributesTags) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *VirtualMachineAttributesTags) GetColor() *string {
	if v == nil {
		return nil
	}
	return v.Color
}

type VirtualMachineAttributesAttributes struct {
	Name      *string `json:"name,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	// Current lifecycle status of the VM, derived from the underlying KubeVirt phase/printable status and capitalized. This is an open set that may grow over time — do not treat it as a closed enum. Known values include: Running, Starting, Stopped, Stopping, Failed, Off, Error, Rebooting, Deleting, Destroying, Configuring network, Scheduling, Scheduled, Provisioning.
	Status      *string `json:"status,omitempty"`
	PrimaryIpv4 *string `json:"primary_ipv4,omitempty"`
	// The operating system installed on the virtual machine
	OperatingSystem *VirtualMachineAttributesOperatingSystem `json:"operating_system,omitempty"`
	// SSH credentials for connecting to the virtual machine. Only available when the VM is running. Opt-in extra field: request via `extra_fields[virtual_machines]=credentials`.
	Credentials *Credentials `json:"credentials,omitempty"`
	Site        *string      `json:"site,omitempty"`
	Billing     *string      `json:"billing,omitempty"`
	// Encoded ID of the user data record applied to this VM, if any
	UserData *string                        `json:"user_data,omitempty"`
	Plan     *VirtualMachineAttributesPlan  `json:"plan,omitempty"`
	Specs    *VirtualMachineAttributesSpecs `json:"specs,omitempty"`
	Tags     []VirtualMachineAttributesTags `json:"tags,omitempty"`
	Team     *TeamInclude                   `json:"team,omitempty"`
	Project  *ProjectInclude                `json:"project,omitempty"`
	// Opt-in extra field. Request via `extra_fields[virtual_machines]=pending_restart`.
	PendingRestart *bool `json:"pending_restart,omitempty"`
}

func (v *VirtualMachineAttributesAttributes) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *VirtualMachineAttributesAttributes) GetCreatedAt() *string {
	if v == nil {
		return nil
	}
	return v.CreatedAt
}

func (v *VirtualMachineAttributesAttributes) GetStatus() *string {
	if v == nil {
		return nil
	}
	return v.Status
}

func (v *VirtualMachineAttributesAttributes) GetPrimaryIpv4() *string {
	if v == nil {
		return nil
	}
	return v.PrimaryIpv4
}

func (v *VirtualMachineAttributesAttributes) GetOperatingSystem() *VirtualMachineAttributesOperatingSystem {
	if v == nil {
		return nil
	}
	return v.OperatingSystem
}

func (v *VirtualMachineAttributesAttributes) GetCredentials() *Credentials {
	if v == nil {
		return nil
	}
	return v.Credentials
}

func (v *VirtualMachineAttributesAttributes) GetSite() *string {
	if v == nil {
		return nil
	}
	return v.Site
}

func (v *VirtualMachineAttributesAttributes) GetBilling() *string {
	if v == nil {
		return nil
	}
	return v.Billing
}

func (v *VirtualMachineAttributesAttributes) GetUserData() *string {
	if v == nil {
		return nil
	}
	return v.UserData
}

func (v *VirtualMachineAttributesAttributes) GetPlan() *VirtualMachineAttributesPlan {
	if v == nil {
		return nil
	}
	return v.Plan
}

func (v *VirtualMachineAttributesAttributes) GetSpecs() *VirtualMachineAttributesSpecs {
	if v == nil {
		return nil
	}
	return v.Specs
}

func (v *VirtualMachineAttributesAttributes) GetTags() []VirtualMachineAttributesTags {
	if v == nil {
		return nil
	}
	return v.Tags
}

func (v *VirtualMachineAttributesAttributes) GetTeam() *TeamInclude {
	if v == nil {
		return nil
	}
	return v.Team
}

func (v *VirtualMachineAttributesAttributes) GetProject() *ProjectInclude {
	if v == nil {
		return nil
	}
	return v.Project
}

func (v *VirtualMachineAttributesAttributes) GetPendingRestart() *bool {
	if v == nil {
		return nil
	}
	return v.PendingRestart
}

type VirtualMachineAttributes struct {
	ID         *string                             `json:"id,omitempty"`
	Type       *VirtualMachineAttributesType       `json:"type,omitempty"`
	Attributes *VirtualMachineAttributesAttributes `json:"attributes,omitempty"`
}

func (v *VirtualMachineAttributes) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *VirtualMachineAttributes) GetType() *VirtualMachineAttributesType {
	if v == nil {
		return nil
	}
	return v.Type
}

func (v *VirtualMachineAttributes) GetAttributes() *VirtualMachineAttributesAttributes {
	if v == nil {
		return nil
	}
	return v.Attributes
}
