// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type VpnSessionDataWithPasswordType string

const (
	VpnSessionDataWithPasswordTypeVpnSessions VpnSessionDataWithPasswordType = "vpn_sessions"
)

func (e VpnSessionDataWithPasswordType) ToPointer() *VpnSessionDataWithPasswordType {
	return &e
}
func (e *VpnSessionDataWithPasswordType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "vpn_sessions":
		*e = VpnSessionDataWithPasswordType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VpnSessionDataWithPasswordType: %v", v)
	}
}

// VpnSessionDataWithPasswordStatus - from Firewall Response
type VpnSessionDataWithPasswordStatus string

const (
	VpnSessionDataWithPasswordStatusEnable  VpnSessionDataWithPasswordStatus = "enable"
	VpnSessionDataWithPasswordStatusDisable VpnSessionDataWithPasswordStatus = "disable"
)

func (e VpnSessionDataWithPasswordStatus) ToPointer() *VpnSessionDataWithPasswordStatus {
	return &e
}
func (e *VpnSessionDataWithPasswordStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "enable":
		fallthrough
	case "disable":
		*e = VpnSessionDataWithPasswordStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VpnSessionDataWithPasswordStatus: %v", v)
	}
}

type VpnSessionDataWithPasswordAttributes struct {
	// VPN username
	UserName *string `json:"user_name,omitempty"`
	// VPN password
	Password *string `json:"password,omitempty"`
	// VPN port
	Port *string `json:"port,omitempty"`
	// VPN host
	Host   *string             `json:"host,omitempty"`
	Region *RegionResourceData `json:"region,omitempty"`
	// from Firewall Response
	Status *VpnSessionDataWithPasswordStatus `json:"status,omitempty"`
	// Time to expiry
	ExpiresAt *string `json:"expires_at,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

func (v *VpnSessionDataWithPasswordAttributes) GetUserName() *string {
	if v == nil {
		return nil
	}
	return v.UserName
}

func (v *VpnSessionDataWithPasswordAttributes) GetPassword() *string {
	if v == nil {
		return nil
	}
	return v.Password
}

func (v *VpnSessionDataWithPasswordAttributes) GetPort() *string {
	if v == nil {
		return nil
	}
	return v.Port
}

func (v *VpnSessionDataWithPasswordAttributes) GetHost() *string {
	if v == nil {
		return nil
	}
	return v.Host
}

func (v *VpnSessionDataWithPasswordAttributes) GetRegion() *RegionResourceData {
	if v == nil {
		return nil
	}
	return v.Region
}

func (v *VpnSessionDataWithPasswordAttributes) GetStatus() *VpnSessionDataWithPasswordStatus {
	if v == nil {
		return nil
	}
	return v.Status
}

func (v *VpnSessionDataWithPasswordAttributes) GetExpiresAt() *string {
	if v == nil {
		return nil
	}
	return v.ExpiresAt
}

func (v *VpnSessionDataWithPasswordAttributes) GetCreatedAt() *string {
	if v == nil {
		return nil
	}
	return v.CreatedAt
}

func (v *VpnSessionDataWithPasswordAttributes) GetUpdatedAt() *string {
	if v == nil {
		return nil
	}
	return v.UpdatedAt
}

type VpnSessionDataWithPassword struct {
	ID         *string                               `json:"id,omitempty"`
	Type       *VpnSessionDataWithPasswordType       `json:"type,omitempty"`
	Attributes *VpnSessionDataWithPasswordAttributes `json:"attributes,omitempty"`
}

func (v *VpnSessionDataWithPassword) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *VpnSessionDataWithPassword) GetType() *VpnSessionDataWithPasswordType {
	if v == nil {
		return nil
	}
	return v.Type
}

func (v *VpnSessionDataWithPassword) GetAttributes() *VpnSessionDataWithPasswordAttributes {
	if v == nil {
		return nil
	}
	return v.Attributes
}
