workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Latitudesh-OAS:
        inputs:
            - location: https://api.latitude.sh/api-docs/v3/swagger.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/latitude/latitude/latitudesh-oas
    api-docs:
        inputs:
            - location: https://api.latitude.sh/api-docs/v3/swagger.json
targets:
    latitudesh:
        target: go
        source: Latitudesh-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/latitude/latitude/latitudesh-oas-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
